/* UX/decision clarity pass: Guru placement, Player Hub fit logic, market sorting/actuals, trade explanations, cross-position impact. */
(function(){
  let fg24Sort='default', searchState={value:'',start:0,end:0}, sleeperActuals=null, sleeperActualKey='';
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const F=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
  const N=(v,d=1)=>F(v)?Number(v).toFixed(d):'—';
  const compact=n=>{n=Number(n||0);const a=Math.abs(n);if(a>=1e6)return (n/1e6).toFixed(a>=1e7?0:1).replace('.0','')+'M';if(a>=1e3)return (n/1e3).toFixed(a>=1e4?0:1).replace('.0','')+'K';return Math.round(n).toLocaleString()};

  function syncGateGuru(){
    const gate=$('gate'),onGate=gate&&!gate.classList.contains('hidden');
    document.body.classList.toggle('fg24Gate',!!onGate);
    const g=$('fg7Guru');if(g)g.classList.remove('fg8Expanded');
  }

  function allAnalysisPlayers(){const out=[],seen=new Set();const add=p=>{if(!p)return;const id=ident(p);if(!id||seen.has(id))return;seen.add(id);out.push(p)};for(const p of analysis?.waiver_pool||[])add(p);for(const t of analysis?.team_details||[])for(const p of t.players||[])add(p);return out}
  function rawById(){const m=new Map();for(const p of allAnalysisPlayers())m.set(ident(p),p);return m}

  function bestFits(){
    const m=mineTeam();if(!m)return[];const pr=needProfile(m),strict=typeof storedWaiverIdeas==='function'?storedWaiverIdeas():[],radar=typeof waiverRadar==='function'?waiverRadar():[],seen=new Set(),rows=[];
    for(const x of [...strict,...radar]){const a=x?.add;if(!a)continue;const id=ident(a);if(seen.has(id))continue;seen.add(id);const q=pos(a.position),need=needScore(pr,q),wg=Number(x.wg||0),rg=Number(x.rg||0),rv=Number(x.rv||0),wv=Number(x.waiverValue?.score||0);if(['K','DEF'].includes(q)&&wg<1.5&&rg<0.5)continue;const score=rg*5+wg*2+Math.max(-10,rv)*.03+need*9+wv*.04;rows.push({...x,add:a,need,score})}
    return rows.sort((a,b)=>b.score-a.score).slice(0,4)
  }
  function marketMovers(){return allAnalysisPlayers().filter(p=>Number(p.sleeper_adds_24h||0)||Number(p.sleeper_drops_24h||0)||Number(p.sleeper_net_24h||0)).sort((a,b)=>Math.abs(Number(b.sleeper_net_24h||0))-Math.abs(Number(a.sleeper_net_24h||0))).slice(0,4)}
  function polishHubOverview(){
    const grid=document.querySelector('.fg23HubGrid');if(!grid)return;const sections=[...grid.querySelectorAll(':scope>section')];if(sections.length<4)return;
    const fits=bestFits();sections[1].innerHTML=`<h3>📋 Best Roster Fits</h3>${fits.length?fits.map(x=>{const a=x.add,q=pos(a.position),drop=x.drop?.name?` · likely drop ${E(x.drop.name)}`:'';return `<button class="fg24Fit" data-fg24-tab="compare"><b>${E(a.name)} <span>${E(q)}</span></b><small>Addresses ${Math.round(x.need*100)}% ${E(q)} need · Week ${x.wg>=0?'+':''}${N(x.wg)} · ROS ${x.rg>=0?'+':''}${N(x.rg)}${drop}</small></button>`}).join(''):'<div class="muted">No available player currently improves the roster enough to call a best fit.</div>'}<div class="fg24Explain">Ranked by actual add/drop lineup impact plus your positional needs. K/DEF only rise here when they create a meaningful improvement.</div>`;
    const movers=marketMovers();sections[3].innerHTML=`<h3>🔥 Market Movers</h3>${movers.length?movers.map(p=>{const adds=Number(p.sleeper_adds_24h||0),drops=Number(p.sleeper_drops_24h||0),net=Number(p.sleeper_net_24h||0),label=net>=250?'HOT':net>0?'RISING':net<0?'FALLING':'STEADY';return `<div class="fg24Mover"><b>${E(p.name)} <span>${label}</span></b><small>${E(pos(p.position))} · Adds ${compact(adds)} · Drops ${compact(drops)} · Net ${net>=0?'+':''}${compact(net)} / 24h</small></div>`}).join(''):'<div class="muted">No strong Sleeper add/drop movement right now.</div>'}<div class="fg24Explain">Market activity is behavior, not a projection. It comes from Sleeper add/drop activity.</div>`;
    sections[1].querySelectorAll('[data-fg24-tab]').forEach(b=>b.onclick=()=>[...document.querySelectorAll('.fg17Tab')].find(x=>x.dataset.tab===b.dataset.fg24Tab)?.click());
  }

  function exactSleeperScore(row){const st=row?.stats||row||{},cfg=C?.league?.scoring_settings||{};let total=0,used=0;for(const[k,w]of Object.entries(cfg)){if(F(w)&&F(st[k])){total+=Number(w)*Number(st[k]);used++}}if(used)return Math.round(total*100)/100;const rec=Number(cfg.rec||0);if(rec>=.75&&F(st.pts_ppr))return Number(st.pts_ppr);if(rec>0&&F(st.pts_half_ppr))return Number(st.pts_half_ppr);return F(st.pts_std)?Number(st.pts_std):null}
  async function loadSleeperActuals(){
    if(String(C?.platform||'').toUpperCase()!=='SLEEPER')return null;const key=`${C?.league?.season||2026}:${C?.current_week||1}`;if(sleeperActualKey===key&&sleeperActuals)return sleeperActuals;sleeperActualKey=key;sleeperActuals=new Map();const season=C?.league?.season||2026,week=C?.current_week||1,urls=[`https://api.sleeper.app/stats/nfl/regular/${season}/${week}`,`https://api.sleeper.app/v1/stats/nfl/regular/${season}/${week}`];for(const u of urls){try{const r=await fetch(u);if(!r.ok)continue;const d=await r.json(),rows=Array.isArray(d)?d:Object.entries(d||{}).map(([id,v])=>({player_id:id,...(v||{})}));for(const x of rows){const id=String(x.player_id||x.player?.player_id||x.player?.id||'');if(id){const n=exactSleeperScore(x);if(F(n))sleeperActuals.set(id,Number(n))}}if(sleeperActuals.size)break}catch{}}return sleeperActuals}
  function contextActualMap(){const m=new Map(),add=p=>{if(!p)return;const id=ident(p);if(id&&F(p.actual_weekly_points))m.set(id,Number(p.actual_weekly_points))};for(const t of C?.league_teams||[])for(const p of t.players||[])add(p);for(const p of C?.available_trending_players||[])add(p);return m}
  async function patchActuals(){
    if(currentView!=='playerhub'||!document.querySelector('.fg17Rows'))return;const raw=rawById(),ctx=contextActualMap(),sl=await loadSleeperActuals();document.querySelectorAll('.fg17Row').forEach(row=>{const link=row.querySelector('.fg17PlayerLink');if(!link)return;const id=link.dataset.playerId,p=raw.get(id);let v=ctx.get(id);if(!F(v)&&sl&&p?.sleeper_id&&sl.has(String(p.sleeper_id)))v=sl.get(String(p.sleeper_id));if(F(v)){const b=row.children[1]?.querySelector('b');if(b){b.textContent=Number(v).toFixed(1);b.dataset.fg24Actual=String(v)}}});applySort()}

  function rowVal(row,mode){if(mode==='name')return String(row.querySelector('.fg17PlayerLink')?.textContent||'').toLowerCase();const idx={actual:1,week:2,ros:3}[mode];if(idx==null)return null;const t=row.children[idx]?.querySelector('b')?.textContent||'';const n=Number(String(t).replace(/[^0-9+-.]/g,''));return Number.isFinite(n)?n:-Infinity}
  function applySort(){const box=document.querySelector('.fg17Rows');if(!box||fg24Sort==='default')return;const rows=[...box.querySelectorAll(':scope>.fg17Row')];rows.sort((a,b)=>fg24Sort==='name'?String(rowVal(a,'name')).localeCompare(String(rowVal(b,'name'))):Number(rowVal(b,fg24Sort))-Number(rowVal(a,fg24Sort)));rows.forEach(r=>box.appendChild(r))}
  function installSort(){
    if(currentView!=='playerhub')return;const tools=document.querySelector('.fg17Tools');if(!tools||$('fg24Sort'))return;const s=document.createElement('select');s.id='fg24Sort';s.innerHTML='<option value="default">Sort: Default</option><option value="actual">Actual ↓</option><option value="week">Week Proj ↓</option><option value="ros">ROS ↓</option><option value="name">Name A–Z</option>';s.value=fg24Sort;s.onchange=()=>{fg24Sort=s.value;applySort()};tools.appendChild(s);const active=[...document.querySelectorAll('.fg17Tab.active')][0];if(active?.dataset.tab==='activity'&&!document.querySelector('.fg24MarketSource'))tools.insertAdjacentHTML('beforebegin','<div class="fg24MarketSource">Market Activity uses Sleeper add/drop behavior and FantasyCalc 30-day market movement. Actual points come from the league platform when verifiable; projections remain ESPN + Sleeper + ffanalytics.</div>')
  }

  function preserveSearch(e){if(e.target?.id!=='fg17Search')return;searchState={value:e.target.value,start:e.target.selectionStart??e.target.value.length,end:e.target.selectionEnd??e.target.value.length};requestAnimationFrame(()=>{const n=$('fg17Search');if(!n)return;n.focus();try{n.setSelectionRange(searchState.start,searchState.end)}catch{}})}

  function pctNeed(rank,n){return n<=1?0:Math.round(((Number(rank||n)-1)/(n-1))*100)}
  function posScore(roster,q){const count=Math.max(1,(C?.league?.roster_positions||[]).filter(s=>s===q).length),vals=(roster||[]).filter(p=>pos(p.position)===q&&F(p.ros_points)).map(p=>Number(p.ros_points)).sort((a,b)=>b-a);if(!vals.length)return 0;return vals.slice(0,count).reduce((a,b)=>a+b,0)/Math.min(count,vals.length)}
  function hypotheticalRank(roster,q){const mine=mineTeam(),mineScore=posScore(roster,q),others=(analysis?.team_details||[]).filter(t=>t!==mine&&String(t.roster_id)!==String(mine?.roster_id)).map(t=>{const k='ros_'+q.toLowerCase();return F(t[k])?Number(t[k]):posScore(t.players||[],q)});return 1+others.filter(v=>v>mineScore).length}
  function installCrossPositionImpact(){
    const box=$('fg17CompareResult'),d=$('fg17Drop'),a=$('fg17Add');if(!box||!d||!a)return;box.querySelector('.fg24CrossImpact')?.remove();const base=mineTeam()?.players||[],drop=base.find(p=>ident(p)===d.value),add=waiverPool().find(p=>ident(p)===a.value);if(!drop||!add)return;const after=base.filter(p=>ident(p)!==ident(drop)).concat(add),qs=[...new Set([pos(drop.position),pos(add.position)])].filter(q=>['QB','RB','WR','TE'].includes(q)),n=analysis?.team_details?.length||C?.league_teams?.length||10;if(!qs.length)return;const rows=qs.map(q=>{const br=hypotheticalRank(base,q),ar=hypotheticalRank(after,q),bp=pctNeed(br,n),ap=pctNeed(ar,n),dir=ar<br?'IMPROVES':ar>br?'WORSENS':'UNCHANGED';return `<div><b>${E(q)} ${dir}</b><span>League rank #${br} → #${ar} · need ${bp}% → ${ap}%</span></div>`}).join('');box.insertAdjacentHTML('beforeend',`<div class="fg24CrossImpact"><h4>Position impact after the swap</h4>${rows}<p>The weekly and ROS totals above already re-optimize your entire lineup; this shows which position got stronger and which position you weakened.</p></div>`)}

  function tradeImpactText(x){const give=x.give||[],get=x.get||[],sent=give.reduce((n,p)=>n+(F(p.ros_points)?Number(p.ros_points):0),0),recv=get.reduce((n,p)=>n+(F(p.ros_points)?Number(p.ros_points):0),0),delta=recv-sent,who=delta>0?'Projected ROS value favors you':delta<0?'Projected ROS value favors the other team':'Projected ROS value is even',need=get[0]?Math.round(needScore(needProfile(mineTeam()),get[0].position)*100):0;return `<div class="fg24ImpactGrid"><div><b>Your lineup</b><span>Week ${Number(x.wg||0)>=0?'+':''}${N(x.wg)} · ROS ${Number(x.rg||0)>=0?'+':''}${N(x.rg)}</span></div><div><b>Their lineup</b><span>Week ${Number(x.ow||0)>=0?'+':''}${N(x.ow)} · ROS ${Number(x.orr||0)>=0?'+':''}${N(x.orr)}</span></div><div><b>Projection value</b><span>You receive ${N(recv)} ROS / send ${N(sent)} → ${delta>=0?'+':''}${N(delta)} to you. ${who}.</span></div><div><b>Roster fit</b><span>You add ${E(pos(get[0]?.position))}, currently a ${need}% need. Any depth you lose from the players sent is included in the lineup impact above.</span></div></div>`}
  function renderTradeRadarPlain(){
    const active=[...document.querySelectorAll('.fg17Tab.active')].find(x=>x.dataset.tab==='trade');if(!active)return;const cards=[...document.querySelectorAll('.fg17Card')],card=cards.find(c=>/Trade Target Radar/i.test(c.querySelector('h3')?.textContent||''));if(!card||card.dataset.fg24)return;card.dataset.fg24='1';const ideas=typeof tradeIdeas==='function'?tradeIdeas():[],radar=typeof tradeRadar==='function'?tradeRadar():[],strict=new Set(ideas.flatMap(x=>(x.get||[]).map(ident))),filtered=radar.filter(x=>!strict.has(ident(x.get?.[0]))),show=(filtered.length?filtered:radar).slice(0,8);card.innerHTML=`<h3>Trade Target Radar</h3><div class="fg24Explain">Guru Trade Value is a 0–100 player value score. Projection balance tells you which side gets more projected ROS value; 100% means perfectly even.</div>${show.length?show.map((x,i)=>{const target=x.get?.[0],gtv=target?tradeValue(target).score:0,give=(x.give||[]).map(p=>`${E(p.name)} (${tradeValue(p).score})`).join(' + ')||'No framework',sent=(x.give||[]).reduce((n,p)=>n+(F(p.ros_points)?Number(p.ros_points):0),0),recv=(x.get||[]).reduce((n,p)=>n+(F(p.ros_points)?Number(p.ros_points):0),0),delta=recv-sent,fair=Math.round(Number(x.fr||0)*100);return `<div class="fg24Trade"><div class="fg24TradeTop"><div><b>${E(target?.name||'Target')}</b><span>${E(x.partner||'Opponent')} · Guru Trade Value ${gtv}/100</span></div><button type="button" data-fg24-impact="${i}">Trade Impact</button></div><div class="fg24TradeLine"><b>Possible offer:</b> ${give}</div><div class="fg24TradeLine"><b>Projection balance:</b> ${fair}% · You receive ${N(recv)} ROS / send ${N(sent)} → <strong class="${delta>=0?'good':'bad'}">${delta>=0?'+':''}${N(delta)} to you</strong></div>${x.marketFair!=null?`<div class="fg24TradeLine"><b>Market balance:</b> ${Math.round(Number(x.marketFair)*100)}% (closer to 100% is more even)</div>`:''}<div class="fg24Impact" data-fg24-panel="${i}" hidden>${tradeImpactText(x)}</div></div>`}).join(''):'<div class="muted">No realistic trade target clears the current filters.</div>'}`;card.querySelectorAll('[data-fg24-impact]').forEach(b=>b.onclick=()=>{const p=card.querySelector(`[data-fg24-panel="${b.dataset.fg24Impact}"]`);if(p)p.hidden=!p.hidden})}

  function enhanceHub(){if(currentView!=='playerhub')return;polishHubOverview();installSort();renderTradeRadarPlain();patchActuals();installCrossPositionImpact()}

  document.addEventListener('input',preserveSearch,true);
  document.addEventListener('change',e=>{if(e.target?.id==='fg17Drop'||e.target?.id==='fg17Add')setTimeout(installCrossPositionImpact,0)});
  document.addEventListener('click',e=>{if(e.target.closest?.('.fg20Row'))setTimeout(installCrossPositionImpact,0)});

  const style=document.createElement('style');style.textContent=`
    body.fg24Gate #fg7Guru,body.fg24Gate #fg11GuruShow{display:none!important}
    #fg8GuruToggle{display:none!important}
    #fg11GuruShow{top:auto!important;bottom:18px!important;right:18px!important;border-radius:999px!important}
    #fg7Guru{width:400px!important;max-width:calc(100vw - 28px)!important;height:min(560px,calc(100vh - 100px))!important;max-height:calc(100vh - 100px)!important;top:auto!important;bottom:16px!important}
    #fg7Guru.fg8Expanded{width:400px!important;height:min(560px,calc(100vh - 100px))!important;max-height:calc(100vh - 100px)!important}
    .fg24Explain,.fg24MarketSource{font-size:9px;line-height:1.4;color:#8fa6bf;background:#07111e;border:1px solid #223a53;border-radius:7px;padding:7px 8px;margin-top:7px}
    .fg24Fit{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid #1e324a;background:transparent;color:#e8f2ff;padding:8px 0;cursor:pointer}.fg24Fit:last-of-type{border-bottom:0}.fg24Fit b{font-size:11px}.fg24Fit b span{color:#7dd3fc}.fg24Fit small,.fg24Mover small{display:block;color:#8fa6bf;font-size:9px;margin-top:2px}.fg24Mover{padding:7px 0;border-bottom:1px solid #1e324a}.fg24Mover:last-of-type{border-bottom:0}.fg24Mover b{font-size:11px}.fg24Mover b span{font-size:8px;color:#7dd3fc;margin-left:5px}
    .fg17Tools{grid-template-columns:minmax(0,1fr) 110px 140px!important}.fg17Tools #fg24Sort{width:100%;background:#07111e;color:#e8f2ff;border:1px solid #28405d;border-radius:8px;padding:8px}
    .fg24CrossImpact{margin-top:9px;padding:10px;border:1px solid #31506d;border-radius:9px;background:#081827}.fg24CrossImpact h4{margin:0 0 7px;font-size:11px;color:#7dd3fc}.fg24CrossImpact>div{display:flex;justify-content:space-between;gap:10px;padding:5px 0;border-bottom:1px solid #1e324a}.fg24CrossImpact>div:last-of-type{border-bottom:0}.fg24CrossImpact b{font-size:10px}.fg24CrossImpact span,.fg24CrossImpact p{font-size:9px;color:#9fb0c2}.fg24CrossImpact p{margin:7px 0 0;line-height:1.4}
    .fg24Trade{border-top:1px solid #1e324a;padding:10px 0}.fg24Trade:first-of-type{border-top:0}.fg24TradeTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.fg24TradeTop>div{display:grid;gap:2px}.fg24TradeTop b{font-size:12px}.fg24TradeTop span{font-size:9px;color:#8fa6bf}.fg24TradeTop button{border:1px solid #2d5e86;background:#0b2033;color:#c9ecff;border-radius:7px;padding:6px 9px;font-size:9px;font-weight:900}.fg24TradeLine{font-size:9.5px;color:#b9cbe0;margin-top:5px;line-height:1.4}.fg24TradeLine b{color:#e8f2ff}.fg24Impact{margin-top:8px;border:1px solid #28405d;border-radius:8px;background:#07111e;padding:8px}.fg24ImpactGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.fg24ImpactGrid>div{border:1px solid #1e324a;border-radius:7px;padding:7px}.fg24ImpactGrid b{display:block;font-size:9px;color:#7dd3fc}.fg24ImpactGrid span{display:block;font-size:9px;color:#b9cbe0;margin-top:2px;line-height:1.35}
    @media(max-width:700px){#fg7Guru{left:8px!important;right:8px!important;width:auto!important;bottom:8px!important;height:min(72vh,620px)!important;max-height:72vh!important}.fg17Tools{grid-template-columns:1fr 1fr!important}.fg17Tools #fg17Search{grid-column:1/-1}.fg24ImpactGrid{grid-template-columns:1fr}.fg24CrossImpact>div{display:grid;gap:2px}}
  `;document.head.appendChild(style);

  function sync(){syncGateGuru();if($('fg7Guru'))$('fg7Guru').classList.remove('fg8Expanded');if(currentView==='playerhub')enhanceHub()}
  const obs=new MutationObserver(()=>requestAnimationFrame(sync));obs.observe(document.documentElement,{subtree:true,childList:true});
  const oldShow=showView;showView=function(v){const out=oldShow(v);setTimeout(sync,0);return out};
  const oldBack=backToLeagues;backToLeagues=function(){oldBack();setTimeout(syncGateGuru,0)};
  setTimeout(sync,0);
})();