/* Dashboard consolidation, analytics-week navigation, favorite-team news, Guru expansion polish, and trade-alert surface. */
(function(){
  let dashTab='overview',liveContext=null,liveWeek=null,teamNews=[],teamNewsTeam=null,weekBusy=false;
  const clone=x=>{try{return structuredClone(x)}catch{return JSON.parse(JSON.stringify(x))}};

  // Power Rankings belongs inside Dashboard now.
  const pi=NAV.findIndex(x=>x[0]==='power');if(pi>=0)NAV.splice(pi,1);

  function dashboardTabs(){return `<div class="fg22DashTabs"><button class="${dashTab==='overview'?'active':''}" data-fg22-dash="overview">Dashboard</button><button class="${dashTab==='power'?'active':''}" data-fg22-dash="power">Power Rankings</button></div>`}
  function wireDashTabs(){document.querySelectorAll('[data-fg22-dash]').forEach(b=>b.onclick=()=>{dashTab=b.dataset.fg22Dash||'overview';renderDashboard()})}
  function powerHTML(){const d=analysis?.ros;if(!d||d.blocked)return `<div class="fg22Power"><h2>🏆 Power Rankings</h2><div class="fg22Card"><div class="hold">WITHHELD</div><div class="muted">${esc(d?.message||'Trusted ranking data is incomplete.')}</div></div></div>`;const r=d.my_ranks||{};return `<div class="fg22Power"><div class="fg22Head"><div><h2>🏆 Power Rankings</h2><span>League-relative ROS strength from the same trusted projection consensus used everywhere else.</span></div></div><div class="rankGrid">${['qb','rb','wr','te','starters','overall'].map(k=>`<div class="rankBox"><span>${k.toUpperCase()}</span><b>#${r[k]||'—'} / ${C.league_teams.length}</b></div>`).join('')}</div><div class="fg22Card" style="margin-top:9px">${(d.power_rankings||[]).map((x,i)=>`<div class="rankRow ${x.team===C.my_team.team?'mine':''}"><b>${i+1}</b><span>${esc(x.team)}${x.team===C.my_team.team?' ← YOU':''}</span><b class="right">${Number(x.score).toFixed(1)}</b></div>`).join('')}</div></div>`}

  function favoriteKey(team){const map={ARI:['Cardinals','Arizona'],ATL:['Falcons','Atlanta'],BAL:['Ravens','Baltimore'],BUF:['Bills','Buffalo'],CAR:['Panthers','Carolina'],CHI:['Bears','Chicago'],CIN:['Bengals','Cincinnati'],CLE:['Browns','Cleveland'],DAL:['Cowboys','Dallas'],DEN:['Broncos','Denver'],DET:['Lions','Detroit'],GB:['Packers','Green Bay'],HOU:['Texans','Houston'],IND:['Colts','Indianapolis'],JAX:['Jaguars','Jacksonville'],KC:['Chiefs','Kansas City'],LV:['Raiders','Las Vegas'],LAC:['Chargers','Los Angeles Chargers'],LA:['Rams','Los Angeles Rams'],MIA:['Dolphins','Miami'],MIN:['Vikings','Minnesota'],NE:['Patriots','New England'],NO:['Saints','New Orleans'],NYG:['Giants','New York Giants'],NYJ:['Jets','New York Jets'],PHI:['Eagles','Philadelphia'],PIT:['Steelers','Pittsburgh'],SF:['49ers','San Francisco'],SEA:['Seahawks','Seattle'],TB:['Buccaneers','Tampa Bay'],TEN:['Titans','Tennessee'],WAS:['Commanders','Washington']};return map[team]||[team]}
  async function loadFavoriteNews(force=false){const team=localStorage.getItem('fg-favorite-team')||'IND';if(!force&&teamNewsTeam===team&&teamNews.length)return teamNews;teamNewsTeam=team;teamNews=[];try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${encodeURIComponent(team.toLowerCase())}/news?limit=8`);if(r.ok){const d=await r.json();teamNews=(d?.articles||[]).slice(0,5)}}catch{}if(!teamNews.length){const keys=favoriteKey(team).map(x=>String(x).toLowerCase());teamNews=(nflNews||[]).filter(a=>{const s=`${a?.headline||''} ${a?.description||''}`.toLowerCase();return keys.some(k=>s.includes(k))}).slice(0,5)}return teamNews}
  function favoriteCardHTML(){const team=localStorage.getItem('fg-favorite-team')||'IND',keys=favoriteKey(team),games=(nflGames||[]).filter(e=>{const g=fmtGame(e);return g.away===team||g.home===team}).slice(0,2);const news=teamNewsTeam===team?teamNews:[];return `<div class="fg6Title"><div><h2>⭐ ${esc(keys[0]||team)} News</h2><span>Recent ${esc(keys[0]||team)} headlines and schedule.</span></div></div>${games.map(fg6GameRow).join('')}${news.length?news.slice(0,4).map(a=>`<div class="fg6NewsRow"><a class="headline" target="_blank" rel="noopener" href="${a.links?.web?.href||'#'}">${esc(a.headline)}</a><span>${esc((a.description||'').slice(0,92))}</span></div>`).join(''):'<div class="muted fg22NewsLoading">Loading recent team news…</div>'}`}
  function enhanceFavoriteCard(){const card=document.querySelector('.fg6Bottom .fg6Card:first-child');if(!card)return;card.innerHTML=favoriteCardHTML();loadFavoriteNews().then(()=>{const c=document.querySelector('.fg6Bottom .fg6Card:first-child');if(c&&currentView==='dashboard'&&dashTab==='overview')c.innerHTML=favoriteCardHTML()})}

  function weekControls(){const w=Number(C?.current_week||1),isLive=Number(liveWeek)===w;return `<div class="fg22WeekCtl"><button id="fg22Prev" ${weekBusy||w<=1?'disabled':''}>←</button><div><span>Analytics Week</span><b>Week ${w}${isLive?' · CURRENT':''}</b></div><button id="fg22Next" ${weekBusy||w>=18?'disabled':''}>→</button>${!isLive?'<button id="fg22Now">Current Week</button>':''}</div>`}
  function installWeekControls(){const top=document.querySelector('.topbar');if(!top||!C)return;let box=$('fg22WeekCtl');if(!box){box=document.createElement('div');box.id='fg22WeekCtl';top.appendChild(box)}box.innerHTML=weekControls();$('fg22Prev')?.addEventListener('click',()=>switchWeek(Number(C.current_week)-1));$('fg22Next')?.addEventListener('click',()=>switchWeek(Number(C.current_week)+1));$('fg22Now')?.addEventListener('click',()=>switchWeek(Number(liveWeek)))}
  function scrubEspnWeekly(ctx){if(String(ctx?.platform||'').toUpperCase()!=='ESPN')return ctx;const clean=p=>{if(!p)return;p.espn_weekly_points=null;p.actual_weekly_points=null};for(const t of ctx.league_teams||[])for(const p of t.players||[])clean(p);for(const p of ctx.my_team?.players||[])clean(p);for(const p of ctx.available_trending_players||[])clean(p);return ctx}
  async function switchWeek(target){target=Math.max(1,Math.min(18,Number(target)||1));if(weekBusy||!liveContext||target===Number(C?.current_week))return;weekBusy=true;const wantedView=currentView==='power'?'dashboard':currentView;const oldTab=dashTab;try{C=clone(liveContext);C.current_week=target;if(target!==Number(liveWeek))scrubEspnWeekly(C);analysis=null;matchupData=null;rosterIntel=null;installWeekControls();$('content').innerHTML='<div class="loading">Loading Week '+target+' analytics…</div>';await loadAnalysis();$('topWeek').textContent=target;dashTab=oldTab;if(wantedView==='dashboard')renderDashboard();else showView(wantedView)}catch(e){$('content').innerHTML=`<div class="error">Could not load Week ${target}: ${esc(e.message||e)}</div>`}finally{weekBusy=false;installWeekControls()}}
  window.fg22SwitchWeek=switchWeek;

  async function sleeperTradeAlerts(l){try{const week=Number(C?.current_week||liveWeek||1),r=await fetch(`https://api.sleeper.app/v1/league/${encodeURIComponent(l.id)}/transactions/${week}`);if(!r.ok)return[];const rows=await r.json(),rid=Number(l.rid||l.roster_id);return (rows||[]).filter(x=>String(x.type).toLowerCase()==='trade'&&Array.isArray(x.roster_ids)&&x.roster_ids.map(Number).includes(rid)&&String(x.status||'').toLowerCase()!=='complete')}catch{return[]}}
  async function espnTradeAlerts(l){try{const r=await fetch(`/api/espn?leagueId=${encodeURIComponent(l.id)}&teamId=${encodeURIComponent(l.rid||l.roster_id)}&season=2026&mode=pending`);if(!r.ok)return[];const d=await r.json();return Array.isArray(d.pending_trades)?d.pending_trades:[]}catch{return[]}}
  async function checkTradeAlerts(){const ls=leagues(),hits=[];for(const l of ls){const rows=String(l.platform).toUpperCase()==='ESPN'?await espnTradeAlerts(l):await sleeperTradeAlerts(l);for(const x of rows)hits.push({league:l.name,platform:l.platform,tx:x})}let bar=$('fg22TradeAlert');if(!hits.length){bar?.remove();return hits}if(!bar){bar=document.createElement('button');bar.id='fg22TradeAlert';bar.onclick=()=>{dashTab='overview';showView('dashboard')};document.body.appendChild(bar)}bar.textContent=`🔔 ${hits.length} pending trade${hits.length===1?'':'s'} across your leagues`;return hits}
  window.fg22CheckTradeAlerts=checkTradeAlerts;

  const baseDashboard=renderDashboard;
  renderDashboard=function(){currentView='dashboard';if(dashTab==='power'){$('content').innerHTML=dashboardTabs()+powerHTML();wireDashTabs();installWeekControls();return}baseDashboard();const dash=document.querySelector('.fg6Dash');if(dash)dash.insertAdjacentHTML('beforebegin',dashboardTabs());wireDashTabs();enhanceFavoriteCard();installWeekControls();checkTradeAlerts()};

  const baseShow=showView;
  showView=function(v){if(v==='power'){dashTab='power';currentView='dashboard';$('nav')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view==='dashboard'));renderDashboard();return}if(v==='dashboard')dashTab='overview';baseShow(v);installWeekControls()};

  const baseOpen=openLeague;
  openLeague=async function(i){await baseOpen(i);if(C){liveContext=clone(C);liveWeek=Number(C.current_week||1);installWeekControls();checkTradeAlerts()}};

  const style=document.createElement('style');style.textContent=`
    .fg22DashTabs{display:flex;gap:5px;margin:0 0 9px}.fg22DashTabs button{border:1px solid #2d5e86;background:#0a1a2a;color:#c9ecff;border-radius:8px;padding:7px 11px;font-size:10px;font-weight:900;cursor:pointer}.fg22DashTabs button.active{background:#1597d1;color:#041b2a;border-color:#1597d1}.fg22Power{max-width:1100px}.fg22Card{background:#081524;border:1px solid #28405d;border-radius:11px;padding:10px 12px}.fg22Head{display:flex;justify-content:space-between;gap:8px;margin-bottom:9px}.fg22Head h2{margin:0}.fg22Head span{font-size:10px;color:#8fa6bf}.fg22WeekCtl{margin-left:auto;display:flex;align-items:center;gap:5px;border:1px solid #28405d;background:#071524;border-radius:9px;padding:4px 5px}.fg22WeekCtl>div{display:grid;min-width:95px;text-align:center}.fg22WeekCtl span{font-size:7px;color:#8fa6bf;text-transform:uppercase}.fg22WeekCtl b{font-size:10px}.fg22WeekCtl button{border:1px solid #31506d;background:#0b1828;color:#c9ecff;border-radius:6px;padding:5px 7px;font-size:9px;font-weight:850}.fg22WeekCtl button:disabled{opacity:.35}.fg22NewsLoading{padding:8px 0}#fg22TradeAlert{position:fixed;left:50%;transform:translateX(-50%);top:8px;z-index:500;border:1px solid #ca8a04;background:#3a2a06;color:#fde68a;border-radius:999px;padding:7px 12px;font-size:10px;font-weight:900;cursor:pointer}
    #fg7Guru.fg8Expanded{width:min(520px,calc(100vw - 36px))!important;height:calc(100vh - 82px)!important;max-height:none!important;box-shadow:0 18px 50px rgba(0,0,0,.45)!important}.fg8Expanded .fg7GuruHead{grid-template-columns:minmax(0,1fr) auto auto!important;padding:12px!important}.fg8Expanded .fg7GuruLog{padding:12px!important}.fg8Expanded .fg7Msg{font-size:12px!important;line-height:1.5!important;margin-left:0!important;margin-right:0!important}.fg8Expanded .fg7Compose{padding:10px!important}.fg8Expanded .fg7Compose textarea{min-height:72px!important;max-height:140px!important;font-size:12px!important}
    @media(max-width:900px){.fg22WeekCtl{position:fixed;top:10px;left:60px;right:auto;z-index:240}.fg22DashTabs{margin-left:50px}.fg22Power{max-width:none}#fg7Guru.fg8Expanded{width:auto!important}}
  `;document.head.appendChild(style);
})();
