const TEAM_FACTS_EXTRA={
ARI:['The franchise traces its lineage to Chicago and later played in St. Louis before moving to Arizona.','Larry Fitzgerald spent his entire NFL career with the Cardinals and became one of the league’s most productive receivers.'],
ATL:['The Falcons’ name was chosen through a fan contest before the team’s first season.','The team has played home games in the Georgia Dome and Mercedes-Benz Stadium.'],
BAL:['The Ravens name was inspired by Edgar Allan Poe, who lived and died in Baltimore.','Ray Lewis was a cornerstone of Baltimore’s first Super Bowl championship defense.'],
BUF:['The Bills name connects to Buffalo Bill Cody and was carried over from an earlier Buffalo football team.','Highmark Stadium is famous for one of the NFL’s most passionate tailgating cultures.'],
CAR:['The Panthers represent both North and South Carolina.','Carolina reached the NFC Championship Game in only its second season.'],
CHI:['George Halas helped found both the Bears and the NFL.','Soldier Field is one of the league’s most historic stadium sites.'],
CIN:['The striped tiger helmet became one of the NFL’s most distinctive looks in 1981.','The Bengals play in a division that features two franchises with direct Paul Brown connections.'],
CLE:['The Dawg Pound became one of the NFL’s most recognizable fan sections.','The current Browns resumed play in 1999 after Cleveland retained the team name, colors, and history.'],
DAL:['The “America’s Team” nickname became widely associated with Dallas in the late 1970s.','The Cowboys’ star logo is one of the most recognizable marks in American sports.'],
DEN:['The Broncos’ Orange Crush defense became famous during the late 1970s.','Denver’s high-altitude home field sits more than a mile above sea level.'],
DET:['The Lions franchise began as the Portsmouth Spartans before moving to Detroit.','Barry Sanders spent his entire Hall of Fame career with Detroit.'],
GB:['Lambeau Field opened in 1957 and is one of the NFL’s most iconic venues.','The Packers are named for the Indian Packing Company, an early sponsor of the team.'],
HOU:['The Texans replaced the Oilers as Houston’s NFL franchise.','The team’s bull-head logo incorporates the colors and shape of a Texas-inspired identity.'],
IND:['The Colts play their home games at Lucas Oil Stadium in downtown Indianapolis.','The franchise drafted Peyton Manning first overall in 1998, beginning one of the most successful eras in team history.'],
JAX:['Jacksonville’s teal identity has been part of the franchise since its 1995 debut.','The Jaguars reached the playoffs four times in their first five seasons.'],
KC:['Arrowhead Stadium is famous for one of the loudest home-field environments in football.','The Chiefs name and arrowhead identity date to the franchise’s move from Dallas to Kansas City.'],
LV:['The Raiders’ silver-and-black identity has remained consistent through multiple city moves.','Al Davis became one of the most influential owners and executives in pro football history.'],
LAC:['The Chargers’ “Air Coryell” offenses helped reshape modern passing football.','The franchise’s powder-blue uniforms are among the league’s most recognizable throwback looks.'],
LA:['The Rams introduced the first painted helmet design in pro football in 1948.','The franchise has won championships while representing both St. Louis and Los Angeles.'],
MIA:['Don Shula coached the Dolphins for 26 seasons.','The Dolphins’ aqua-and-orange color scheme is one of the NFL’s most distinctive.'],
MIN:['The Vikings’ Gjallarhorn is sounded before home games as part of the team’s pregame tradition.','Bud Grant coached Minnesota to four Super Bowl appearances.'],
NE:['The Patriots played at several Boston-area venues before settling in Foxborough.','The team adopted the “Flying Elvis” logo in the 1990s.'],
NO:['The Saints’ fleur-de-lis logo reflects New Orleans’ French heritage.','The Superdome has been the team’s home since 1975.'],
NYG:['The Giants are one of the NFL’s oldest continuously operating franchises.','Lawrence Taylor changed how offenses thought about protecting the quarterback.'],
NYJ:['The Jets began as the New York Titans before changing names in 1963.','Super Bowl III remains one of the defining upsets in pro football history.'],
PHI:['The “Philly Special” became one of the most famous plays in Super Bowl history.','Eagles fans have one of the league’s longest-running fight songs: “Fly, Eagles Fly.”'],
PIT:['The Steelers were originally called the Pittsburgh Pirates.','The Terrible Towel became one of the most recognizable fan traditions in sports.'],
SF:['Bill Walsh’s West Coast offense helped transform NFL passing strategy.','The 49ers name references prospectors from the 1849 California Gold Rush.'],
SEA:['The Seahawks’ 12s tradition celebrates the impact of their fan base.','Seattle originally played in the AFC before moving to the NFC in the 2002 realignment.'],
TB:['Tampa Bay’s original uniforms featured the “Bucco Bruce” pirate logo.','The Buccaneers have won Super Bowls with two different starting quarterbacks.'],
TEN:['The franchise used the Tennessee Oilers name before becoming the Titans.','The “Music City Miracle” is one of the most famous playoff returns in NFL history.'],
WAS:['The franchise has played home games in Washington, D.C., and Maryland.','Its three Super Bowl wins under Joe Gibbs came with Joe Theismann, Doug Williams, and Mark Rypien at quarterback.']
};
function allTeamFacts(team){return [...(TEAM_FACTS[team]||[]),...(TEAM_FACTS_EXTRA[team]||[])].slice(0,5)}
function impliedProb(ml){if(!finite(ml))return null;ml=Number(ml);return ml<0?(-ml)/((-ml)+100):100/(ml+100)}
function fmtGame(e){const c=e.competitions?.[0]||{},a=c.competitors||[],away=a.find(x=>x.homeAway==='away')||{},home=a.find(x=>x.homeAway==='home')||{},dt=e.date?new Date(e.date):null,status=c?.status?.type||{},completed=!!status.completed||status.state==='post',started=status.state==='in'||completed,odd=(c.odds||[])[0]||{},awayML=odd?.awayTeamOdds?.moneyLine??odd?.awayTeamOdds?.moneyline,homeML=odd?.homeTeamOdds?.moneyLine??odd?.homeTeamOdds?.moneyline;let vegas='';const ap=impliedProb(awayML),hp=impliedProb(homeML);if(ap!==null&&hp!==null){const z=ap+hp||1;vegas=`Vegas win: ${away?.team?.abbreviation||'Away'} ${Math.round(ap/z*100)}% · ${home?.team?.abbreviation||'Home'} ${Math.round(hp/z*100)}%`}else if(odd?.details)vegas=`Vegas: ${odd.details}`;const as=finite(away.score)?Number(away.score):null,hs=finite(home.score)?Number(home.score):null;return{away:away?.team?.abbreviation||'Away',home:home?.team?.abbreviation||'Home',date:dt?dt.toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'}):'',status:status.shortDetail||'',completed,started,awayScore:as,homeScore:hs,vegas}}
function gameLine(g){if(g.completed&&g.awayScore!==null&&g.homeScore!==null)return `<b>${g.away} ${g.awayScore} · ${g.home} ${g.homeScore}</b><div class="muted">Final</div>`;if(g.started&&g.awayScore!==null&&g.homeScore!==null)return `<b>${g.away} ${g.awayScore} · ${g.home} ${g.homeScore}</b><div class="muted">${esc(g.status)}</div>`;return `<b>${g.away} @ ${g.home}</b><div class="muted">${esc(g.date)} · ${esc(g.status)}${g.vegas?`<br>${esc(g.vegas)}`:''}</div>`}
function renderDashboard(){const ls=leagues(),fav=localStorage.getItem('fg-favorite-team')||'IND',facts=allTeamFacts(fav),favGames=nflGames.filter(e=>{const g=fmtGame(e);return g.away===fav||g.home===fav}).slice(0,2);$('content').innerHTML=`<h2>🏈 Fantasy Guru</h2><div class="sub">Your fantasy football command center.</div><div class="dashboardGrid"><div class="card dashLeague"><h3>🏆 League Hub</h3><div class="leagueTiles">${ls.map((x,i)=>`<button class="miniLeague ${String(x.id)===String(C.league.id)?'current':''}" data-i="${i}"><b>${esc(x.name)}</b><div class="leagueMeta">${esc(x.team)} · ${x.platform}</div></button>`).join('')}</div></div><div class="card dashFav"><h3>⭐ Favorite NFL Team</h3><select id="favTeam">${Object.keys(TEAM_FACTS).map(t=>`<option ${t===fav?'selected':''}>${t}</option>`).join('')}</select><div style="margin-top:7px">${favGames.length?favGames.map(e=>`<div class="row">${gameLine(fmtGame(e))}</div>`).join(''):'<div class="muted">No game in the current scoreboard window.</div>'}</div><div style="margin-top:7px"><b style="font-size:11px;color:#7dd3fc">TEAM TRIVIA</b>${facts.map(f=>`<div class="fact">💡 ${esc(f)}</div>`).join('')}</div></div><div class="card dashSchedule"><h3>📅 NFL Schedule</h3>${nflGames.slice(0,8).map(e=>`<div class="row">${gameLine(fmtGame(e))}</div>`).join('')||'<div class="muted">Loading schedule…</div>'}</div><div class="card dashNews"><h3>📰 NFL & Fantasy Watch</h3>${nflNews.slice(0,6).map(a=>`<div class="row"><a class="headline" target="_blank" rel="noopener" href="${a.links?.web?.href||'#'}">${esc(a.headline)}</a><div class="muted">${esc((a.description||'').slice(0,120))}</div></div>`).join('')||'<div class="muted">Loading headlines…</div>'}</div><div class="card dashAsk"><h3>🧠 Quick Ask Guru</h3><div class="quickAsk"><input id="quickQ" placeholder="Ask about this league, lineup, waivers or trades…"><button id="quickBtn">Ask</button></div></div></div>`;$('content').querySelectorAll('.miniLeague').forEach(b=>b.onclick=()=>openLeague(Number(b.dataset.i)));$('favTeam').onchange=()=>{localStorage.setItem('fg-favorite-team',$('favTeam').value);renderDashboard()};$('quickBtn').onclick=()=>{const q=$('quickQ').value.trim();if(!q)return;showView('guru');const box=$('guruQ');if(box){box.value=q;askGuru(q)}}}
function renderPower(){const d=analysis?.ros;if(!d||d.blocked){$('content').innerHTML='<h2>🏆 Power Rankings</h2><div class="card"><div class="hold">WITHHELD</div><div class="muted">Trusted ranking data is incomplete.</div></div>';return}const r=d.my_ranks||{};$('content').innerHTML=`<h2>🏆 Power Rankings</h2><div class="sub">League-relative values from the ESPN + Sleeper + ffanalytics consensus.</div><div class="rankGrid">${['qb','rb','wr','te','starters','overall'].map(k=>`<div class="rankBox"><span>${k.toUpperCase()}</span><b>#${r[k]||'—'} / ${C.league_teams.length}</b></div>`).join('')}</div><div class="card" style="margin-top:9px">${(d.power_rankings||[]).map((x,i)=>`<div class="rankRow ${x.team===C.my_team.team?'mine':''}"><b>${i+1}</b><span>${esc(x.team)}${x.team===C.my_team.team?' ← YOU':''}</span><b class="right">${Number(x.score).toFixed(1)}</b></div>`).join('')}</div>`}
function lineupRows(a=[]){return a.map(x=>`<div class="playerRow"><span>${esc(x.slot||'BN')}</span><span><b>${esc(x.name)}</b><div class="muted">${esc(x.position||'')}${x.injury_status?' · '+esc(x.injury_status):''}</div></span><span class="right">${x.actual_points==null?'—':Number(x.actual_points).toFixed(1)}</span><span class="right muted">${x.value==null?'—':Number(x.value).toFixed(1)}</span></div>`).join('')}
function lineupCard(title,lineup,bench){return `<div class="lineup" style="min-width:0"><div style="display:grid;grid-template-columns:48px 1fr 55px 55px;gap:5px;padding:0 0 5px;border-bottom:1px solid #26364f"><b style="grid-column:1/3">${esc(title)}</b><span class="muted right" style="font-size:9px">ACTUAL</span><span class="muted right" style="font-size:9px">PROJ</span></div>${lineupRows(lineup)}<div class="benchTitle">BENCH</div>${lineupRows(bench||[])}</div>`}
function renderMatchup(){const d=matchupData;if(!d?.available){$('content').innerHTML=`<h2>⚔️ Matchup</h2><div class="card muted">${esc(d?.message||'Matchup unavailable.')}</div>`;return}$('content').innerHTML=`<div style="max-width:1180px;margin:0 auto"><h2>⚔️ Matchup Center</h2><div class="sub">Live score from ${esc(d.score_source||C.platform)} · trusted weekly projection at right.</div><div class="matchHead" style="max-width:900px;margin:0 auto;padding:12px 18px"><div><div class="teamName">${esc(d.you.team)}</div><div class="actual">${Number(d.you.actual||0).toFixed(1)}</div><div class="projected">Projected ${Number(d.you.projection||0).toFixed(1)}</div></div><div><b style="font-size:16px">VS</b><div class="muted">Week ${C.current_week}</div></div><div><div class="teamName">${esc(d.them.team)}</div><div class="actual">${Number(d.them.actual||0).toFixed(1)}</div><div class="projected">Projected ${Number(d.them.projection||0).toFixed(1)}</div></div></div><div class="lineups" style="grid-template-columns:repeat(2,minmax(0,560px));justify-content:center;align-items:start">${lineupCard(d.you.team+' starters',d.you.lineup,d.you.bench)}${lineupCard(d.them.team+' starters',d.them.lineup,d.them.bench)}</div></div>`}
async function renderIntel(){const team=C.league_teams.find(t=>String(t.roster_id)===String(selectedIntel))||C.league_teams[0];$('content').innerHTML=`<h2>🩺 Roster Intel</h2><div class="sub">Current fantasy context for every player. Injury status comes from ${esc(C.platform)}; recent news/outlook is researched from current public sources.</div><div class="teamTabs">${C.league_teams.map(t=>`<button data-id="${t.roster_id}" class="${String(t.roster_id)===String(team.roster_id)?'active':''}">${esc(t.team)}${String(t.roster_id)===String(C.my_team.roster_id)?' · YOU':''}</button>`).join('')}</div><div id="intelData" class="card"><div class="loading">Researching current roster intel…</div></div>`;$('content').querySelectorAll('.teamTabs button').forEach(b=>b.onclick=()=>{selectedIntel=String(b.dataset.id);renderIntel()});try{const ctx={...C,my_team:{...C.my_team,team:team.team,roster_id:team.roster_id,players:team.players}},d=await get('/api/roster-intel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({context:ctx})});const td=(analysis?.team_details||[]).find(x=>String(x.roster_id)===String(team.roster_id)||x.team===team.team),map=new Map((td?.players||[]).map(p=>[String(p.name).toLowerCase(),p]));$('intelData').innerHTML=(d.players||[]).map(x=>{const p=map.get(String(x.name).toLowerCase()),wk=finite(p?.weekly_points)?Number(p.weekly_points).toFixed(1):'—',ros=finite(p?.ros_points)?Number(p.ros_points).toFixed(1):'—',kind=x.intel_type||'CURRENT OUTLOOK';return `<div class="intelRow"><div class="intelTop"><span><b>${esc(x.name)}</b><br><small>${esc(x.position||'')}${p?.team?' · '+esc(p.team):''}</small></span><b class="right">${wk}</b><b class="right">${esc(x.injury_status||'ACTIVE')}</b><span class="right muted" style="font-size:9px">ROS ${ros}</span></div><div style="margin-top:5px"><span class="pill" style="font-size:8px">${esc(kind)}</span> <span class="muted">${esc(x.intel||x.news||'No reliable current context found.')}</span></div></div>`}).join('')}catch(e){$('intelData').innerHTML=`<div class="error">Roster intel unavailable: ${esc(e.message)}</div>`}}
function guruKey(){return `fg-guru-history:${C?.platform||''}:${C?.league?.id||''}:${C?.my_team?.roster_id||''}`}
function guruHistory(){try{const h=JSON.parse(localStorage.getItem(guruKey())||'[]');return Array.isArray(h)?h.slice(-12):[]}catch{return[]}}
function saveGuruHistory(h){try{localStorage.setItem(guruKey(),JSON.stringify(h.slice(-12)))}catch{}}
function guruTranscript(h){if(!h.length)return'<div class="muted" style="padding:10px 0">Ask anything about this league, roster, waivers, trades, or a player.</div>';return h.map(x=>`<div style="margin:10px 0;padding:12px 14px;border:1px solid #29405d;border-radius:12px;background:${x.role==='user'?'#102238':'#0b1727'}"><div class="muted" style="font-size:11px;margin-bottom:6px">${x.role==='user'?'YOU':'GURU'}</div><div style="white-space:pre-wrap;line-height:1.45">${esc(x.content||'')}</div>${x.role==='assistant'&&x.follow_up?`<div style="margin-top:12px;padding-top:10px;border-top:1px solid #29405d"><b>Guru asks:</b> ${esc(x.follow_up)}</div>`:''}</div>`).join('')}
function renderGuru(){const h=guruHistory();$('content').innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><div><h2 style="margin-bottom:3px">🧠 Ask Guru</h2><div class="sub">League-specific conversation using current roster context and trusted values.</div></div><button class="btn" id="guruClear">＋ New Chat</button></div><div class="card" style="margin-top:10px"><div id="guruChat">${guruTranscript(h)}</div><div style="display:flex;gap:8px;align-items:flex-end;margin-top:12px"><textarea id="guruQ" rows="3" placeholder="Reply to Guru or ask a new question…" style="flex:1"></textarea><button class="btn" id="guruBtn">Send</button></div></div>`;$('guruBtn').onclick=()=>askGuru($('guruQ').value);$('guruQ').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();askGuru($('guruQ').value)}};$('guruClear').onclick=()=>{localStorage.removeItem(guruKey());renderGuru()};$('guruQ').focus()}
async function askGuru(q){q=String(q||'').trim();if(!q)return;const input=$('guruQ'),btn=$('guruBtn'),chat=$('guruChat'),prior=guruHistory();if(input)input.value='';if(btn)btn.disabled=true;if(!chat){showView('guru');const nextInput=$('guruQ');if(nextInput)nextInput.value=q;return askGuru(q)}chat.innerHTML=guruTranscript([...prior,{role:'user',content:q}])+`<div id="guruThinking" class="muted" style="padding:10px 4px">Guru is researching…</div>`;chat.scrollIntoView({block:'end',behavior:'smooth'});try{const d=await get('/api/guru',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,history:prior,context:C,analysis})}),answer=d.answer||'No answer returned.',follow=d.follow_up_question||'';const next=[...prior,{role:'user',content:q},{role:'assistant',content:answer,follow_up:follow}];saveGuruHistory(next);chat.innerHTML=guruTranscript(next);if(input){input.placeholder=follow||'Reply to Guru or ask another question…';input.focus()}}catch(e){chat.innerHTML=guruTranscript([...prior,{role:'user',content:q},{role:'assistant',content:'Ask Guru error: '+e.message,follow_up:''}])}finally{if(btn)btn.disabled=false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('gateAddBtn').onclick=showAddForm;gateRender();
