function renderShell(idx){const ls=leagues();$('leagueSelect').innerHTML=ls.map((x,i)=>`<option value="${i}" ${i===idx?'selected':''}>${esc(x.name)} — ${esc(x.team)}</option>`).join('');$('nav').innerHTML=NAV.map(([k,l])=>`<button data-view="${k}">${l}</button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('leagueSelect').onchange=()=>openLeague(Number($('leagueSelect').value));$('sideAddBtn').onclick=showAddForm;$('topTitle').textContent=`${C.league.name} — ${C.my_team.team} [${C.platform}]`;$('topRecord').textContent=`${C.my_team.record.wins}-${C.my_team.record.losses}`;$('topWaiver').textContent=C.my_team.waiver_position!=null?`#${C.my_team.waiver_position}`:'—';$('topWeek').textContent=C.current_week;$('topTeams').textContent=C.league_teams.length}
async function loadAnalysis(){const body=JSON.stringify({context:C});analysis=await get('/api/rankings',{method:'POST',headers:{'Content-Type':'application/json'},body});if(String(C?.platform||'').toUpperCase()==='ESPN'&&analysis?.source_policy){analysis.source_policy.version=String(analysis.source_policy.version||'4.0-canonical')+':espn-verified-waivers-v2'}await Promise.allSettled([loadMatchup(),loadPublic()])}
async function loadMatchup(){matchupData=await get('/api/matchup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({context:C,analysis})}).catch(e=>({available:false,message:e.message}))}
function showView(v){currentView=v;$('nav').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));({dashboard:renderDashboard,intel:renderIntel,matchup:renderMatchup,power:renderPower,waivers:renderWaivers,trades:renderTrades,guru:renderGuru}[v]||renderDashboard)()}
async function loadPublic(){try{const [s,n]=await Promise.all([fetch('https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard').then(r=>r.json()),fetch('https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?limit=8').then(r=>r.json())]);nflGames=s.events||[];nflNews=n.articles||[]}catch{}if(currentView==='dashboard')renderDashboard()}
function fmtGame(e){const c=e.competitions?.[0],a=c?.competitors||[],away=a.find(x=>x.homeAway==='away'),home=a.find(x=>x.homeAway==='home'),dt=e.date?new Date(e.date):null;return{away:away?.team?.abbreviation||'Away',home:home?.team?.abbreviation||'Home',date:dt?dt.toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'}):'',status:c?.status?.type?.shortDetail||''}}
function renderDashboard(){const ls=leagues(),fav=localStorage.getItem('fg-favorite-team')||'IND',facts=TEAM_FACTS[fav]||[],favGames=nflGames.filter(e=>{const g=fmtGame(e);return g.away===fav||g.home===fav}).slice(0,2);$('content').innerHTML=`<h2>🏈 Fantasy Guru</h2><div class="sub">Your fantasy football command center.</div><div class="dashboardGrid"><div class="card dashLeague"><h3>🏆 League Hub</h3><div class="leagueTiles">${ls.map((x,i)=>`<button class="miniLeague ${String(x.id)===String(C.league.id)?'current':''}" data-i="${i}"><b>${esc(x.name)}</b><div class="leagueMeta">${esc(x.team)} · ${x.platform}</div></button>`).join('')}</div></div><div class="card dashFav"><h3>⭐ Favorite NFL Team</h3><select id="favTeam">${Object.keys(TEAM_FACTS).map(t=>`<option ${t===fav?'selected':''}>${t}</option>`).join('')}</select><div style="margin-top:7px">${favGames.length?favGames.map(e=>{const g=fmtGame(e);return `<div class="row"><b>${g.away} @ ${g.home}</b><div class="muted">${g.date} · ${g.status}</div></div>`}).join(''):'<div class="muted">No game in the current scoreboard window.</div>'}</div>${facts.map(f=>`<div class="fact">💡 ${esc(f)}</div>`).join('')}</div><div class="card dashSchedule"><h3>📅 NFL Schedule</h3>${nflGames.slice(0,7).map(e=>{const g=fmtGame(e);return `<div class="row"><b>${g.away} @ ${g.home}</b><div class="muted">${g.date} · ${g.status}</div></div>`}).join('')||'<div class="muted">Loading schedule…</div>'}</div><div class="card dashNews"><h3>📰 NFL & Fantasy Watch</h3>${nflNews.slice(0,6).map(a=>`<div class="row"><a class="headline" target="_blank" rel="noopener" href="${a.links?.web?.href||'#'}">${esc(a.headline)}</a><div class="muted">${esc((a.description||'').slice(0,120))}</div></div>`).join('')||'<div class="muted">Loading headlines…</div>'}</div><div class="card dashAsk"><h3>🧠 Quick Ask Guru</h3><div class="quickAsk"><input id="quickQ" placeholder="Ask about this league, lineup, waivers or trades…"><button id="quickBtn">Ask</button></div><div id="quickAns" class="answer hidden"></div></div></div>`;$('content').querySelectorAll('.miniLeague').forEach(b=>b.onclick=()=>openLeague(Number(b.dataset.i)));$('favTeam').onchange=()=>{localStorage.setItem('fg-favorite-team',$('favTeam').value);renderDashboard()};$('quickBtn').onclick=()=>askGuru($('quickQ').value,$('quickAns'))}
function ranks(field){const out={QB:{},RB:{},WR:{},TE:{}};for(const p of Object.keys(out)){const k=field+'_'+p.toLowerCase(),rows=(analysis?.team_details||[]).filter(t=>finite(t[k])).sort((a,b)=>Number(b[k])-Number(a[k]));rows.forEach((t,i)=>out[p][String(t.roster_id)]=i+1)}return out}
function needProfile(team){const n=analysis?.team_details?.length||10,wr=ranks('weekly'),rr=ranks('ros');return['QB','RB','WR','TE'].map(p=>{const id=String(team.roster_id),w=wr[p][id]||n,r=rr[p][id]||n,score=((w-1)/Math.max(1,n-1)*.25)+((r-1)/Math.max(1,n-1)*.75);return{position:p,weekly_rank:w,ros_rank:r,need_score:+score.toFixed(3)}}).sort((a,b)=>b.need_score-a.need_score)}
function eligible(p,s){if(s===p)return true;if(s==='FLEX')return['RB','WR','TE'].includes(p);if(s==='SUPER_FLEX')return['QB','RB','WR','TE'].includes(p);return false}
function optimize(players,field){const used=new Set(),slots=(C?.league?.roster_positions||[]).filter(s=>!['BN','IR'].includes(s)),order=[...slots].sort((a,b)=>({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[a]||9)-({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[b]||9));let total=0;for(const s of order){let best=-1,bv=-Infinity;players.forEach((p,i)=>{if(used.has(i)||!eligible(pos(p.position),s)||!finite(p[field]))return;const v=Number(p[field]);if(v>bv){bv=v;best=i}});if(best>=0){used.add(best);total+=Number(players[best][field])}}return total}
const ident=p=>String(p?.canonical_player_id||p?.sleeper_id||p?.espn_id||p?.gsis_id||p?.id||p?.name||''), sum=(a,f)=>a.reduce((n,p)=>n+(finite(p[f])?Number(p[f]):0),0), src=p=>Math.max(Number(p?.ros_source_count||0),Number(p?.weekly_source_count||0)), bye=p=>finite(p?.bye_week??p?.bye??p?.byeWeek)?Number(p?.bye_week??p?.bye??p?.byeWeek):null;
function mineTeam(){return(analysis?.team_details||[]).find(t=>String(t.roster_id)===String(C?.my_team?.roster_id)||t.team===C?.my_team?.team)}
function owned(){const s=new Set();for(const t of analysis?.team_details||[])for(const p of t.players||[])s.add(ident(p));return s}
function espnAvailableKeys(){const s=new Set();for(const p of C?.available_trending_players||[]){if(p?.espn_id)s.add('e:'+String(p.espn_id));if(p?.id)s.add('e:'+String(p.id));if(p?.sleeper_id)s.add('s:'+String(p.sleeper_id));if(p?.canonical_player_id)s.add('c:'+String(p.canonical_player_id));s.add('n:'+String(p?.name||'').toLowerCase().replace(/[^a-z0-9]/g,'')+'|'+pos(p?.position))}return s}
function espnIsAvailable(p,keys){if(p?.espn_id&&keys.has('e:'+String(p.espn_id)))return true;if(p?.sleeper_id&&keys.has('s:'+String(p.sleeper_id)))return true;if(p?.canonical_player_id&&keys.has('c:'+String(p.canonical_player_id)))return true;return keys.has('n:'+String(p?.name||'').toLowerCase().replace(/[^a-z0-9]/g,'')+'|'+pos(p?.position))}
function waiverPool(){const o=owned(),pool=(analysis?.waiver_pool||[]).filter(p=>!o.has(ident(p))&&(finite(p.ros_points)||finite(p.weekly_points)));if(String(C?.platform||'').toUpperCase()!=='ESPN')return pool;const keys=espnAvailableKeys();return pool.filter(p=>espnIsAvailable(p,keys))}
function impact(r){return{w:optimize(r,'weekly_points'),r:optimize(r,'ros_points'),v:sum(r,'ros_points')}}
function needScore(pr,p){return pr.find(x=>x.position===pos(p))?.need_score||0}
function claimConfidence(){const p=Number(C?.my_team?.waiver_position),n=C?.league_teams?.length||10;if(!Number.isFinite(p)||p<=0)return'Waiver priority unknown';if(p<=Math.ceil(n*.3))return`Waiver #${p} · high claim confidence`;if(p<=Math.ceil(n*.65))return`Waiver #${p} · medium claim confidence`;return`Waiver #${p} · low claim confidence`}
function bestWaiver(r,pr,exclude=new Set()){const b=impact(r);let best=null;for(const a of waiverPool().slice(0,120)){if(exclude.has(ident(a)))continue;const n=impact([...r,a]),wg=n.w-b.w,rg=n.r-b.r,sc=rg*3+wg+needScore(pr,a.position)*3;if(src(a)===1&&rg<1.5&&wg<2)continue;if(!best||sc>best.sc)best={p:a,wg,rg,sc}}return best}
function normalizeRoster(r,base,pr,exclude=new Set()){r=[...r];let add=null,drop=null;while(r.length>base.length){let best=null;for(const p of r){const a=r.filter(x=>ident(x)!==ident(p)),i=impact(a),sc=i.r*3+i.w;if(!best||sc>best.sc)best={a,p,sc}}r=best.a;drop=best.p}while(r.length<base.length){const b=bestWaiver(r,pr,exclude);if(!b)break;r.push(b.p);exclude.add(ident(b.p));add=b.p}return{r,add,drop}}
function waiverIdeas(){const m=mineTeam();if(!m)return[];const base=m.players||[],bi=impact(base),pr=needProfile(m),out=[];for(const a of waiverPool().slice(0,120))for(const d of base){if(finite(a.ros_points)&&finite(d.ros_points)&&Number(a.ros_points)<Number(d.ros_points))continue;const r=base.filter(p=>ident(p)!==ident(d)).concat(a),i=impact(r),wg=i.w-bi.w,rg=i.r-bi.r,rv=i.v-bi.v;if(wg<-1||((rg<.5)&&(wg<1.5))||(src(a)===1&&rg<1.5&&wg<2.5))continue;const bw=bye(a),over=bw==null?0:base.filter(p=>pos(p.position)===pos(a.position)&&bye(p)===bw).length,score=rg*4+wg+Math.max(0,rv)*.2+needScore(pr,a.position)*4-over;out.push({add:a,drop:d,wg,rg,rv,before:bi,after:i,over,score})}out.sort((a,b)=>b.score-a.score);const seen=new Set();return out.filter(x=>{const k=ident(x.add);if(seen.has(k))return false;seen.add(k);return true}).slice(0,6)}
