const ROSTER_INTEL_CACHE_TTL=6*60*60*1000;
function intelRosterFingerprint(team){return (team?.players||[]).map(p=>String(p?.id||p?.espn_id||p?.sleeper_id||p?.name||'')+':'+String(p?.name||'')).sort().join('|')}
function intelCacheKey(team){return `fg-roster-intel:v1:${C?.platform||''}:${C?.league?.id||''}:${team?.roster_id||''}:${intelRosterFingerprint(team)}`}
function readIntelCache(team){try{const x=JSON.parse(localStorage.getItem(intelCacheKey(team))||'null');if(!x?.data||Date.now()-Number(x.ts||0)>ROSTER_INTEL_CACHE_TTL)return null;return x}catch{return null}}
function writeIntelCache(team,data){try{localStorage.setItem(intelCacheKey(team),JSON.stringify({ts:Date.now(),data}))}catch{}return data}
function intelAge(ts){const m=Math.max(0,Math.floor((Date.now()-Number(ts||0))/60000));if(m<1)return'just now';if(m<60)return`${m} min ago`;const h=Math.floor(m/60);return h===1?'1 hr ago':`${h} hrs ago`}
async function renderIntel(force=false){
  const team=C.league_teams.find(t=>String(t.roster_id)===String(selectedIntel))||C.league_teams[0];
  const cached=!force?readIntelCache(team):null;
  $('content').innerHTML=`<h2>🩺 Roster Intel</h2><div class="sub">Current fantasy context for every player. Injury status comes live from ${esc(C.platform)}; researched news/outlook is cached for 6 hours unless the roster changes.</div><div style="display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap"><div class="teamTabs" style="margin-bottom:8px">${C.league_teams.map(t=>`<button data-id="${t.roster_id}" class="${String(t.roster_id)===String(team.roster_id)?'active':''}">${esc(t.team)}${String(t.roster_id)===String(C.my_team.roster_id)?' · YOU':''}</button>`).join('')}</div><button class="btn secondary" id="intelRefresh">↻ Refresh Intel</button></div><div id="intelCacheStatus" class="muted" style="font-size:10px;margin:0 0 8px">${cached?`Using cached research · ${intelAge(cached.ts)}`:'Fresh research needed'}</div><div id="intelData" class="card"><div class="loading">${cached?'Loading cached roster intel…':'Researching current roster intel…'}</div></div>`;
  $('content').querySelectorAll('.teamTabs button').forEach(b=>b.onclick=()=>{selectedIntel=String(b.dataset.id);renderIntel(false)});
  $('intelRefresh').onclick=()=>renderIntel(true);
  try{
    const ctx={...C,my_team:{...C.my_team,team:team.team,roster_id:team.roster_id,players:team.players}};
    let d=cached?.data;
    if(!d){d=await get('/api/roster-intel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({context:ctx})});writeIntelCache(team,d)}
    const status=$('intelCacheStatus');if(status)status.textContent=cached&&!force?`Using cached research · ${intelAge(cached.ts)} · injury/status remains live`:`Research refreshed just now · cached for 6 hours`;
    const td=(analysis?.team_details||[]).find(x=>String(x.roster_id)===String(team.roster_id)||x.team===team.team),map=new Map((td?.players||[]).map(p=>[String(p.name).toLowerCase(),p])),intelMap=new Map((d.players||[]).map(x=>[String(x.name).toLowerCase(),x])),slots=(C?.league?.roster_positions||[]).filter(s=>!['BN','IR'].includes(s)),slotRank=s=>{const i=slots.indexOf(s);return i<0?99:i},rows=(team.players||[]).map(r=>{const key=String(r.name).toLowerCase(),x=intelMap.get(key)||{name:r.name,position:r.position,intel_type:'CURRENT OUTLOOK',intel:'Reliable current role context was not found.',intel_date:d.generated_at?.slice(0,10)},p=map.get(key);return{x,p,r}}).sort((a,b)=>{const as=a.r?.starter?0:1,bs=b.r?.starter?0:1;if(as!==bs)return as-bs;const ar=slotRank(a.r?.lineup_slot),br=slotRank(b.r?.lineup_slot);if(ar!==br)return ar-br;return String(a.x?.position||'').localeCompare(String(b.x?.position||''))||String(a.x?.name||'').localeCompare(String(b.x?.name||''))});
    const makeRows=list=>list.map(({x,p,r})=>{const wk=finite(p?.weekly_points)?Number(p.weekly_points).toFixed(1):'—',ros=finite(p?.ros_points)?Number(p.ros_points).toFixed(1):'—',slot=r?.starter?(r.lineup_slot||x.position||'START'):'BN',kind=x.intel_type||'CURRENT OUTLOOK',date=fmtIntelDate(x.intel_date||d.generated_at?.slice(0,10)),liveStatus=r?.injury_status||x.injury_status||'ACTIVE',teamAbbr=r?.team||p?.team||'';return `<div class="intelRow"><div style="display:grid;grid-template-columns:48px minmax(0,1fr) 64px 64px;gap:6px;align-items:center"><span>${esc(slot)}</span><span><b>${esc(x.name)}</b><div class="muted">${esc(x.position||r?.position||'')}${teamAbbr?' · '+esc(teamAbbr):''} · ${esc(liveStatus)}</div></span><span class="right"><b>${wk}</b><div class="muted" style="font-size:8px">WEEKLY</div></span><span class="right"><b>${ros}</b><div class="muted" style="font-size:8px">ROS</div></span></div><div style="margin:6px 0 0 54px"><span class="pill" style="font-size:8px">${esc(kind)}</span> <span class="muted">${esc(x.intel||x.news||'No reliable current context found.')}${date?' · '+esc(date):''}</span></div></div>`}).join('');
    const starters=rows.filter(z=>z.r?.starter),bench=rows.filter(z=>!z.r?.starter);
    $('intelData').innerHTML=`<div style="display:grid;grid-template-columns:48px minmax(0,1fr) 64px 64px;gap:6px;padding:0 0 6px;border-bottom:1px solid #26364f"><b style="grid-column:1/3">${esc(team.team)}</b><span class="muted right" style="font-size:9px">WEEKLY</span><span class="muted right" style="font-size:9px">ROS</span></div><div class="benchTitle">STARTERS</div>${makeRows(starters)}<div class="benchTitle">BENCH</div>${makeRows(bench)}`;
  }catch(e){$('intelData').innerHTML=`<div class="error">Roster intel unavailable: ${esc(e.message)}</div>`}
}
