/* Player Hub: combines waiver discovery + trade discovery with cached league player market. */
(function(){
  const HUB_TTL=15*60*1000;
  let hubTab='recommended',hubQuery='',hubPos='ALL';

  function hubKey(){return `fg-player-hub:v1:${C?.platform||''}:${C?.league?.id||''}:${C?.current_week||''}:${C?.my_team?.roster_id||''}`}
  function hubRead(){try{const x=JSON.parse(localStorage.getItem(hubKey())||'null');if(!x?.data||Date.now()-Number(x.ts||0)>HUB_TTL)return null;return x}catch{return null}}
  function hubWrite(data){try{localStorage.setItem(hubKey(),JSON.stringify({ts:Date.now(),data}))}catch{}return data}
  function hubAge(ts){const m=Math.max(0,Math.floor((Date.now()-Number(ts||0))/60000));return m<1?'just now':m===1?'1 min ago':`${m} min ago`}
  function ownerMap(){const m=new Map();for(const t of analysis?.team_details||[])for(const p of t.players||[])m.set(ident(p),t.team);return m}
  function trendMap(){const m=new Map();for(const p of C?.available_trending_players||[])m.set(String(p.id||p.canonical_player_id||p.sleeper_id||p.espn_id||p.name),Number(p.trending_adds||p.count||0));return m}
  function marketRows(){
    const cached=hubRead();if(cached?.data)return cached.data;
    const own=ownerMap(),trend=trendMap(),seen=new Set(),rows=[];
    const add=(p,available=false)=>{if(!p)return;const id=ident(p);if(!id||seen.has(id))return;seen.add(id);const owner=own.get(id)||null,tv=typeof tradeValue==='function'?tradeValue(p):{score:0,label:''};const t=Number(p.trending_adds||trend.get(String(p.id||p.canonical_player_id||p.sleeper_id||p.espn_id||p.name))||0);rows.push({id,name:p.name||'Unknown',position:pos(p.position),team:p.team||'',week:finite(p.weekly_points)?Number(p.weekly_points):null,ros:finite(p.ros_points)?Number(p.ros_points):null,tradeScore:Number(tv?.score||0),tradeLabel:tv?.label||'',owner,available:available||!owner,trend:t,signal:String(p.opportunity_signal||p.signal||p.market_signal||'').replace(/_/g,' '),marketTrend:finite(p.market_trend_30d??p.market_trend)?Number(p.market_trend_30d??p.market_trend):null})};
    for(const p of analysis?.waiver_pool||[])add(p,true);
    for(const t of analysis?.team_details||[])for(const p of t.players||[])add(p,false);
    rows.sort((a,b)=>(b.tradeScore||0)-(a.tradeScore||0)||(b.ros??-Infinity)-(a.ros??-Infinity));return hubWrite(rows)
  }
  function fitText(r){const need=mineTeam()?needScore(needProfile(mineTeam()),r.position):0;if(r.available&&need>=.65)return `Available · fits a major ${r.position} need`;if(r.available)return 'Available · compare against your weakest roster spot';if(r.owner===C?.my_team?.team)return 'On your roster';if(need>=.65)return `Trade target · fills a ${r.position} need`;return 'Rostered · evaluate only if price is realistic'}
  function rowHTML(r){const trend=r.trend?`+${Math.round(r.trend)} adds`:r.marketTrend!=null?`${r.marketTrend>=0?'+':''}${r.marketTrend} 30d`:'—';return `<div class="fg17Row"><div class="fg17Player"><b>${esc(r.name)}</b><span>${esc(r.position)}${r.team?' · '+esc(r.team):''}</span></div><div><b>${r.week==null?'—':r.week.toFixed(1)}</b><span>WEEK</span></div><div><b>${r.ros==null?'—':r.ros.toFixed(1)}</b><span>ROS</span></div><div><b>${esc(trend)}</b><span>TREND</span></div><div class="fg17Owner"><b>${r.available?'AVAILABLE':esc(r.owner||'ROSTERED')}</b><span>${esc(fitText(r))}</span></div></div>`}
  function filteredRows(kind){let rows=marketRows();if(kind==='available')rows=rows.filter(r=>r.available);if(kind==='all')rows=[...rows];if(kind==='trending')rows=rows.filter(r=>r.trend>0||r.marketTrend!=null).sort((a,b)=>(b.trend||Math.abs(b.marketTrend||0))-(a.trend||Math.abs(a.marketTrend||0)));if(hubPos!=='ALL')rows=rows.filter(r=>r.position===hubPos);if(hubQuery){const q=hubQuery.toLowerCase();rows=rows.filter(r=>`${r.name} ${r.team} ${r.position} ${r.owner||''}`.toLowerCase().includes(q))}return rows.slice(0,100)}
  function browseHTML(kind){const rows=filteredRows(kind);return `<div class="fg17Tools"><input id="fg17Search" value="${esc(hubQuery)}" placeholder="Search players, team, owner…"><select id="fg17Pos"><option>ALL</option>${['QB','RB','WR','TE','K','DEF'].map(p=>`<option ${hubPos===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="fg17TableHead"><span>PLAYER</span><span>WEEK</span><span>ROS</span><span>TREND</span><span>STATUS / FIT</span></div><div class="fg17Rows">${rows.length?rows.map(rowHTML).join(''):'<div class="muted" style="padding:14px">No players match these filters.</div>'}</div>`}
  function recommendationsHTML(){const w=typeof storedWaiverIdeas==='function'?storedWaiverIdeas():[],t=typeof tradeIdeas==='function'?tradeIdeas():[],wr=typeof waiverRadar==='function'?waiverRadar():[],tr=typeof tradeRadar==='function'?tradeRadar():[],pr=mineTeam()?needProfile(mineTeam()):[];return `<div class="fg17RecGrid"><section class="fg17Card"><div class="fg17CardHead"><h3>📋 Best Adds</h3><button data-hub-tab="available">Browse Available</button></div>${w.length?w.slice(0,4).map((x,i)=>waiverMoveHTML(x,i,pr)).join(''):wr.length?wr.slice(0,4).map((x,i)=>waiverMoveHTML(x,i,pr,'wr')).join(''):'<div class="hold">HOLD</div><div class="muted">No add clearly improves the roster right now.</div>'}</section><section class="fg17Card"><div class="fg17CardHead"><h3>🤝 Best Trade Paths</h3><button data-hub-tab="trade">Trade Targets</button></div>${t.length?t.slice(0,4).map((x,i)=>tradeMoveHTML(x,i,'tr')).join(''):tr.length?tr.slice(0,4).map((x,i)=>tradeMoveHTML(x,i,'rr')).join(''):'<div class="hold">HOLD</div><div class="muted">No realistic trade clears the current thresholds.</div>'}</section></div>`}
  function tradeHTML(){const ideas=typeof tradeIdeas==='function'?tradeIdeas():[],radar=typeof tradeRadar==='function'?tradeRadar():[],strict=new Set(ideas.flatMap(x=>(x.get||[]).map(ident))),show=(radar.filter(x=>!strict.has(ident(x.get?.[0]))).length?radar.filter(x=>!strict.has(ident(x.get?.[0]))):radar).slice(0,8);return `<div class="fg17RecGrid"><section class="fg17Card"><h3>Recommended Trades</h3>${ideas.length?ideas.slice(0,6).map((x,i)=>tradeMoveHTML(x,i,'tr')).join(''):'<div class="hold">HOLD</div><div class="muted">No trade clears every fairness and roster-impact check.</div>'}</section><section class="fg17Card"><h3>Trade Target Radar</h3>${show.length?show.map((x,i)=>tradeMoveHTML(x,i,'rr')).join(''):'<div class="muted">No sufficiently plausible trade targets found.</div>'}</section></div>`}
  function renderBody(){const box=$('fg17Body');if(!box)return;if(hubTab==='recommended')box.innerHTML=recommendationsHTML();else if(hubTab==='trade')box.innerHTML=tradeHTML();else box.innerHTML=browseHTML(hubTab);wireBody()}
  function wireBody(){document.querySelectorAll('[data-hub-tab]').forEach(b=>b.onclick=()=>{hubTab=b.dataset.hubTab;syncTabs();renderBody()});const s=$('fg17Search');if(s)s.oninput=()=>{hubQuery=s.value;renderBody()};const p=$('fg17Pos');if(p)p.onchange=()=>{hubPos=p.value;renderBody()}}
  function syncTabs(){document.querySelectorAll('.fg17Tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===hubTab))}
  function renderHub(){const c=hubRead(),age=c?`Cached ${hubAge(c.ts)}`:'Player market cache created now';marketRows();$('content').innerHTML=`<div class="fg17Head"><div><h2>🔎 Player Hub</h2><span>Discover players, waiver adds, trends and realistic trade targets in one place.</span></div><div class="fg17Cache">${esc(age)} · market cache 15 min</div></div><div class="fg17Tabs"><button class="fg17Tab" data-tab="recommended">Recommended</button><button class="fg17Tab" data-tab="available">Available</button><button class="fg17Tab" data-tab="all">All Players</button><button class="fg17Tab" data-tab="trending">Trending</button><button class="fg17Tab" data-tab="trade">Trade Targets</button></div><div id="fg17Body"></div>`;document.querySelectorAll('.fg17Tab').forEach(b=>b.onclick=()=>{hubTab=b.dataset.tab;syncTabs();renderBody()});syncTabs();renderBody()}

  const oldWaivers=renderWaivers,oldTrades=renderTrades;
  window.fg17OpenHub=function(tab='recommended'){hubTab=tab;showView('playerhub')};

  const iIntel=NAV.findIndex(x=>x[0]==='intel');if(iIntel>=0)NAV.splice(iIntel,1);
  const iW=NAV.findIndex(x=>x[0]==='waivers');if(iW>=0)NAV.splice(iW,1);
  const iT=NAV.findIndex(x=>x[0]==='trades');if(iT>=0)NAV.splice(iT,1);
  const insert=Math.min(3,NAV.length);NAV.splice(insert,0,['playerhub','🔎 Player Hub']);

  const baseShow=showView;showView=function(v){if(v==='waivers'){hubTab='available';v='playerhub'}else if(v==='trades'){hubTab='trade';v='playerhub'}else if(v==='intel'){v='matchup'};if(v==='playerhub'){currentView=v;$('nav')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderHub();return}return baseShow(v)};

  const baseDashboard=renderDashboard;renderDashboard=function(){baseDashboard();document.querySelectorAll('[data-fg6-view="waivers"],[data-fg-view="waivers"]').forEach(b=>{b.dataset.fg6View='playerhub';b.dataset.fgView='playerhub';if(/waiver/i.test(b.textContent))b.textContent='Open Player Hub →'});document.querySelectorAll('[data-fg6-view="trades"],[data-fg-view="trades"]').forEach(b=>{b.dataset.fg6View='playerhub';b.dataset.fgView='playerhub';if(/trade/i.test(b.textContent))b.textContent='Open Player Hub →'});document.querySelectorAll('[data-fg6-view="intel"],[data-fg-view="intel"]').forEach(b=>{b.dataset.fg6View='matchup';b.dataset.fgView='matchup';b.textContent='View Matchup Intel →'});if(typeof fg6Wire==='function')fg6Wire();if(typeof fgWireViewButtons==='function')fgWireViewButtons()};

  const style=document.createElement('style');style.textContent=`
    .fg17Head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.fg17Head h2{margin:0 0 3px}.fg17Head span{color:#8fa6bf;font-size:11px}.fg17Cache{font-size:9px;color:#86efac;border:1px solid #285845;background:#0c211c;border-radius:999px;padding:5px 8px;white-space:nowrap}.fg17Tabs{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:9px}.fg17Tab,.fg17CardHead button{border:1px solid #2d5e86;background:#0a1a2a;color:#c9ecff;border-radius:8px;padding:7px 10px;font-size:10px;font-weight:850;cursor:pointer}.fg17Tab.active{background:#1597d1;color:#041b2a;border-color:#1597d1}.fg17RecGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;align-items:start}.fg17Card{background:#081524;border:1px solid #28405d;border-radius:11px;padding:10px;min-width:0}.fg17Card h3{margin:0 0 8px}.fg17CardHead{display:flex;justify-content:space-between;align-items:center;gap:8px}.fg17Tools{display:grid;grid-template-columns:minmax(0,1fr) 110px;gap:7px;margin-bottom:7px}.fg17Tools input,.fg17Tools select{width:100%;background:#07111e;color:#e8f2ff;border:1px solid #28405d;border-radius:8px;padding:8px}.fg17TableHead,.fg17Row{display:grid;grid-template-columns:minmax(190px,1.4fr) 70px 70px 90px minmax(220px,1.3fr);gap:7px;align-items:center}.fg17TableHead{padding:6px 9px;background:#0b1b2d;color:#8fa6bf;font-size:8px;font-weight:900;border:1px solid #28405d;border-radius:8px 8px 0 0}.fg17Rows{border:1px solid #28405d;border-top:0;border-radius:0 0 8px 8px;overflow:hidden}.fg17Row{padding:8px 9px;border-top:1px solid #1b3047}.fg17Row:first-child{border-top:0}.fg17Row>div:not(.fg17Player):not(.fg17Owner){text-align:center}.fg17Row b{display:block;font-size:11px}.fg17Row span{display:block;color:#8fa6bf;font-size:8px;margin-top:2px}.fg17Player b{font-size:12px}.fg17Owner b{color:#7dd3fc}.fg17Owner span{font-size:9px;line-height:1.3}
    @media(max-width:900px){.fg17RecGrid{grid-template-columns:1fr}.fg17TableHead{display:none}.fg17Rows{border-top:1px solid #28405d;border-radius:8px}.fg17Row{grid-template-columns:minmax(0,1fr) repeat(3,54px);grid-template-rows:auto auto;gap:5px}.fg17Player{grid-column:1}.fg17Owner{grid-column:1/-1;grid-row:2;padding-top:4px}.fg17Tools{grid-template-columns:minmax(0,1fr) 85px}}
    @media(max-width:700px){.fg17Head{display:block;margin-left:50px}.fg17Cache{display:inline-block;margin-top:6px}.fg17Tabs{display:grid;grid-template-columns:repeat(2,1fr)}.fg17Tab:first-child{grid-column:1/-1}.fg17Row{grid-template-columns:minmax(0,1fr) repeat(3,48px);padding:9px 8px}.fg17Row b{font-size:10px}.fg17Player b{font-size:12px}.fg17Card{padding:8px}}
  `;document.head.appendChild(style);
})();
