/* Clean UI compatibility layer. Presentation only; decision engines remain unchanged. */
function leaguePlatformUrl(l){
  if(!l)return null;
  const platform=String(l.platform||'').toUpperCase(),id=encodeURIComponent(String(l.id||'')),rid=encodeURIComponent(String(l.rid||l.roster_id||''));
  if(platform==='SLEEPER'&&id)return `https://sleeper.com/leagues/${id}/team`;
  if(platform==='ESPN'&&id)return `https://fantasy.espn.com/football/team?leagueId=${id}${rid?`&teamId=${rid}`:''}`;
  return null;
}
function externalLeagueLink(l,compact=false){const u=leaguePlatformUrl(l);return u?`<a href="${u}" target="_blank" rel="noopener noreferrer" class="fg7LeagueLink${compact?' compact':''}">Open in ${esc(l.platform)} ↗</a>`:''}

function ssEligible(p,s){const q=pos(p?.position);if(s===q)return true;if(s==='FLEX')return['RB','WR','TE'].includes(q);if(s==='SUPER_FLEX')return['QB','RB','WR','TE'].includes(q);return false}
function ssOptimized(){
  const m=mineTeam(),players=m?.players||[],slots=(C?.league?.roster_positions||[]).filter(s=>!['BN','IR'].includes(s));
  const order=[...slots].map((slot,i)=>({slot,i})).sort((a,b)=>({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[a.slot]||9)-({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[b.slot]||9));
  const used=new Set(),picks=[];
  for(const x of order){let bi=-1,bv=-Infinity;players.forEach((p,i)=>{if(used.has(i)||!ssEligible(p,x.slot)||!finite(p.weekly_points))return;const v=Number(p.weekly_points);if(v>bv){bv=v;bi=i}});if(bi>=0){used.add(bi);picks.push({slot:x.slot,player:players[bi],value:bv})}}
  return picks;
}
function ssDecisions(){
  const m=mineTeam();if(!m)return{picks:[],changes:[],close:[]};
  const picks=ssOptimized(),optIds=new Set(picks.map(x=>ident(x.player))),current=(m.players||[]).filter(p=>p.starter),curIds=new Set(current.map(ident));
  const incoming=picks.filter(x=>!curIds.has(ident(x.player))),outgoing=current.filter(p=>!optIds.has(ident(p))),usedOut=new Set(),changes=[];
  for(const x of incoming){let cand=null;for(const p of outgoing){if(usedOut.has(ident(p))||!ssEligible(p,x.slot)||!finite(p.weekly_points))continue;if(!cand||Number(p.weekly_points)<Number(cand.weekly_points))cand=p}if(!cand)continue;usedOut.add(ident(cand));const diff=Number(x.player.weekly_points)-Number(cand.weekly_points);changes.push({start:x.player,sit:cand,slot:x.slot,diff,confidence:diff>=5?'HIGH':diff>=2.5?'GOOD':diff>=1?'MEDIUM':'TOSS-UP'})}
  const bench=(m.players||[]).filter(p=>!optIds.has(ident(p))&&finite(p.weekly_points)),close=[];
  for(const x of picks)for(const b of bench){if(!ssEligible(b,x.slot))continue;const diff=Number(x.player.weekly_points)-Number(b.weekly_points);if(diff>=0&&diff<=5)close.push({start:x.player,sit:b,slot:x.slot,diff,confidence:diff>=2.5?'GOOD':diff>=1?'MEDIUM':'TOSS-UP'})}
  close.sort((a,b)=>a.diff-b.diff);const seen=new Set(),unique=[];for(const x of close){const k=ident(x.start)+'|'+ident(x.sit);if(seen.has(k))continue;seen.add(k);unique.push(x);if(unique.length>=6)break}
  return{picks,changes,close:unique};
}
function renderStartSit(){
  const d=ssDecisions(),m=mineTeam();if(!m){$('content').innerHTML='<h2>✅ Start / Sit</h2><div class="card muted">Roster data unavailable.</div>';return}
  const currentIds=new Set((m.players||[]).filter(p=>p.starter).map(ident));
  const changes=d.changes.length?d.changes.map((x,i)=>`<div class="fg7SSRow"><span class="fg7SSNum">${i+1}</span><div><b class="gain">START ${esc(x.start.name)}</b> over <b class="loss">${esc(x.sit.name)}</b><div class="muted">${esc(x.slot)} · ${Number(x.start.weekly_points).toFixed(1)} vs ${Number(x.sit.weekly_points).toFixed(1)} · +${x.diff.toFixed(1)}</div></div><span class="grade">${x.confidence}</span></div>`).join(''):'<div class="fg7Good">✅ Your current starters already match Fantasy Guru’s highest-projected lineup.</div>';
  const close=d.close.length?d.close.map(x=>`<div class="fg7Close"><b>${esc(x.start.name)}</b> over ${esc(x.sit.name)} <span class="grade">${x.confidence}</span><div class="muted">${Number(x.start.weekly_points).toFixed(1)} vs ${Number(x.sit.weekly_points).toFixed(1)} · ${x.diff.toFixed(1)} point edge</div></div>`).join(''):'<div class="muted">No especially close start/sit calls.</div>';
  const lineup=d.picks.map(x=>`<div class="fg7Line"><b>${esc(x.slot)}</b><span>${esc(x.player.name)} <small>${esc(pos(x.player.position))}${x.player.team?' · '+esc(x.player.team):''}</small>${currentIds.has(ident(x.player))?'':' <span class="pill">MOVE IN</span>'}</span><strong>${Number(x.player.weekly_points).toFixed(1)}</strong></div>`).join('');
  $('content').innerHTML=`<h2>✅ Start / Sit</h2><div class="sub">Week ${C.current_week} · optimized from the same trusted weekly projection engine used everywhere else.</div><div class="fg7SSGrid"><div class="card"><h3>Guru Lineup Check</h3>${changes}</div><div class="card"><h3>Closest Decisions</h3>${close}</div></div><div class="card" style="margin-top:9px"><h3>Highest-Projected Starting Lineup</h3>${lineup}</div>`;
}

let fg7GuruHistory=[];
function fg7GuruKey(){return `fg-guru-drawer:v2:${C?.platform||''}:${C?.league?.id||''}:${C?.my_team?.roster_id||''}`}
function fg7LoadGuru(){try{fg7GuruHistory=JSON.parse(localStorage.getItem(fg7GuruKey())||'[]');if(!Array.isArray(fg7GuruHistory))fg7GuruHistory=[]}catch{fg7GuruHistory=[]}}
function fg7SaveGuru(){try{localStorage.setItem(fg7GuruKey(),JSON.stringify(fg7GuruHistory.slice(-12)))}catch{}}
function fg7RenderGuru(){const log=$('fg7GuruLog');if(!log)return;log.innerHTML=fg7GuruHistory.length?fg7GuruHistory.map(x=>`<div class="fg7Msg ${x.role==='user'?'user':'guru'}"><small>${x.role==='user'?'YOU':'🧠 GURU'}</small><div>${esc(x.content).replace(/\n/g,'<br>')}</div>${x.follow_up?`<button class="fg7Follow" data-q="${esc(x.follow_up)}">${esc(x.follow_up)}</button>`:''}</div>`).join(''):'<div class="fg7Welcome"><b>Ask me about this league.</b><div class="muted">Lineup, matchup, waivers, trades, roster value—whatever you’re looking at.</div></div>';log.querySelectorAll('.fg7Follow').forEach(b=>b.onclick=()=>{$('fg7GuruInput').value=b.dataset.q||'';$('fg7GuruInput').focus()});log.scrollTop=log.scrollHeight}
async function fg7SendGuru(){const input=$('fg7GuruInput'),q=input?.value.trim();if(!q||!C||!analysis)return;input.value='';fg7GuruHistory.push({role:'user',content:q});fg7SaveGuru();fg7RenderGuru();$('fg7GuruSend').disabled=true;$('fg7Thinking').classList.remove('hidden');try{const enriched={...analysis,screen_context:{screen:currentView,week:C.current_week,league:C.league?.name,team:C.my_team?.team}},d=await get('/api/guru',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context:C,analysis:enriched,history:fg7GuruHistory.slice(-8)})});fg7GuruHistory.push({role:'assistant',content:d.answer||'No answer returned.',follow_up:d.follow_up_question||''});fg7SaveGuru();fg7RenderGuru()}catch(e){fg7GuruHistory.push({role:'assistant',content:'Guru could not answer: '+(e.message||'Unknown error')});fg7RenderGuru()}finally{$('fg7GuruSend').disabled=false;$('fg7Thinking').classList.add('hidden')}}
function fg7EnsureGuru(){if($('fg7Guru'))return;const el=document.createElement('aside');el.id='fg7Guru';el.innerHTML=`<div class="fg7GuruHead"><div><b>🧠 Guru</b><small>● Online</small></div><button id="fg7GuruNew">+ New Chat</button></div><div id="fg7GuruContext" class="fg7GuruContext">League context</div><div id="fg7GuruLog" class="fg7GuruLog"></div><div class="fg7Compose"><textarea id="fg7GuruInput" placeholder="Ask Guru about this league..."></textarea><div><span id="fg7Thinking" class="muted hidden">Guru is thinking…</span><button id="fg7GuruSend">Send</button></div></div>`;document.body.appendChild(el);$('fg7GuruSend').onclick=fg7SendGuru;$('fg7GuruNew').onclick=()=>{fg7GuruHistory=[];try{localStorage.removeItem(fg7GuruKey())}catch{}fg7RenderGuru()};$('fg7GuruInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();fg7SendGuru()}})}

(function(){
  if(!NAV.some(x=>x[0]==='startsit'))NAV.splice(1,0,['startsit','✅ Start / Sit']);
  const gi=NAV.findIndex(x=>x[0]==='guru');if(gi>=0)NAV.splice(gi,1);
  const style=document.createElement('style');style.textContent=`
    .fg7LeagueLink{color:#4cc9ff;text-decoration:none;font-size:10px;font-weight:800;margin-left:8px}.fg7LeagueLink:hover{text-decoration:underline}
    .fg7SSGrid{display:grid;grid-template-columns:1.1fr .9fr;gap:9px}.fg7SSRow{display:grid;grid-template-columns:28px 1fr auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #26364f}.fg7SSNum{width:24px;height:24px;border-radius:50%;background:#10263b;color:#7dd3fc;display:grid;place-items:center;font-weight:900}.fg7Good{padding:10px;border:1px solid #285845;background:#0c211c;border-radius:8px;color:#86efac}.fg7Close{padding:7px 0;border-bottom:1px solid #26364f}.fg7Line{display:grid;grid-template-columns:75px 1fr 55px;gap:8px;align-items:center;padding:6px 0;border-bottom:1px solid #1e2f46}.fg7Line>b{color:#7dd3fc}.fg7Line small{color:#94a3b8}.fg7Line strong{text-align:right}
    #fg7Guru{position:fixed;right:10px;top:70px;bottom:10px;width:350px;z-index:55;background:#071524;border:1px solid #28405d;border-radius:12px;display:flex;flex-direction:column;overflow:hidden}.fg7GuruHead{padding:11px 12px;border-bottom:1px solid #28405d}.fg7GuruHead>div{display:flex;align-items:center;justify-content:space-between;gap:8px}.fg7GuruHead b{font-size:17px}.fg7GuruHead small{color:#86efac}.fg7GuruHead button{margin-top:8px;border:1px solid #2d5e86;background:#0a1a2a;color:#c9ecff;border-radius:7px;padding:5px 8px}.fg7GuruContext{padding:6px 12px;color:#8fa5bd;font-size:10px;border-bottom:1px solid #1e324a}.fg7GuruLog{flex:1;overflow:auto;padding:9px}.fg7Msg{padding:9px;border-radius:10px;margin-bottom:8px;line-height:1.4;font-size:11px}.fg7Msg.user{background:#0c56a6;margin-left:35px}.fg7Msg.guru{background:#0d2034;border:1px solid #213a55;margin-right:10px}.fg7Msg small{display:block;color:#9ddcff;font-size:8px;font-weight:900;margin-bottom:4px}.fg7Follow{display:block;margin-top:7px;text-align:left;border:1px solid #31506d;background:#0b1828;color:#9bdcff;border-radius:7px;padding:6px;cursor:pointer}.fg7Welcome{padding:12px;border:1px dashed #29425e;border-radius:9px}.fg7Compose{padding:8px;border-top:1px solid #28405d}.fg7Compose textarea{min-height:58px;resize:vertical}.fg7Compose>div{display:flex;align-items:center;justify-content:space-between;margin-top:6px}.fg7Compose button{border:0;background:#22c55e;color:#052e16;border-radius:7px;padding:7px 12px;font-weight:900}.main{padding-right:382px!important}
    @media(max-width:1100px){.main{padding-right:16px!important}#fg7Guru{position:fixed;transform:translateX(110%)}.fg7SSGrid{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  fg7EnsureGuru();
  const brokenShell=renderShell;renderShell=function(idx){try{brokenShell(idx)}catch(e){if(!String(e?.message||e).includes('loadGuruDrawerHistory'))throw e}const l=leagues()[idx]||{platform:C?.platform,id:C?.league?.id,rid:C?.my_team?.roster_id};$('topTitle').innerHTML=`${esc(C.league.name)} — ${esc(C.my_team.team)} [${esc(C.platform)}] ${externalLeagueLink(l,true)}`;fg7LoadGuru();fg7RenderGuru();const c=$('fg7GuruContext');if(c)c.textContent=`${String(currentView||'dashboard').replace(/^./,x=>x.toUpperCase())} · ${C.league.name}`};
  const baseShow=showView;showView=function(v){if(v==='startsit'){currentView=v;$('nav')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderStartSit()}else baseShow(v);const c=$('fg7GuruContext');if(c)c.textContent=`${String(v||'dashboard').replace(/^./,x=>x.toUpperCase())} · ${C?.league?.name||''}`};
})();