// Evaluation Lab — simple answer first, engineering detail on demand.
(function(){
  if(!Array.isArray(NAV)||NAV.some(x=>x[0]==='evalLab'))return;
  NAV.push(['evalLab','🧪 Evaluation Lab']);
  const oldShowView=showView;
  showView=function(v){if(v!=='evalLab')return oldShowView(v);currentView=v;$('nav').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderEvaluationLab()};

  const num=v=>finite(v)?Number(v):null;
  const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
  const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)};
  const confidence=p=>{const vals=[p.espn_weekly_points,p.sleeper_weekly_points,p.ffanalytics_weekly_points].filter(finite).map(Number);if(!vals.length)return{score:0,label:'LOW',sources:0};const m=mean(vals),cv=Math.abs(m)>.01?sd(vals)/Math.abs(m):1,source=vals.length===3?1:vals.length===2?.78:.48,agree=Math.max(0,Math.min(1,1-cv)),score=Math.round((source*.65+agree*.35)*100);return{score,label:score>=80?'HIGH':score>=60?'MEDIUM':'LOW',sources:vals.length}};
  function allPlayers(){const out=[],seen=new Set();for(const t of analysis?.team_details||[])for(const p of t.players||[]){const k=ident(p);if(!seen.has(k)){seen.add(k);out.push(p)}}return out}
  function actualRows(players){return players.filter(p=>finite(p.actual_weekly_points)&&finite(p.weekly_points)).map(p=>({p,actual:Number(p.actual_weekly_points),sources:{ESPN:num(p.espn_weekly_points),Sleeper:num(p.sleeper_weekly_points),ffanalytics:num(p.ffanalytics_weekly_points)}}))}
  function mae(rows,getter){const a=[];for(const r of rows){const v=getter(r);if(finite(v))a.push(Math.abs(Number(v)-r.actual))}return a.length?{n:a.length,v:mean(a)}:{n:0,v:null}}
  function fmt(x){return finite(x)?Number(x).toFixed(2):'—'}
  function sampleMessage(n,target=25){return n<target?`Too early to judge. Guru has graded ${n} player${n===1?'':'s'} so far; we want at least ${target} before trusting accuracy results.`:`Guru has graded ${n} players, so the accuracy results are becoming useful.`}
  function ledgerStatus(l){if(!l)return'Guru has not started a prediction record yet.';if(l.status==='LOCKED'||l.status==='CAPTURED')return`This week's predictions were saved before the games so Guru can grade itself fairly afterward.`;if(l.status==='GRADED')return`Guru has graded this week's saved predictions against what actually happened.`;if(l.status==='MISSED_PREGAME')return`Guru skipped grading this week because games had already started before a clean prediction snapshot was saved.`;if(l.status==='ERROR')return`Prediction tracking hit an error: ${l.error||'unknown error'}`;return l.reason||l.note||`Prediction tracking status: ${l.status||'unknown'}`}

  function rookieCheck(players){
    const rookies=players.filter(p=>p?.rookie===true||p?.is_rookie===true||Number(p?.years_exp)===0||Number(p?.experience)===0);
    if(!rookies.length)return{status:'WATCH',title:'Rookie Value Check',text:'Guru can value rookies from projections and market value before they have NFL stats, but the current player feed does not reliably label rookies yet, so Guru cannot separately audit them as a group.'};
    const valued=rookies.filter(p=>finite(p.trade_value)),market=rookies.filter(p=>finite(p.market_value));
    return{status:valued.length===rookies.length?'GOOD':'WATCH',title:'Rookie Value Check',text:`Guru identified ${rookies.length} rookies. ${valued.length} have a Trade Value and ${market.length} have a FantasyCalc market value. Rookies without enough forward-looking evidence stay unscored rather than getting a guessed value.`};
  }

  function marketCheck(){
    const m=analysis?.market||{},coverage=Number(m.coverage_pct||0),matched=Number(m.matched_players||0),total=Number(m.total_players_enriched||0);
    if(m.available===false)return{title:'Market Data Check',text:'FantasyCalc market data is unavailable right now, so Guru is using conservative fallback values instead of guessing what the market thinks.'};
    if(total)return{title:'Market Data Check',text:`Guru has FantasyCalc market values for ${coverage}% of the players it is checking (${matched} of ${total}). Missing market values use a conservative fallback instead of making the other inputs count more.`};
    return{title:'Market Data Check',text:'Guru is checking FantasyCalc for outside market value. There is not enough market-match information loaded yet to grade the coverage.'};
  }

  function simpleHealth(players,rows){
    const a=analysis?.trade_value_audit||{},m=analysis?.market||{},tv=String(a.status||'UNKNOWN');
    if(tv==='CAUTION')return{tone:'watch',label:'NEEDS WATCHING',title:'Guru may be counting the same information twice.',text:'Replacement value and starter value are currently very similar. Guru noticed it and is watching it, but it has not automatically changed player scores.'};
    if(m?.available===false)return{tone:'problem',label:'PROBLEM',title:'Guru is missing an important market-data source.',text:'FantasyCalc market data is unavailable right now, so Trade Value is relying more heavily on projections and conservative fallback values.'};
    if(rows.length<25)return{tone:'good',label:'LOOKS GOOD SO FAR',title:'Guru is running normally, but it is still early to judge accuracy.',text:'The model checks are running and no major failure is showing. There just are not enough completed-game results yet to know how accurate Guru is over time.'};
    return{tone:'good',label:'LOOKS GOOD',title:'Guru’s model checks are healthy.',text:'The main data sources are working and Guru has enough graded results to start judging how accurate its predictions are.'};
  }

  function advancedTV(){
    const a=analysis?.trade_value_audit||{},m=analysis?.market||{},c=a.correlations||{},f=a.missing_component_fallbacks||{},mm=m?.match_methods||{};
    return`<div class="card"><h3>Trade Value Model Audit</h3><div class="muted">Technical check: are several TV ingredients accidentally measuring the same thing?</div><div class="dashboardGrid" style="margin-top:10px"><div class="card"><div class="muted">Projection-linked weight</div><h3>${Number(a.projection_linked_weight_pct||0)}%</h3></div><div class="card"><div class="muted">Highest correlation</div><h3>${fmt(c.max_absolute)}</h3><div class="muted">${esc(c.strongest_pair||'—')}</div></div><div class="card"><div class="muted">Average correlation</div><h3>${fmt(c.average_absolute)}</h3></div><div class="card"><div class="muted">Fallback values used</div><h3>${Number(f.market||0)+Number(f.week_outlook||0)}</h3></div></div><div class="row"><b>ROS ↔ VORP</b><div class="muted">${fmt(c.ros_vs_vorp)}</div></div><div class="row"><b>ROS ↔ Starter Impact</b><div class="muted">${fmt(c.ros_vs_starter_impact)}</div></div><div class="row"><b>VORP ↔ Starter Impact</b><div class="muted">${fmt(c.vorp_vs_starter_impact)}</div></div><div class="card" style="margin-top:10px"><h3>FantasyCalc Market Matching</h3><div class="muted">${Number(m?.coverage_pct||0)}% coverage · ${Number(m?.matched_players||0)} matched of ${Number(m?.total_players_enriched||0)} players · ${Number(m?.rows_received||0)} market rows received</div><div class="row"><b>Sleeper ID matches</b><div class="muted">${Number(mm.sleeper_id||0)}</div></div><div class="row"><b>ESPN ID matches</b><div class="muted">${Number(mm.espn_id||0)}</div></div><div class="row"><b>Name + position matches</b><div class="muted">${Number(mm.name_position||0)}</div></div><div class="row"><b>Name-only matches</b><div class="muted">${Number(mm.name_only||0)}</div></div><div class="row"><b>Unmatched players</b><div class="muted">${Number(mm.unmatched||0)}</div></div></div></div>`;
  }

  function renderEvaluationLab(){
    const players=allPlayers(),rows=actualRows(players),guru=mae(rows,r=>r.p.weekly_points),espn=mae(rows,r=>r.sources.ESPN),sleeper=mae(rows,r=>r.sources.Sleeper),ffa=mae(rows,r=>r.sources.ffanalytics),conf=players.map(confidence).filter(x=>x.sources),avgConf=conf.length?mean(conf.map(x=>x.score)):null,health=simpleHealth(players,rows),rookie=rookieCheck(players),market=marketCheck(),ledger=analysis?.evaluation_ledger||null,hist=ledger?.history&&!ledger.history.error?ledger.history:null;
    const byPos=['QB','RB','WR','TE'].map(position=>{const x=rows.filter(r=>pos(r.p.position)===position),g=mae(x,r=>r.p.weekly_points);return{position,n:g.n,mae:g.v}});
    $('content').innerHTML=`<div class="fgEvalSimple"><h2>🧪 Evaluation Lab</h2><div class="sub">This is Guru checking its own work. You do not need to understand the math to use Fantasy Guru.</div>
      <section class="fgEvalHealth ${health.tone}"><span class="fgEvalBadge">${esc(health.label)}</span><h3>${esc(health.title)}</h3><p>${esc(health.text)}</p></section>
      <div class="fgEvalCards" style="margin-top:12px"><div class="card"><h3>Accuracy Check</h3><p>${esc(sampleMessage(rows.length))}</p><div class="muted">Projection confidence right now: ${fmt(avgConf)} / 100 across ${conf.length} players.</div></div><div class="card"><h3>${esc(rookie.title)}</h3><p>${esc(rookie.text)}</p></div><div class="card"><h3>${esc(market.title)}</h3><p>${esc(market.text)}</p></div></div>
      <div class="card" style="margin-top:12px"><h3>What Guru is checking</h3><div class="row"><b>Are the projections dependable?</b><div class="muted">Guru compares ESPN, Sleeper and ffanalytics instead of trusting one source.</div></div><div class="row"><b>Is Trade Value double-counting the same idea?</b><div class="muted">Guru checks whether ROS, replacement value and starter value are becoming too similar.</div></div><div class="row"><b>Is market data actually available?</b><div class="muted">Guru checks FantasyCalc so player value is not based only on projections.</div></div><div class="row"><b>Does Guru learn from misses?</b><div class="muted">Predictions are saved before games, then compared with what actually happened.</div></div></div>
      <details class="fgEvalAdvanced" style="margin-top:12px"><summary>Advanced Diagnostics — show me the nerd stuff</summary><div style="margin-top:10px">${advancedTV()}<div class="card" style="margin-top:10px"><h3>Prediction Tracking</h3><p>${esc(ledgerStatus(ledger))}</p>${hist?`<div class="muted">Graded weeks: ${hist.graded_snapshots||0} · player grades: ${hist.players_graded||0}</div>`:''}</div><div class="dashboardGrid" style="margin-top:10px">${[['Guru consensus',guru],['ESPN',espn],['Sleeper',sleeper],['ffanalytics',ffa]].map(([name,x])=>`<div class="card"><div class="muted">${esc(name)} error</div><h3>${fmt(x.v)}</h3><div class="muted">${x.n} graded · lower is better</div></div>`).join('')}</div><div class="card" style="margin-top:10px"><h3>Accuracy by position</h3>${byPos.map(x=>`<div class="row"><b>${x.position}</b><div class="muted">Error ${fmt(x.mae)} · ${x.n} graded</div></div>`).join('')}</div></div></details></div>`;
  }
  window.renderEvaluationLab=renderEvaluationLab;
  const style=document.createElement('style');style.textContent=`.fgEvalHealth{margin-top:14px;border:1px solid #2b4966;border-radius:12px;padding:14px;background:#081524}.fgEvalHealth.good{border-color:#1f7a5b}.fgEvalHealth.watch{border-color:#a87b0a}.fgEvalHealth.problem{border-color:#a53645}.fgEvalBadge{display:inline-block;border-radius:999px;padding:4px 8px;font-size:9px;font-weight:900;background:#17324a;color:#dcecff}.fgEvalHealth.good .fgEvalBadge{background:#0f4a38;color:#9df5ca}.fgEvalHealth.watch .fgEvalBadge{background:#3a2f0a;color:#fde68a}.fgEvalHealth.problem .fgEvalBadge{background:#451922;color:#fecdd3}.fgEvalHealth h3{margin:8px 0 5px;font-size:18px}.fgEvalHealth p,.fgEvalSimple .card p{color:#c8d6e5;line-height:1.45}.fgEvalCards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.fgEvalCards>.card{min-width:0}.fgEvalAdvanced>summary{cursor:pointer;font-weight:900;color:#7dd3fc;background:#081524;border:1px solid #28405d;border-radius:10px;padding:11px;list-style:none}.fgEvalAdvanced>summary::-webkit-details-marker{display:none}.fgEvalAdvanced>summary:after{content:'  ▾'}.fgEvalAdvanced[open]>summary:after{content:'  ▴'}@media(max-width:1000px){.fgEvalCards{grid-template-columns:1fr}}`;document.head.appendChild(style);
})();