/* Player Hub: waiver discovery + player market + trade discovery with cached league data. */
(function(){
  const HUB_TTL=15*60*1000;
  let hubTab='waivers',hubQuery='',hubPos='ALL',selectedPlayerId=null;

  function hubKey(){return `fg-player-hub:v2:${C?.platform||''}:${C?.league?.id||''}:${C?.current_week||''}:${C?.my_team?.roster_id||''}`}
  function hubRead(){try{const x=JSON.parse(localStorage.getItem(hubKey())||'null');if(!x?.data||Date.now()-Number(x.ts||0)>HUB_TTL)return null;return x}catch{return null}}
  function hubWrite(data){try{localStorage.setItem(hubKey(),JSON.stringify({ts:Date.now(),data}))}catch{}return data}
  function hubAge(ts){const m=Math.max(0,Math.floor((Date.now()-Number(ts||0))/60000));return m<1?'just now':m===1?'1 min ago':`${m} min ago`}
  function ownerMap(){const m=new Map();for(const t of analysis?.team_details||[])for(const p of t.players||[])m.set(ident(p),t.team);return m}
  function contextPlayerMap(){const m=new Map();for(const t of C?.league_teams||[])for(const p of t.players||[])m.set(ident(p),{...p,owner:t.team});for(const p of C?.available_trending_players||[])if(!m.has(ident(p)))m.set(ident(p),p);return m}
  function trendMap(){const m=new Map();for(const p of C?.available_trending_players||[])m.set(String(p.id||p.canonical_player_id||p.sleeper_id||p.espn_id||p.name),Number(p.trending_adds||p.count||0));return m}
  function liveActualMap(){const m=new Map(),add=x=>{if(!x?.name||!finite(x.actual_points))return;m.set(String(x.name).toLowerCase()+'|'+pos(x.position),Number(x.actual_points))};for(const x of matchupData?.you?.lineup||[])add(x);for(const x of matchupData?.you?.bench||[])add(x);for(const x of matchupData?.them?.lineup||[])add(x);for(const x of matchupData?.them?.bench||[])add(x);return m}
  function actualFor(p,ctx,live){const key=String(p?.name||'').toLowerCase()+'|'+pos(p?.position);if(live.has(key))return live.get(key);for(const v of [ctx?.actual_weekly_points,p?.actual_weekly_points,p?.actual_points])if(finite(v))return Number(v);return null}
  function rawPlayer(id){for(const p of analysis?.waiver_pool||[])if(ident(p)===id)return p;for(const t of analysis?.team_details||[])for(const p of t.players||[])if(ident(p)===id)return p;return null}
  function contextPlayer(id){for(const t of C?.league_teams||[])for(const p of t.players||[])if(ident(p)===id)return{...p,owner:t.team};for(const p of C?.available_trending_players||[])if(ident(p)===id)return p;return null}
  function marketRows(){
    const cached=hubRead();if(cached?.data)return cached.data;
    const own=ownerMap(),ctxMap=contextPlayerMap(),trend=trendMap(),live=liveActualMap(),seen=new Set(),rows=[];
    const add=(p,available=false)=>{if(!p)return;const id=ident(p);if(!id||seen.has(id))return;seen.add(id);const owner=own.get(id)||null,ctx=ctxMap.get(id)||null,tv=typeof tradeValue==='function'?tradeValue(p):{score:0,label:''};const t=Number(p.trending_adds||trend.get(String(p.id||p.canonical_player_id||p.sleeper_id||p.espn_id||p.name))||0);rows.push({id,name:p.name||'Unknown',position:pos(p.position),team:p.team||ctx?.team||'',week:finite(p.weekly_points)?Number(p.weekly_points):null,actual:actualFor(p,ctx,live),ros:finite(p.ros_points)?Number(p.ros_points):null,tradeScore:Number(tv?.score||0),tradeLabel:tv?.label||'',owner,available:available||!owner,adds7d:t,signal:String(p.opportunity_signal||p.signal||p.market_signal||'').replace(/_/g,' '),marketTrend:finite(p.market_trend_30d??p.market_trend)?Number(p.market_trend_30d??p.market_trend):null})};
    for(const p of analysis?.waiver_pool||[])add(p,true);
    for(const t of analysis?.team_details||[])for(const p of t.players||[])add(p,false);
    rows.sort((a,b)=>(b.tradeScore||0)-(a.tradeScore||0)||(b.ros??-Infinity)-(a.ros??-Infinity));return hubWrite(rows)
  }
  function fitText(r){const need=mineTeam()?needScore(needProfile(mineTeam()),r.position):0;if(r.available&&need>=.65)return `Available · fits a major ${r.position} need`;if(r.available)return 'Available · compare against your weakest roster spot';if(r.owner===C?.my_team?.team)return 'On your roster';if(need>=.65)return `Trade target · fills a ${r.position} need`;return 'Rostered · evaluate only if price is realistic'}
  function compact(n){n=Number(n||0);if(Math.abs(n)>=1e6)return(Number(n/1e6).toFixed(n>=1e7?0:1).replace('.0',''))+'M';if(Math.abs(n)>=1e3)return(Number(n/1e3).toFixed(n>=1e4?0:1).replace('.0',''))+'K';return String(Math.round(n))}
  function activityText(r){if(r.adds7d>0)return `${compact(r.adds7d)} adds / 7d`;if(r.marketTrend!=null)return `${r.marketTrend>=0?'+':''}${Number(r.marketTrend).toFixed(1)} value / 30d`;return '—'}
  function rowHTML(r){return `<div class="fg17Row"><div class="fg17Player"><button class="fg17PlayerLink" data-player-id="${esc(r.id)}">${esc(r.name)}</button><span>${esc(r.position)}${r.team?' · '+esc(r.team):''}</span></div><div><b>${r.actual==null?'—':r.actual.toFixed(1)}</b><span>ACTUAL</span></div><div><b>${r.week==null?'—':r.week.toFixed(1)}</b><span>WEEK PROJ</span></div><div><b>${r.ros==null?'—':r.ros.toFixed(1)}</b><span>ROS</span></div><div><b>${esc(activityText(r))}</b><span>MARKET ACTIVITY</span></div><div class="fg17Owner"><b>${r.available?'AVAILABLE':esc(r.owner||'ROSTERED')}</b><span>${esc(fitText(r))}</span></div></div>`}
  function filteredRows(kind){let rows=marketRows();if(kind==='available')rows=rows.filter(r=>r.available);if(kind==='all')rows=[...rows];if(kind==='activity')rows=rows.filter(r=>r.adds7d>0||r.marketTrend!=null).sort((a,b)=>(b.adds7d||Math.abs(b.marketTrend||0))-(a.adds7d||Math.abs(a.marketTrend||0)));if(hubPos!=='ALL')rows=rows.filter(r=>r.position===hubPos);if(hubQuery){const q=hubQuery.toLowerCase();rows=rows.filter(r=>`${r.name} ${r.team} ${r.position} ${r.owner||''}`.toLowerCase().includes(q))}return rows.slice(0,100)}
  function browseHTML(kind){const rows=filteredRows(kind);return `<div class="fg17Tools"><input id="fg17Search" value="${esc(hubQuery)}" placeholder="Search players, team, owner…"><select id="fg17Pos"><option>ALL</option>${['QB','RB','WR','TE','K','DEF'].map(p=>`<option ${hubPos===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="fg17TableHead"><span>PLAYER</span><span>ACTUAL</span><span>WEEK PROJ</span><span>ROS</span><span>MARKET ACTIVITY</span><span>STATUS / FIT</span></div><div class="fg17Rows">${rows.length?rows.map(rowHTML).join(''):'<div class="muted" style="padding:14px">No players match these filters.</div>'}</div>`}
  function waiversHTML(){const w=typeof storedWaiverIdeas==='function'?storedWaiverIdeas():[],wr=typeof waiverRadar==='function'?waiverRadar():[],pr=mineTeam()?needProfile(mineTeam()):[],strictIds=new Set(w.map(x=>ident(x.add))),watch=wr.filter(x=>!strictIds.has(ident(x.add))).slice(0,6);return `<div class="fg17RecGrid"><section class="fg17Card"><div class="fg17CardHead"><h3>📋 Recommended Waiver Adds</h3><button data-hub-tab="available">Browse Available</button></div>${w.length?w.slice(0,6).map((x,i)=>waiverMoveHTML(x,i,pr)).join(''):'<div class="hold">HOLD</div><div class="muted">No waiver move clearly improves your roster right now.</div>'}</section><section class="fg17Card"><h3>🔭 Watchlist</h3>${(watch.length?watch:wr).slice(0,6).map((x,i)=>waiverMoveHTML(x,i,pr,'wr')).join('')||'<div class="muted">No verified waiver candidates are available.</div>'}</section></div>`}
  function tradeHTML(){const ideas=typeof tradeIdeas==='function'?tradeIdeas():[],radar=typeof tradeRadar==='function'?tradeRadar():[],strict=new Set(ideas.flatMap(x=>(x.get||[]).map(ident))),show=(radar.filter(x=>!strict.has(ident(x.get?.[0]))).length?radar.filter(x=>!strict.has(ident(x.get?.[0]))):radar).slice(0,8);return `<div class="fg17RecGrid"><section class="fg17Card"><h3>Recommended Trades</h3>${ideas.length?ideas.slice(0,6).map((x,i)=>tradeMoveHTML(x,i,'tr')).join(''):'<div class="hold">HOLD</div><div class="muted">No trade clears every fairness and roster-impact check.</div>'}</section><section class="fg17Card"><h3>Trade Target Radar</h3>${show.length?show.map((x,i)=>tradeMoveHTML(x,i,'rr')).join(''):'<div class="muted">No sufficiently plausible trade targets found.</div>'}</section></div>`}
  function selectOptions(players,selected){return players.map(p=>`<option value="${esc(ident(p))}" ${ident(p)===selected?'selected':''}>${esc(p.name)} · ${esc(pos(p.position))}</option>`).join('')}
  function compareCalc(dropId,addId){const m=mineTeam(),base=m?.players||[],drop=base.find(p=>ident(p)===dropId),add=waiverPool().find(p=>ident(p)===addId);if(!m||!drop||!add)return null;const before=impact(base),afterRoster=base.filter(p=>ident(p)!==dropId).concat(add),after=impact(afterRoster),pr=needProfile(m),rg=after.r-before.r,wg=after.w-before.w,rv=after.v-before.v,bw=bye(add),over=bw==null?0:afterRoster.filter(p=>ident(p)!==addId&&pos(p.position)===pos(add.position)&&bye(p)===bw).length,confidence=Math.max(src(add),0);let verdict='HOLD';if(rg>0.5||wg>1.5)verdict='UPGRADE';else if(rg>=0&&wg>=0)verdict='SLIGHT UPGRADE';else if(rg<-1||wg<-2)verdict='DOWNGRADE';return{drop,add,before,after,rg,wg,rv,need:needScore(pr,add.position),over,confidence,verdict}}
  function compareResultHTML(x){if(!x)return '<div class="fg17CompareEmpty">Choose one player from your roster and one available player.</div>';const cls=x.verdict.includes('UPGRADE')?'good':x.verdict==='DOWNGRADE'?'bad':'';return `<div class="fg17CompareResult"><div class="fg17CompareVerdict ${cls}">${esc(x.verdict)}</div><div class="fg17CompareMove"><span>DROP <b>${esc(x.drop.name)}</b></span><span>ADD <b>${esc(x.add.name)}</b></span></div><div class="fg17CompareMetrics"><div><span>Weekly lineup</span><b class="${x.wg>=0?'good':'bad'}">${x.wg>=0?'+':''}${x.wg.toFixed(1)}</b></div><div><span>ROS lineup</span><b class="${x.rg>=0?'good':'bad'}">${x.rg>=0?'+':''}${x.rg.toFixed(1)}</b></div><div><span>Total ROS value</span><b class="${x.rv>=0?'good':'bad'}">${x.rv>=0?'+':''}${x.rv.toFixed(1)}</b></div><div><span>Position need</span><b>${Math.round(x.need*100)}%</b></div><div><span>Projection sources</span><b>${x.confidence||0}/3</b></div><div><span>Bye overlap</span><b>${x.over}</b></div></div><div class="fg17CompareNote">This comparison re-optimizes your starting lineup after the add/drop. It does not force a move when the difference is marginal.</div></div>`}
  function compareHTML(){const mine=(mineTeam()?.players||[]).filter(p=>!['K','DEF'].includes(pos(p.position))),avail=waiverPool().filter(p=>!['K','DEF'].includes(pos(p.position))).slice(0,120),drop=mine[0]?ident(mine[0]):'',add=avail[0]?ident(avail[0]):'';return `<div class="fg17Compare"><div class="fg17ComparePick"><label>DROP FROM MY ROSTER<select id="fg17Drop">${selectOptions(mine,drop)}</select></label><div class="fg17Swap">⇄</div><label>ADD AVAILABLE PLAYER<select id="fg17Add">${selectOptions(avail,add)}</select></label></div><div id="fg17CompareResult">${compareResultHTML(compareCalc(drop,add))}</div></div>`}
  function playerSources(raw){const a=[];for(const s of raw?.weekly_sources||[])if(s&&!a.includes(String(s)))a.push(String(s));for(const s of raw?.ros_sources||[])if(s&&!a.includes(String(s)))a.push(String(s));return a}
  function drawerHTML(id){const r=marketRows().find(x=>x.id===id),raw=rawPlayer(id)||{},ctx=contextPlayer(id)||{},sources=playerSources(raw),inj=ctx.injury_status||raw.injury_status||'Active/No flag';if(!r)return'';const mv=finite(raw.market_value)?Number(raw.market_value):null,mt=finite(raw.market_trend_30d??raw.market_trend)?Number(raw.market_trend_30d??raw.market_trend):null;return `<div class="fg17DrawerBackdrop" data-close-player></div><aside class="fg17Drawer"><div class="fg17DrawerHead"><div><h3>${esc(r.name)}</h3><span>${esc(r.position)}${r.team?' · '+esc(r.team):''}</span></div><button data-close-player>×</button></div><div class="fg17DrawerGrid"><div><span>Actual Week ${esc(C.current_week)}</span><b>${r.actual==null?'—':r.actual.toFixed(1)}</b></div><div><span>Week Projection</span><b>${r.week==null?'—':r.week.toFixed(1)}</b></div><div><span>ROS Projection</span><b>${r.ros==null?'—':r.ros.toFixed(1)}</b></div><div><span>Guru Value</span><b>${r.tradeScore||'—'}</b></div></div><section><h4>League Status</h4><p>${r.available?'Available':`Owned by ${esc(r.owner||'another team')}`} · ${esc(inj)}</p></section><section><h4>Projection Sources</h4><p>${sources.length?esc(sources.join(' · ')):'Source names not exposed for this player.'}</p><p class="muted">Weekly source count: ${Number(raw.weekly_source_count||0)} · ROS source count: ${Number(raw.ros_source_count||0)}</p></section><section><h4>Market</h4><p>${r.adds7d>0?`${compact(r.adds7d)} Sleeper adds over 7 days`:mt!=null?`${mt>=0?'+':''}${mt.toFixed(1)} 30-day market movement`:'No verified market movement available.'}${mv!=null?` · FantasyCalc value ${mv}`:''}</p></section><section><h4>Identifiers / Data Coverage</h4><p>${raw.sleeper_id||ctx.sleeper_id?'Sleeper ✓':'Sleeper —'} · ${raw.espn_id||ctx.espn_id?'ESPN ✓':'ESPN —'} · ${raw.gsis_id||ctx.gsis_id?'GSIS ✓':'GSIS —'}</p></section><section><h4>Guru Fit</h4><p>${esc(fitText(r))}</p></section></aside>`}
  function openDrawer(id){selectedPlayerId=id;document.querySelector('.fg17DrawerWrap')?.remove();const w=document.createElement('div');w.className='fg17DrawerWrap';w.innerHTML=drawerHTML(id);document.body.appendChild(w);w.querySelectorAll('[data-close-player]').forEach(b=>b.onclick=()=>{w.remove();selectedPlayerId=null})}
  function renderBody(){const box=$('fg17Body');if(!box)return;if(hubTab==='waivers')box.innerHTML=waiversHTML();else if(hubTab==='trade')box.innerHTML=tradeHTML();else if(hubTab==='compare')box.innerHTML=compareHTML();else box.innerHTML=browseHTML(hubTab);wireBody()}
  function wireBody(){document.querySelectorAll('[data-hub-tab]').forEach(b=>b.onclick=()=>{hubTab=b.dataset.hubTab;syncTabs();renderBody()});document.querySelectorAll('.fg17PlayerLink').forEach(b=>b.onclick=()=>openDrawer(b.dataset.playerId));const s=$('fg17Search');if(s)s.oninput=()=>{hubQuery=s.value;renderBody()};const p=$('fg17Pos');if(p)p.onchange=()=>{hubPos=p.value;renderBody()};const d=$('fg17Drop'),a=$('fg17Add');const rerun=()=>{const out=$('fg17CompareResult');if(out)out.innerHTML=compareResultHTML(compareCalc(d?.value,a?.value))};if(d)d.onchange=rerun;if(a)a.onchange=rerun}
  function syncTabs(){document.querySelectorAll('.fg17Tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===hubTab))}
  function renderHub(){const c=hubRead(),age=c?`Cached ${hubAge(c.ts)}`:'Player market cache created now';marketRows();$('content').innerHTML=`<div class="fg17Head"><div><h2>🔎 Player Hub</h2><span>Waiver adds, player research, market activity, comparisons and realistic trade targets.</span></div><div class="fg17Cache">${esc(age)} · market cache 15 min</div></div><div class="fg17Tabs"><button class="fg17Tab" data-tab="waivers">Waiver Adds</button><button class="fg17Tab" data-tab="available">Available</button><button class="fg17Tab" data-tab="all">All Players</button><button class="fg17Tab" data-tab="activity">Market Activity</button><button class="fg17Tab" data-tab="compare">Compare Players</button><button class="fg17Tab" data-tab="trade">Trade Targets</button></div><div id="fg17Body"></div>`;document.querySelectorAll('.fg17Tab').forEach(b=>b.onclick=()=>{hubTab=b.dataset.tab;syncTabs();renderBody()});syncTabs();renderBody()}

  window.fg17OpenHub=function(tab='waivers'){hubTab=tab;showView('playerhub')};
  const iIntel=NAV.findIndex(x=>x[0]==='intel');if(iIntel>=0)NAV.splice(iIntel,1);const iW=NAV.findIndex(x=>x[0]==='waivers');if(iW>=0)NAV.splice(iW,1);const iT=NAV.findIndex(x=>x[0]==='trades');if(iT>=0)NAV.splice(iT,1);if(!NAV.some(x=>x[0]==='playerhub'))NAV.splice(Math.min(3,NAV.length),0,['playerhub','🔎 Player Hub']);

  const baseShow=showView;showView=function(v){if(v==='waivers'){hubTab='waivers';v='playerhub'}else if(v==='trades'){hubTab='trade';v='playerhub'}else if(v==='intel'){v='matchup'};if(v==='playerhub'){currentView=v;$('nav')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderHub();return}return baseShow(v)};
  const baseDashboard=renderDashboard;renderDashboard=function(){baseDashboard();document.querySelectorAll('[data-fg6-view="waivers"],[data-fg-view="waivers"]').forEach(b=>{b.dataset.fg6View='playerhub';b.dataset.fgView='playerhub';if(/waiver/i.test(b.textContent))b.textContent='Open Player Hub →'});document.querySelectorAll('[data-fg6-view="trades"],[data-fg-view="trades"]').forEach(b=>{b.dataset.fg6View='playerhub';b.dataset.fgView='playerhub';if(/trade/i.test(b.textContent))b.textContent='Open Player Hub →'});document.querySelectorAll('[data-fg6-view="intel"],[data-fg-view="intel"]').forEach(b=>{b.dataset.fg6View='matchup';b.dataset.fgView='matchup';b.textContent='View Matchup Intel →'});if(typeof fg6Wire==='function')fg6Wire();if(typeof fgWireViewButtons==='function')fgWireViewButtons()};

  const style=document.createElement('style');style.textContent=`
    .fg17Head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.fg17Head h2{margin:0 0 3px}.fg17Head span{color:#8fa6bf;font-size:11px}.fg17Cache{font-size:9px;color:#86efac;border:1px solid #285845;background:#0c211c;border-radius:999px;padding:5px 8px;white-space:nowrap}.fg17Tabs{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:9px}.fg17Tab,.fg17CardHead button{border:1px solid #2d5e86;background:#0a1a2a;color:#c9ecff;border-radius:8px;padding:7px 10px;font-size:10px;font-weight:850;cursor:pointer}.fg17Tab.active{background:#1597d1;color:#041b2a;border-color:#1597d1}.fg17RecGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;align-items:start}.fg17Card{background:#081524;border:1px solid #28405d;border-radius:11px;padding:10px;min-width:0}.fg17Card h3{margin:0 0 8px}.fg17CardHead{display:flex;justify-content:space-between;align-items:center;gap:8px}.fg17Tools{display:grid;grid-template-columns:minmax(0,1fr) 110px;gap:7px;margin-bottom:7px}.fg17Tools input,.fg17Tools select,.fg17Compare select{width:100%;background:#07111e;color:#e8f2ff;border:1px solid #28405d;border-radius:8px;padding:8px}.fg17TableHead,.fg17Row{display:grid;grid-template-columns:minmax(170px,1.3fr) 62px 72px 72px 120px minmax(190px,1.2fr);gap:7px;align-items:center}.fg17TableHead{padding:6px 9px;background:#0b1b2d;color:#8fa6bf;font-size:8px;font-weight:900;border:1px solid #28405d;border-radius:8px 8px 0 0}.fg17Rows{border:1px solid #28405d;border-top:0;border-radius:0 0 8px 8px;overflow:hidden}.fg17Row{padding:8px 9px;border-top:1px solid #1b3047}.fg17Row:first-child{border-top:0}.fg17Row>div:not(.fg17Player):not(.fg17Owner){text-align:center}.fg17Row b{display:block;font-size:11px}.fg17Row span{display:block;color:#8fa6bf;font-size:8px;margin-top:2px}.fg17PlayerLink{border:0;background:transparent;color:#eaf5ff;font-size:12px;font-weight:900;padding:0;cursor:pointer;text-align:left}.fg17PlayerLink:hover{color:#7dd3fc;text-decoration:underline}.fg17Owner b{color:#7dd3fc}.fg17Owner span{font-size:9px;line-height:1.3}
    .fg17DrawerBackdrop{position:fixed;inset:0;background:rgba(0,0,0,.48);z-index:390}.fg17Drawer{position:fixed;right:0;top:0;bottom:0;width:min(430px,92vw);z-index:400;background:#071421;border-left:1px solid #31506d;box-shadow:-14px 0 35px rgba(0,0,0,.45);padding:14px;overflow:auto}.fg17DrawerHead{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;padding-bottom:10px;border-bottom:1px solid #27415d}.fg17DrawerHead h3{margin:0;font-size:20px}.fg17DrawerHead span{font-size:10px;color:#8fa6bf}.fg17DrawerHead button{border:1px solid #31506d;background:#0b1b2d;color:#eaf5ff;border-radius:8px;width:34px;height:34px;font-size:20px}.fg17DrawerGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:10px 0}.fg17DrawerGrid>div,.fg17Drawer section{border:1px solid #28405d;border-radius:9px;background:#0a1929;padding:9px}.fg17DrawerGrid span,.fg17Drawer section h4{display:block;font-size:8px;color:#7dd3fc;text-transform:uppercase;margin:0 0 4px}.fg17DrawerGrid b{font-size:16px}.fg17Drawer section{margin:7px 0}.fg17Drawer section p{margin:0;font-size:11px;line-height:1.45}.fg17Drawer section p+p{margin-top:5px}
    .fg17Compare{max-width:1000px}.fg17ComparePick{display:grid;grid-template-columns:1fr 44px 1fr;gap:8px;align-items:end;background:#081524;border:1px solid #28405d;border-radius:11px;padding:12px}.fg17ComparePick label{font-size:9px;color:#8fa6bf;font-weight:850}.fg17ComparePick select{display:block;margin-top:5px}.fg17Swap{display:grid;place-items:center;height:38px;font-size:22px;color:#7dd3fc}.fg17CompareResult{margin-top:9px}.fg17CompareVerdict{display:inline-block;padding:5px 9px;border-radius:999px;background:#243246;font-size:10px;font-weight:900}.fg17CompareVerdict.good{background:#0f4a38;color:#9df5ca}.fg17CompareVerdict.bad{background:#4a1f28;color:#ffc2cb}.fg17CompareMove{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0}.fg17CompareMove span{border:1px solid #28405d;border-radius:8px;padding:9px;background:#081524;font-size:11px}.fg17CompareMetrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.fg17CompareMetrics>div{border:1px solid #28405d;background:#081524;border-radius:8px;padding:9px}.fg17CompareMetrics span{display:block;font-size:8px;color:#8fa6bf}.fg17CompareMetrics b{display:block;margin-top:3px;font-size:15px}.fg17CompareNote,.fg17CompareEmpty{margin-top:8px;color:#8fa6bf;font-size:10px}
    @media(max-width:1000px){.fg17TableHead,.fg17Row{grid-template-columns:minmax(150px,1.2fr) 56px 64px 64px 100px minmax(150px,1fr)}}
    @media(max-width:900px){.fg17RecGrid{grid-template-columns:1fr}.fg17TableHead{display:none}.fg17Rows{border-top:1px solid #28405d;border-radius:8px}.fg17Row{grid-template-columns:minmax(0,1fr) repeat(3,54px);grid-template-rows:auto auto auto;gap:5px}.fg17Player{grid-column:1}.fg17Row>div:nth-child(5){grid-column:1/-1;grid-row:2;text-align:left!important}.fg17Owner{grid-column:1/-1;grid-row:3;padding-top:3px}.fg17Tools{grid-template-columns:minmax(0,1fr) 85px}.fg17CompareMetrics{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:700px){.fg17Head{display:block;margin-left:50px}.fg17Cache{display:inline-block;margin-top:6px}.fg17Tabs{display:grid;grid-template-columns:repeat(2,1fr)}.fg17Row{grid-template-columns:minmax(0,1fr) repeat(3,48px);padding:9px 8px}.fg17Row b{font-size:10px}.fg17PlayerLink{font-size:12px}.fg17Card{padding:8px}.fg17ComparePick{grid-template-columns:1fr}.fg17Swap{height:20px}.fg17CompareMetrics{grid-template-columns:1fr 1fr}.fg17Drawer{width:100vw}.fg17DrawerGrid{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(style);
})();
