/* Decision context polish: bye weeks in Compare Players + simplified Trade Target Radar. */
(function(){
  const esc26=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt26=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  const bye26=p=>{try{const w=typeof bye==='function'?bye(p):null;return Number.isFinite(Number(w))?Number(w):null}catch{return null}};
  function find26(side,id){const pool=side==='drop'?(typeof mineTeam==='function'?(mineTeam()?.players||[]):[]):(typeof waiverPool==='function'?waiverPool():[]);return (pool||[]).find(p=>ident(p)===String(id))||null}
  function patchCompareBye(){
    if(currentView!=='playerhub'||!document.querySelector('.fg20Pickers'))return;
    document.querySelectorAll('.fg20Picker').forEach(box=>{const side=box.dataset.side;box.querySelectorAll('.fg20Row').forEach(row=>{if(row.dataset.fg26Bye)return;const p=find26(side,row.dataset.id);const w=bye26(p);const meta=row.querySelector('span:first-child small');if(meta&&w!=null)meta.textContent += ` · BYE ${w}`;row.dataset.fg26Bye='1'})});
    const d=$('fg17Drop'),a=$('fg17Add');if(d&&a){[['drop',d.value],['add',a.value]].forEach(([side,id])=>{const p=find26(side,id),w=bye26(p),card=document.querySelector(`.fg21Selected.${side}`);if(card&&w!=null&&!card.querySelector('.fg26Bye')){const info=card.querySelector('div>small');if(info){const s=document.createElement('span');s.className='fg26Bye';s.textContent=`BYE ${w}`;info.insertAdjacentElement('afterend',s)}}})}
  }
  function tradeImpact26(x){const give=x?.give||[],get=x?.get||[],sent=give.reduce((n,p)=>n+(Number.isFinite(Number(p?.ros_points))?Number(p.ros_points):0),0),recv=get.reduce((n,p)=>n+(Number.isFinite(Number(p?.ros_points))?Number(p.ros_points):0),0),delta=recv-sent;return `<div class="fg26ImpactGrid"><div><b>Your lineup</b><span>Week ${Number(x?.wg||0)>=0?'+':''}${fmt26(x?.wg)} · ROS ${Number(x?.rg||0)>=0?'+':''}${fmt26(x?.rg)}</span></div><div><b>Their lineup</b><span>Week ${Number(x?.ow||0)>=0?'+':''}${fmt26(x?.ow)} · ROS ${Number(x?.orr||0)>=0?'+':''}${fmt26(x?.orr)}</span></div><div><b>Projected value</b><span>You receive ${fmt26(recv)} ROS and send ${fmt26(sent)} → ${delta>=0?'+':''}${fmt26(delta)} to you.</span></div><div><b>Why their roster cut usually doesn't matter</b><span>Fantasy Guru already evaluates the opponent's post-trade roster. A player they would cut is only relevant to you if that player becomes a useful waiver option.</span></div></div>`}
  function patchTradeRadar(){
    if(currentView!=='playerhub')return;const active=[...document.querySelectorAll('.fg17Tab.active')][0];if(!active||!/trade/i.test(active.textContent||''))return;
    const card=[...document.querySelectorAll('.fg17Card')].find(c=>/Trade Target Radar/i.test(c.querySelector('h3')?.textContent||''));if(!card||card.dataset.fg26)return;
    const ideas=typeof tradeIdeas==='function'?tradeIdeas():[],radar=typeof tradeRadar==='function'?tradeRadar():[],strict=new Set(ideas.flatMap(x=>(x.get||[]).map(ident))),alt=radar.filter(x=>!strict.has(ident(x.get?.[0]))),show=(alt.length?alt:radar).slice(0,8);card.dataset.fg26='1';
    card.innerHTML=`<h3>Trade Target Radar</h3><div class="fg26Intro">Focus on what you receive, what you give up, and whether the move improves your roster. The other team's potential cut is secondary and is not shown here unless it matters to you.</div>${show.length?show.map((x,i)=>{const target=x.get?.[0],give=x.give||[],tv=target&&typeof tradeValue==='function'?tradeValue(target).score:null,bw=bye26(target),fair=Math.round(Number(x.fr||0)*100),offer=give.length?give.map(p=>`${esc26(p.name)}${bye26(p)!=null?` · Bye ${bye26(p)}`:''}`).join(' + '):'No realistic offer framework yet';return `<div class="fg26Trade"><div class="fg26TradeTop"><div><b>${esc26(target?.name||'Target')}</b><span>${esc26(pos(target?.position))}${target?.team?' · '+esc26(target.team):''}${bw!=null?' · Bye '+bw:''}${tv!=null?' · Guru Trade Value '+tv+'/100':''}</span></div><button type="button" data-fg26-impact="${i}">Trade Impact</button></div><div class="fg26Line"><b>You would give:</b> ${offer}</div><div class="fg26Line"><b>Projection balance:</b> ${Number.isFinite(fair)?fair+'%':'—'}${Number.isFinite(Number(x?.rg))?` · Your ROS lineup ${Number(x.rg)>=0?'+':''}${fmt26(x.rg)}`:''}</div><div class="fg26Impact" data-fg26-panel="${i}" hidden>${tradeImpact26(x)}</div></div>`}).join(''):'<div class="muted">No realistic trade targets found.</div>'}`;
    card.querySelectorAll('[data-fg26-impact]').forEach(b=>b.onclick=()=>{const p=card.querySelector(`[data-fg26-panel="${b.dataset.fg26Impact}"]`);if(p)p.hidden=!p.hidden});
  }
  function enhance26(){patchCompareBye();patchTradeRadar()}
  document.addEventListener('click',e=>{if(e.target.closest?.('.fg17Tabs,.fg20Row'))setTimeout(enhance26,0)});
  document.addEventListener('change',e=>{if(['fg17Drop','fg17Add'].includes(e.target?.id)||e.target.closest?.('.fg20Picker'))setTimeout(enhance26,0)});
  const oldShow=showView;showView=function(v){const out=oldShow(v);if(v==='playerhub')setTimeout(enhance26,0);return out};
  const style=document.createElement('style');style.textContent=`
    .fg26Bye{display:block!important;font-size:7px!important;color:#fbbf24!important;margin-top:2px!important;font-weight:800}.fg26Intro{font-size:9px;line-height:1.4;color:#8fa6bf;background:#07111e;border:1px solid #223a53;border-radius:7px;padding:7px 8px;margin:6px 0 8px}.fg26Trade{padding:10px 0;border-top:1px solid #1e324a}.fg26TradeTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.fg26TradeTop>div{display:grid;gap:2px}.fg26TradeTop b{font-size:12px}.fg26TradeTop span{font-size:9px;color:#8fa6bf}.fg26TradeTop button{border:1px solid #2d5e86;background:#0b2033;color:#c9ecff;border-radius:7px;padding:6px 9px;font-size:9px;font-weight:900;cursor:pointer}.fg26Line{font-size:9.5px;color:#b9cbe0;margin-top:5px}.fg26Line b{color:#e8f2ff}.fg26Impact{margin-top:8px;border:1px solid #28405d;border-radius:8px;background:#07111e;padding:8px}.fg26ImpactGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.fg26ImpactGrid>div{border:1px solid #1e324a;border-radius:7px;padding:7px}.fg26ImpactGrid b{display:block;font-size:9px;color:#7dd3fc}.fg26ImpactGrid span{display:block;font-size:9px;color:#b9cbe0;margin-top:2px;line-height:1.35}@media(max-width:700px){.fg26ImpactGrid{grid-template-columns:1fr}}
  `;document.head.appendChild(style);setTimeout(enhance26,0);
})();