/* Matchup Intel workspace: presentation only; reuses existing matchup, projection and roster-intel logic. */
function fg10TeamByName(name){return (C?.league_teams||[]).find(t=>String(t.team||'').trim().toLowerCase()===String(name||'').trim().toLowerCase())||null}
function fg10StatusClass(s){if(typeof fg9StatusClass==='function')return fg9StatusClass(s);const u=String(s||'ACTIVE').toUpperCase();if(/IR|PUP|NFI/.test(u))return'ir';if(/OUT|DOUBTFUL/.test(u))return'out';if(/QUESTION|LIMITED|DNP/.test(u))return'warn';return'active'}
function fg10ShortIntel(s,n=86){s=String(s||'No current intel available.').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s}
function fg10Date(s){return typeof fmtIntelDate==='function'?fmtIntelDate(s):String(s||'')}
function fg10TeamAnalysis(team){return (analysis?.team_details||[]).find(x=>String(x.roster_id)===String(team?.roster_id)||String(x.team||'')===String(team?.team||''))||null}
async function fg10LoadIntel(team){
  if(!team)return{players:[],generated_at:''};
  const cached=typeof readIntelCache==='function'?readIntelCache(team):null;if(cached?.data)return cached.data;
  const ctx={...C,my_team:{...C.my_team,team:team.team,roster_id:team.roster_id,players:team.players}};
  try{const d=await get('/api/roster-intel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({context:ctx})});if(typeof writeIntelCache==='function')writeIntelCache(team,d);return d}catch{return{players:[],generated_at:''}}
}
function fg10Maps(team,intel){
  const td=fg10TeamAnalysis(team),pmap=new Map((td?.players||[]).map(p=>[String(p.name||'').toLowerCase(),p])),rmap=new Map((team?.players||[]).map(p=>[String(p.name||'').toLowerCase(),p])),imap=new Map((intel?.players||[]).map(p=>[String(p.name||'').toLowerCase(),p]));return{pmap,rmap,imap}
}
function fg10Row(x,maps,intelGenerated){
  const key=String(x?.name||'').toLowerCase(),p=maps.pmap.get(key)||{},r=maps.rmap.get(key)||{},i=maps.imap.get(key)||{};
  const status=r.injury_status||x.injury_status||i.injury_status||'ACTIVE',cls=fg10StatusClass(status),slot=x.slot||r.lineup_slot||(r.starter?x.position:'BN')||x.position||'—';
  const actual=x.actual_points==null?'—':Number(x.actual_points).toFixed(1),proj=finite(x.value)?Number(x.value).toFixed(1):finite(p.weekly_points)?Number(p.weekly_points).toFixed(1):'—',ros=finite(p.ros_points)?Number(p.ros_points).toFixed(1):'—';
  const full=i.intel||i.news||'No reliable current context found.',kind=i.intel_type||'CURRENT OUTLOOK',date=fg10Date(i.intel_date||String(intelGenerated||'').slice(0,10));
  return `<div class="fg10Player" data-fg10-player><button class="fg10PlayerMain" type="button" data-fg10-toggle><span class="fg10Slot">${esc(slot)}</span><span class="fg10Identity"><b>${esc(x.name||r.name||'Player')}</b><small>${esc(x.position||r.position||'')}${r.team?' · '+esc(r.team):''}</small></span><span><i class="fg10Status ${cls}">${esc(status)}</i></span><span class="fg10Num"><b>${actual}</b><small>PTS</small></span><span class="fg10Num"><b>${proj}</b><small>PROJ</small></span><span class="fg10Num"><b>${ros}</b><small>ROS</small></span><span class="fg10Intel"><b>${esc(fg10ShortIntel(full))}</b><small>${esc(kind)}${date?' · '+esc(date):''}</small></span><span class="fg10Arrow">›</span></button><div class="fg10Detail"><div><b>${esc(kind)}</b><span>${esc(full)}</span></div><div><b>Projection context</b><span>Week ${proj} · ROS ${ros} · live status ${esc(status)}${date?' · intel '+esc(date):''}</span></div></div></div>`
}
function fg10TeamCard(title,teamData,team,intel){
  const maps=fg10Maps(team,intel),starters=teamData?.lineup||[],bench=teamData?.bench||[];
  return `<section class="fg10Team"><div class="fg10TeamHead"><div><h3>${esc(title)}</h3><span>${team===fg10TeamByName(C?.my_team?.team)?'YOU':'OPPONENT'}</span></div><strong>Proj ${Number(teamData?.projection||0).toFixed(1)}</strong></div><div class="fg10ColHead"><span>POS</span><span>PLAYER</span><span>STATUS</span><span>PTS</span><span>PROJ</span><span>ROS</span><span>INTEL</span><span></span></div><div class="fg10SectionLabel">STARTERS <span>${starters.length}</span></div>${starters.map(x=>fg10Row(x,maps,intel?.generated_at)).join('')}<div class="fg10Bench"><div class="fg10SectionLabel">BENCH <span>${bench.length}</span></div>${bench.map(x=>fg10Row(x,maps,intel?.generated_at)).join('')}</div></section>`
}
function fg10AllStatusPlayers(d,teams,intels){
  const out=[];[['you',d.you,teams.you,intels.you],['them',d.them,teams.them,intels.them]].forEach(([side,td,team,intel])=>{const maps=fg10Maps(team,intel);[...(td?.lineup||[]),...(td?.bench||[])].forEach(x=>{const k=String(x.name||'').toLowerCase(),r=maps.rmap.get(k)||{},i=maps.imap.get(k)||{},status=r.injury_status||x.injury_status||i.injury_status||'ACTIVE';if(fg10StatusClass(status)!=='active')out.push({side,name:x.name,status,starter:(td?.lineup||[]).some(z=>String(z.name)===String(x.name))})})});return out.sort((a,b)=>Number(b.starter)-Number(a.starter))
}
function fg10AlertHTML(d,teams,intels){
  const ss=typeof ssDecisions==='function'?ssDecisions():{changes:[]},inj=fg10AllStatusPlayers(d,teams,intels),edge=Number(d.you?.projection||0)-Number(d.them?.projection||0),leader=edge>=0?d.you.team:d.them.team;
  const ssText=ss.changes?.length?`${ss.changes.length} lineup change${ss.changes.length===1?'':'s'} worth reviewing.`:'Your current starters match the highest-projected lineup.';
  const edgeText=`${esc(leader)} has a ${Math.abs(edge).toFixed(1)}-point projected edge.`;
  const injText=inj.length?`${esc(inj[0].name)} is ${esc(inj[0].status)}${inj.length>1?` · ${inj.length-1} more flag${inj.length-1===1?'':'s'}`:''}.`:'No major injury flags in either matchup roster.';
  return `<div class="fg10Alerts"><button data-fg10-view="startsit"><span>⚡</span><div><b>Lineup Check</b><small>${ssText}</small></div></button><div><span>📊</span><div><b>Projection Edge</b><small>${edgeText}</small></div></div><div><span>🚑</span><div><b>Injury Watch</b><small>${injText}</small></div></div></div>`
}
async function fg10RenderMatchup(){
  const d=matchupData;if(!d?.available){$('content').innerHTML=`<h2>⚔️ Matchup</h2><div class="card muted">${esc(d?.message||'Matchup unavailable.')}</div>`;return}
  $('content').innerHTML='<div class="fg10Loading">Loading matchup intel for both teams…</div>';
  const youTeam=fg10TeamByName(d.you?.team)||C?.league_teams?.find(t=>String(t.roster_id)===String(C?.my_team?.roster_id))||null,themTeam=fg10TeamByName(d.them?.team)||null;
  const [youIntel,themIntel]=await Promise.all([fg10LoadIntel(youTeam),fg10LoadIntel(themTeam)]),teams={you:youTeam,them:themTeam},intels={you:youIntel,them:themIntel};
  const edge=Number(d.you?.projection||0)-Number(d.them?.projection||0),edgeTxt=`${edge>=0?'+':''}${edge.toFixed(1)} projected ${edge>=0?'advantage':'deficit'}`;
  $('content').innerHTML=`<div class="fg10Wrap"><div class="fg10Title"><div><h2>⚔️ Matchup Center</h2><span>Live score, projections and current intel for both teams.</span></div><b>Week ${esc(C.current_week)}</b></div><section class="fg10Score"><div><b>${esc(d.you.team)}</b><strong>${Number(d.you.actual||0).toFixed(1)}</strong><small>Proj ${Number(d.you.projection||0).toFixed(1)}</small></div><span>VS</span><div><b>${esc(d.them.team)}</b><strong>${Number(d.them.actual||0).toFixed(1)}</strong><small>Proj ${Number(d.them.projection||0).toFixed(1)}</small></div><em class="${edge>=0?'good':'bad'}">${esc(edgeTxt)}</em></section>${fg10AlertHTML(d,teams,intels)}<div class="fg10Teams">${fg10TeamCard(d.you.team,d.you,youTeam,youIntel)}${fg10TeamCard(d.them.team,d.them,themTeam,themIntel)}</div></div>`;
  $('content').querySelectorAll('[data-fg10-toggle]').forEach(b=>b.onclick=()=>b.closest('[data-fg10-player]')?.classList.toggle('open'));
  $('content').querySelectorAll('[data-fg10-view]').forEach(b=>b.onclick=()=>showView(b.dataset.fg10View));
}
(function(){
 const style=document.createElement('style');style.textContent=`
 .fg10Wrap{max-width:1240px;margin:0 auto}.fg10Title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.fg10Title h2{margin:0 0 2px}.fg10Title span{font-size:10px;color:#8fa6bf}.fg10Score{position:relative;display:grid;grid-template-columns:1fr 56px 1fr;gap:8px;align-items:center;background:#081524;border:1px solid #28405d;border-radius:11px;padding:10px 18px;margin-bottom:8px}.fg10Score>div{text-align:center}.fg10Score>div b{display:block;font-size:13px}.fg10Score strong{display:block;font-size:25px;line-height:1.05}.fg10Score small{color:#8fa6bf}.fg10Score>span{width:38px;height:38px;border-radius:50%;background:#10263b;display:grid;place-items:center;font-weight:900;margin:auto}.fg10Score em{position:absolute;left:50%;bottom:-8px;transform:translateX(-50%);padding:3px 10px;border-radius:999px;font-size:9px;font-style:normal;font-weight:900}.fg10Score em.good{background:#114c38;color:#86efac}.fg10Score em.bad{background:#4a1f28;color:#fecdd3}
 .fg10Alerts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:13px 0 8px}.fg10Alerts>div,.fg10Alerts>button{display:grid;grid-template-columns:24px 1fr;gap:7px;align-items:start;text-align:left;background:#081524;border:1px solid #28405d;border-radius:9px;padding:8px;color:#e8f2ff}.fg10Alerts>button{cursor:pointer}.fg10Alerts b{display:block;font-size:10px}.fg10Alerts small{display:block;color:#9ab0c7;font-size:9px;line-height:1.3;margin-top:2px}.fg10Teams{display:grid;grid-template-columns:1fr 1fr;gap:8px;align-items:start}.fg10Team{background:#071524;border:1px solid #28405d;border-radius:10px;overflow:hidden;min-width:0}.fg10TeamHead{display:flex;justify-content:space-between;align-items:center;padding:8px 9px;border-bottom:1px solid #28405d}.fg10TeamHead h3{font-size:12px;margin:0}.fg10TeamHead span{font-size:8px;color:#7dd3fc}.fg10TeamHead strong{font-size:10px}.fg10ColHead,.fg10PlayerMain{display:grid;grid-template-columns:42px minmax(118px,1.15fr) 72px 42px 48px 52px minmax(125px,1.4fr) 16px;gap:5px;align-items:center}.fg10ColHead{padding:5px 7px;background:#0b1b2d;color:#8fa6bf;font-size:7px;font-weight:900}.fg10SectionLabel{display:flex;justify-content:space-between;padding:5px 8px;background:#0a2130;color:#7dd3fc;font-size:8px;font-weight:900;border-top:1px solid #1d344b}.fg10SectionLabel span{opacity:.8}.fg10Player{border-top:1px solid #1b3047}.fg10PlayerMain{width:100%;border:0;background:transparent;color:#eef7ff;padding:6px 7px;text-align:left;cursor:pointer}.fg10PlayerMain:hover{background:#0b1d30}.fg10Slot{font-size:9px;font-weight:900;color:#dce8f4}.fg10Identity b{display:block;font-size:10px}.fg10Identity small,.fg10Num small,.fg10Intel small{display:block;color:#8fa6bf;font-size:7px;margin-top:1px}.fg10Status{display:inline-block;border-radius:999px;padding:2px 5px;font-size:7px;font-weight:900;font-style:normal;white-space:nowrap}.fg10Status.active{background:#113b2d;color:#86efac}.fg10Status.warn{background:#49380f;color:#fde68a}.fg10Status.out{background:#4a1f28;color:#fecdd3}.fg10Status.ir{background:#38234f;color:#e9d5ff}.fg10Num{text-align:right}.fg10Num b{font-size:10px}.fg10Intel{min-width:0}.fg10Intel b{display:block;font-size:8px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fg10Arrow{font-size:17px;color:#6fbce9;transition:transform .15s}.fg10Detail{display:none;padding:7px 10px 8px 49px;background:#0a1b2d;border-top:1px dashed #29405d}.fg10Detail>div{display:grid;grid-template-columns:110px 1fr;gap:8px;padding:3px 0}.fg10Detail b{font-size:8px;color:#7dd3fc}.fg10Detail span{font-size:9px;color:#b7c7d9;line-height:1.35}.fg10Player.open .fg10Detail{display:block}.fg10Player.open .fg10Arrow{transform:rotate(90deg)}.fg10Bench{background:#06111f}.fg10Loading{padding:30px;text-align:center;color:#9ab0c7}
 @media(max-width:1180px){.fg10Teams{grid-template-columns:1fr}.fg10Alerts{grid-template-columns:1fr}.fg10ColHead,.fg10PlayerMain{grid-template-columns:38px minmax(120px,1fr) 70px 40px 46px 48px minmax(110px,1.2fr) 14px}}
 `;document.head.appendChild(style);
 renderMatchup=fg10RenderMatchup;
})();
