/* Performance/UX pass: event-driven Player Hub enhancements, split Start/Sit, no Guru startup flash. */
(function(){
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const F=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
  const N=(v,d=1)=>F(v)?Number(v).toFixed(d):'—';
  const compact=n=>{n=Number(n||0);const a=Math.abs(n);if(a>=1e6)return(n/1e6).toFixed(a>=1e7?0:1).replace('.0','')+'M';if(a>=1e3)return(n/1e3).toFixed(a>=1e4?0:1).replace('.0','')+'K';return Math.round(n).toLocaleString()};
  let sortMode='default', actualMap=null, actualKey='';

  /* ---------- Start / Sit: starters left, bench right ---------- */
  function renderSplitStartSit(){
    const m=mineTeam(),d=ssDecisions();if(!m){$('content').innerHTML='<h2>✅ Start / Sit</h2><div class="card muted">Roster data unavailable.</div>';return}
    const opt=ssOptimized(),optIds=new Set(opt.map(x=>ident(x.player))),curIds=new Set((m.players||[]).filter(p=>p.starter).map(ident)),slotById=new Map(opt.map(x=>[ident(x.player),x.slot]));
    const moveIn=new Set((d.changes||[]).map(x=>ident(x.start))),moveOut=new Set((d.changes||[]).map(x=>ident(x.sit)));
    const totalOpt=opt.reduce((s,x)=>s+Number(x.value||0),0),current=(m.players||[]).filter(p=>p.starter&&F(p.weekly_points)).reduce((s,p)=>s+Number(p.weekly_points),0),gain=totalOpt-current;
    const starters=[],bench=[];
    for(const p of m.players||[]){const id=ident(p),inOpt=optIds.has(id),inCur=curIds.has(id),label=moveIn.has(id)?'MOVE IN':moveOut.has(id)?'MOVE OUT':inOpt?'START':'BENCH',cls=moveIn.has(id)?'in':moveOut.has(id)?'out':inOpt?'start':'bench',row={p,id,inOpt,inCur,label,cls,slot:slotById.get(id)||p.lineup_slot||''};(inOpt?starters:bench).push(row)}
    const sort=(a,b)=>Number(b.p.weekly_points??-999)-Number(a.p.weekly_points??-999);starters.sort(sort);bench.sort(sort);
    const row=x=>`<div class="fg25SSRow ${x.cls}"><div><b class="fg25Badge">${E(x.label)}</b><small>${E(x.slot)}</small></div><div class="fg25Who"><b>${E(x.p.name)}</b><small>${E(pos(x.p.position))}${x.p.team?' · '+E(x.p.team):''}${x.p.injury_status?' · '+E(x.p.injury_status):''}</small></div><div><b>${N(x.p.weekly_points)}</b><small>WEEK</small></div><div><b>${N(x.p.ros_points)}</b><small>ROS</small></div><div><b>${Number(x.p.weekly_source_count||0)||'—'}/3</b><small>SOURCES</small></div></div>`;
    const changes=d.changes||[];
    $('content').innerHTML=`<div class="fg25SS"><div class="fg25SSHead"><div><h2>✅ Start / Sit</h2><span>Week ${C.current_week} · full roster, optimized for your exact lineup slots.</span></div><div class="fg25Gain"><span>Projected lineup gain</span><b>${gain>0?'+':''}${N(gain)}</b></div></div><div class="fg25Summary"><section><h3>Guru Lineup Check</h3>${changes.length?changes.map(x=>`<div class="fg25Decision"><span>Start <b>${E(x.start.name)}</b> over ${E(x.sit.name)} · ${E(x.slot)}</span><strong>+${N(x.diff)}</strong></div>`).join(''):'<div class="fg25Good">✅ Your current starters already match the highest-projected lineup.</div>'}</section><section><h3>What this means</h3><p>${changes.length?`${changes.length} change${changes.length===1?'':'s'} improves the highest published projection this week.`:'There is no projected reason to change starters right now.'}</p><p class="muted">Close calls within 5 points: ${(d.close||[]).length}. Small edges are not treated as certainty.</p></section></div><div class="fg25Columns"><section><div class="fg25ColHead"><h3>Starters</h3><span>${starters.length}</span></div><div class="fg25MiniHead"><span>ACTION / SLOT</span><span>PLAYER</span><span>WEEK</span><span>ROS</span><span>SRC</span></div>${starters.map(row).join('')}</section><section><div class="fg25ColHead"><h3>Bench</h3><span>${bench.length}</span></div><div class="fg25MiniHead"><span>ACTION / SLOT</span><span>PLAYER</span><span>WEEK</span><span>ROS</span><span>SRC</span></div>${bench.map(row).join('')}</section></div></div>`;
  }
  renderStartSit=renderSplitStartSit;

  /* ---------- Lightweight Player Hub overview ---------- */
  function needRows(){const m=mineTeam();return m?needProfile(m).slice().sort((a,b)=>(b.ros_rank||0)-(a.ros_rank||0)).slice(0,4):[]}
  function bestFitRows(){
    const m=mineTeam();if(!m)return[];const pr=needProfile(m),items=(typeof storedWaiverIdeas==='function'?storedWaiverIdeas():[]).slice(0,6),out=[];
    for(const x of items){const a=x?.add;if(!a)continue;const q=pos(a.position),need=needScore(pr,q),wg=Number(x.wg||0),rg=Number(x.rg||0);if(['K','DEF'].includes(q)&&wg<1.5&&rg<.5)continue;out.push({...x,need,score:rg*5+wg*2+need*9})}
    return out.sort((a,b)=>b.score-a.score).slice(0,4)
  }
  function movers(){const rows=[];for(const p of analysis?.opportunities?.sleeper_trending||[]){rows.push(p)}return rows.sort((a,b)=>Math.abs(Number(b.sleeper_net_24h||0))-Math.abs(Number(a.sleeper_net_24h||0))).slice(0,4)}
  function overviewHTML(){const needs=needRows(),fits=bestFitRows(),mv=movers();return `<div class="fg25Overview"><div class="fg25Hero"><div><h3>Your Player Market</h3><p>Start here. See needs and the moves most likely to help before opening a detailed tool.</p></div><button data-fg25-tab="compare">Compare an Add/Drop →</button></div><div class="fg25OverviewGrid"><section><h3>🎯 Roster Needs</h3>${needs.map(x=>`<div class="fg25Line"><b>${E(x.position)}</b><span>League rank #${x.ros_rank||'—'} · need ${Math.round((needScore(needProfile(mineTeam()),x.position)||0)*100)}%</span></div>`).join('')||'<div class="muted">No roster needs available.</div>'}</section><section><h3>📋 Best Roster Fits</h3>${fits.map(x=>`<button class="fg25Fit" data-fg25-tab="compare"><b>${E(x.add.name)} <span>${E(pos(x.add.position))}</span></b><small>Need ${Math.round(x.need*100)}% · Week ${Number(x.wg||0)>=0?'+':''}${N(x.wg)} · ROS ${Number(x.rg||0)>=0?'+':''}${N(x.rg)}</small></button>`).join('')||'<div class="muted">No available add currently clears the recommendation bar.</div>'}</section><section><h3>🔥 Market Movers</h3>${mv.map(p=>{const net=Number(p.sleeper_net_24h||0),adds=Number(p.sleeper_adds_24h||0),drops=Number(p.sleeper_drops_24h||0);return `<div class="fg25Line"><b>${E(p.name)}</b><span>${E(p.position||'')} · Adds ${compact(adds)} · Drops ${compact(drops)} · Net ${net>=0?'+':''}${compact(net)}</span></div>`}).join('')||'<div class="muted">No strong Sleeper movement right now.</div>'}<div class="fg25Note">Market movement is Sleeper add/drop behavior, not a projection.</div></section><section><h3>🧭 Explore</h3><button class="fg25Nav" data-fg25-tab="available">Available Players</button><button class="fg25Nav" data-fg25-tab="activity">Market Activity</button><button class="fg25Nav" data-fg25-tab="trade">Trade Targets</button></section></div></div>`}
  function installOverview(){
    const tabs=document.querySelector('.fg17Tabs'),body=$('fg17Body');if(!tabs||!body)return;let ov=$('fg25OverviewTab');if(!ov){ov=document.createElement('button');ov.id='fg25OverviewTab';ov.className='fg17Tab';ov.textContent='Overview';tabs.prepend(ov)}
    tabs.querySelectorAll('.fg17Tab').forEach(x=>x.classList.remove('active'));ov.classList.add('active');body.innerHTML=overviewHTML();
    ov.onclick=installOverview;body.querySelectorAll('[data-fg25-tab]').forEach(b=>b.onclick=()=>{const t=[...tabs.querySelectorAll('.fg17Tab')].find(x=>x.dataset.tab===b.dataset.fg25Tab);if(t)t.click()});
  }

  /* ---------- Browse enhancements run only after a real user action ---------- */
  function rowVal(row,mode){if(mode==='name')return String(row.querySelector('.fg17PlayerLink')?.textContent||'').toLowerCase();const idx={actual:1,week:2,ros:3}[mode];const t=row.children[idx]?.querySelector('b')?.textContent||'';const n=Number(String(t).replace(/[^0-9+-.]/g,''));return Number.isFinite(n)?n:-Infinity}
  function sortRows(){const box=document.querySelector('.fg17Rows');if(!box||sortMode==='default')return;const rows=[...box.querySelectorAll(':scope>.fg17Row')];rows.sort((a,b)=>sortMode==='name'?String(rowVal(a,'name')).localeCompare(String(rowVal(b,'name'))):Number(rowVal(b,sortMode))-Number(rowVal(a,sortMode)));rows.forEach(r=>box.appendChild(r))}
  function installSort(){const tools=document.querySelector('.fg17Tools');if(!tools||$('fg25Sort'))return;const s=document.createElement('select');s.id='fg25Sort';s.innerHTML='<option value="default">Sort: Default</option><option value="actual">Actual ↓</option><option value="week">Week Proj ↓</option><option value="ros">ROS ↓</option><option value="name">Name A–Z</option>';s.value=sortMode;s.onchange=()=>{sortMode=s.value;sortRows()};tools.appendChild(s)}
  async function sleeperActualMap(){if(String(C?.platform||'').toUpperCase()!=='SLEEPER')return null;const key=`${C?.league?.season||2026}:${C?.current_week||1}`;if(actualMap&&actualKey===key)return actualMap;actualKey=key;actualMap=new Map();try{const r=await fetch(`https://api.sleeper.app/stats/nfl/regular/${C?.league?.season||2026}/${C?.current_week||1}`);if(!r.ok)return actualMap;const d=await r.json(),cfg=C?.league?.scoring_settings||{};for(const[id,v]of Object.entries(d||{})){const st=v?.stats||v||{};let total=0,used=0;for(const[k,w]of Object.entries(cfg)){if(F(w)&&F(st[k])){total+=Number(w)*Number(st[k]);used++}}if(used)actualMap.set(String(id),Math.round(total*100)/100)}}catch{}return actualMap}
  async function patchActuals(){if(!document.querySelector('.fg17Rows'))return;const sl=await sleeperActualMap();if(!sl)return;const raw=new Map();for(const p of analysis?.waiver_pool||[])raw.set(ident(p),p);for(const t of analysis?.team_details||[])for(const p of t.players||[])raw.set(ident(p),p);document.querySelectorAll('.fg17Row').forEach(row=>{const id=row.querySelector('.fg17PlayerLink')?.dataset.playerId,p=raw.get(id);if(!p)return;const sid=String(p.sleeper_id||p.id||'');if(sl.has(sid)){const b=row.children[1]?.querySelector('b');if(b)b.textContent=Number(sl.get(sid)).toFixed(1)}});sortRows()}
  function enhanceCurrentTab(){if(!document.querySelector('.fg17Tabs'))return;installSort();patchActuals()}

  /* Search focus: restore after c17 rerenders the rows. */
  document.addEventListener('input',e=>{if(e.target?.id!=='fg17Search')return;const value=e.target.value,start=e.target.selectionStart??value.length,end=e.target.selectionEnd??value.length;requestAnimationFrame(()=>{const n=$('fg17Search');if(n){n.focus();try{n.setSelectionRange(start,end)}catch{}}})},true);

  /* ---------- View wiring ---------- */
  const baseShow=showView;showView=function(v){const out=baseShow(v);if(v==='startsit')renderSplitStartSit();if(v==='playerhub'){setTimeout(()=>{installOverview();document.querySelectorAll('.fg17Tabs .fg17Tab').forEach(b=>{if(b.id==='fg25OverviewTab'||b.dataset.fg25Bound)return;b.dataset.fg25Bound='1';b.addEventListener('click',()=>setTimeout(enhanceCurrentTab,0))})},0)}return out};

  /* Remove startup flash: c25 is loaded after focus state has been established. */
  document.body.classList.add('fg25Ready');

  const style=document.createElement('style');style.textContent=`
    .fg25SS{max-width:1320px}.fg25SSHead{display:flex;justify-content:space-between;gap:12px;margin-bottom:9px}.fg25SSHead h2{margin:0}.fg25SSHead span{font-size:10px;color:#8fa6bf}.fg25Gain{border:1px solid #285845;background:#0c211c;border-radius:9px;padding:8px 11px;text-align:right}.fg25Gain span{display:block;font-size:8px}.fg25Gain b{font-size:18px;color:#86efac}.fg25Summary{display:grid;grid-template-columns:1.2fr .8fr;gap:9px;margin-bottom:9px}.fg25Summary section,.fg25Columns>section{background:#081524;border:1px solid #28405d;border-radius:10px;padding:10px}.fg25Summary h3,.fg25ColHead h3{margin:0 0 7px}.fg25Summary p{font-size:10px;line-height:1.4}.fg25Decision{display:flex;justify-content:space-between;gap:8px;padding:6px 0;border-bottom:1px solid #1e324a;font-size:10px}.fg25Decision strong,.fg25Good{color:#86efac}.fg25Columns{display:grid;grid-template-columns:1fr 1fr;gap:9px;align-items:start}.fg25ColHead{display:flex;justify-content:space-between;align-items:center}.fg25ColHead span{font-size:9px;color:#8fa6bf}.fg25MiniHead,.fg25SSRow{display:grid;grid-template-columns:90px minmax(150px,1fr) 58px 58px 54px;gap:6px;align-items:center}.fg25MiniHead{font-size:7px;color:#8fa6bf;font-weight:900;padding:5px 7px;background:#0b1b2d;border-radius:6px}.fg25SSRow{padding:7px;border-bottom:1px solid #1e324a}.fg25SSRow:last-child{border-bottom:0}.fg25SSRow>div:nth-child(n+3){text-align:right}.fg25SSRow b{display:block;font-size:10px}.fg25SSRow small{display:block;font-size:7px;color:#8fa6bf;margin-top:1px}.fg25Badge{display:inline-block!important;width:max-content;border-radius:999px;padding:3px 6px;background:#12314d;color:#7dd3fc;font-size:8px!important}.fg25SSRow.in .fg25Badge{background:#0f4a38;color:#9df5ca}.fg25SSRow.out .fg25Badge{background:#4a1f28;color:#ffc2cb}.fg25SSRow.bench .fg25Badge{background:#18263a;color:#aab9ca}
    .fg25Overview{display:grid;gap:9px}.fg25Hero{display:flex;justify-content:space-between;gap:10px;align-items:center;border:1px solid #31506d;background:#0a1a2a;border-radius:10px;padding:11px}.fg25Hero h3{margin:0 0 3px}.fg25Hero p{margin:0;color:#8fa6bf;font-size:10px}.fg25Hero button,.fg25Nav{border:1px solid #2d5e86;background:#0b2033;color:#c9ecff;border-radius:7px;padding:7px 9px;font-weight:850}.fg25OverviewGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fg25OverviewGrid section{background:#081524;border:1px solid #28405d;border-radius:10px;padding:10px}.fg25OverviewGrid h3{margin:0 0 7px}.fg25Line,.fg25Fit{display:block;width:100%;text-align:left;padding:7px 0;border:0;border-bottom:1px solid #1e324a;background:transparent;color:#e8f2ff}.fg25Line:last-child,.fg25Fit:last-of-type{border-bottom:0}.fg25Line b,.fg25Fit b{display:block;font-size:11px}.fg25Line span,.fg25Fit small{display:block;font-size:9px;color:#8fa6bf;margin-top:2px}.fg25Fit span{color:#7dd3fc}.fg25Note{font-size:8.5px;color:#8fa6bf;margin-top:7px}.fg25Nav{display:block;width:100%;margin-top:6px;text-align:left}.fg17Tools{grid-template-columns:minmax(0,1fr) 110px 140px!important}#fg25Sort{width:100%;background:#07111e;color:#e8f2ff;border:1px solid #28405d;border-radius:8px;padding:8px}
    @media(max-width:900px){.fg25Columns,.fg25Summary,.fg25OverviewGrid{grid-template-columns:1fr}.fg25MiniHead,.fg25SSRow{grid-template-columns:76px minmax(120px,1fr) 52px 52px 48px}.fg17Tools{grid-template-columns:1fr 1fr!important}.fg17Tools #fg17Search{grid-column:1/-1}}
  `;document.head.appendChild(style);
})();
