const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
function playerKey(p){return norm(p?.name)+'|'+posNorm(p?.position)}
function actualForPlayer(p,map){if(!map)return null;const ids=[p?.sleeper_id,p?.espn_id,p?.gsis_id,p?.id].filter(v=>v!==null&&v!==undefined&&String(v)!=='').map(String);for(const id of ids){if(finite(map[id]))return Number(map[id])}const key=playerKey(p);return finite(map[key])?Number(map[key]):null}

async function sleeperLiveMatchup(context){
  const leagueId=context?.league?.id,week=context?.current_week,myId=Number(context?.my_team?.roster_id);if(!leagueId||!week||!myId)return null;
  const r=await fetch(`https://api.sleeper.app/v1/league/${leagueId}/matchups/${week}`,{headers:{Accept:'application/json','User-Agent':'FantasyGuru/1.0'}});if(!r.ok)return null;
  const rows=await r.json(),mine=(rows||[]).find(x=>Number(x.roster_id)===myId);if(!mine?.matchup_id)return null;
  const opp=(rows||[]).find(x=>Number(x.matchup_id)===Number(mine.matchup_id)&&Number(x.roster_id)!==myId);if(!opp)return null;
  return{opponentId:Number(opp.roster_id),myActuals:mine.players_points||{},oppActuals:opp.players_points||{},myTotal:finite(mine.points)?Number(mine.points):null,oppTotal:finite(opp.points)?Number(opp.points):null,refreshedAt:new Date().toISOString(),scoreSource:'Sleeper live matchup'}
}
function espnWeeklyActual(p,week){const stats=Array.isArray(p?.stats)?p.stats:[];const exact=stats.find(s=>Number(s?.statSourceId)===0&&Number(s?.statSplitTypeId)===1&&Number(s?.scoringPeriodId)===Number(week)&&finite(s?.appliedTotal));if(exact)return Number(exact.appliedTotal);const fallback=stats.find(s=>Number(s?.statSourceId)===0&&Number(s?.scoringPeriodId)===Number(week)&&finite(s?.appliedTotal));return fallback?Number(fallback.appliedTotal):null}
function espnRosterActuals(entries=[],week){const out={};for(const e of entries||[]){const p=e?.playerPoolEntry?.player||e?.player||{},pts=espnWeeklyActual(p,week);if(!finite(pts))continue;const id=String(p.id||e?.playerId||'');if(id)out[id]=Number(pts);const name=p.fullName||p.name||'',pos=({1:'QB',2:'RB',3:'WR',4:'TE',5:'K',16:'DEF'})[p.defaultPositionId]||String(p.defaultPositionId||'');if(name)out[norm(name)+'|'+posNorm(pos)]=Number(pts)}return out}
async function espnLiveMatchup(context){
  if(!process.env.ESPN_S2||!process.env.ESPN_SWID)return null;
  const season=context?.league?.season||'2026',leagueId=context?.league?.id||'1673474732',week=Number(context?.current_week||1),myId=Number(context?.my_team?.roster_id),base=`https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/${season}/segments/0/leagues/${leagueId}`,headers={'Cookie':`espn_s2=${process.env.ESPN_S2}; SWID=${process.env.ESPN_SWID}`,'Accept':'application/json','User-Agent':'Mozilla/5.0'};
  const r=await fetch(`${base}?view=mMatchup&view=mRoster&view=mStatus&scoringPeriodId=${week}`,{headers});if(!r.ok)return null;const data=await r.json();let opponentId=null,myTotal=null,oppTotal=null;
  for(const m of data?.schedule||[]){const period=Number(m?.matchupPeriodId||m?.scoringPeriodId||week);if(period!==week)continue;const home=Number(m?.home?.teamId),away=Number(m?.away?.teamId);if(home===myId&&away){opponentId=away;myTotal=finite(m?.home?.totalPoints)?Number(m.home.totalPoints):null;oppTotal=finite(m?.away?.totalPoints)?Number(m.away.totalPoints):null;break}if(away===myId&&home){opponentId=home;myTotal=finite(m?.away?.totalPoints)?Number(m.away.totalPoints):null;oppTotal=finite(m?.home?.totalPoints)?Number(m.home.totalPoints):null;break}}
  if(!opponentId)return null;const mine=(data?.teams||[]).find(t=>Number(t.id)===myId),opp=(data?.teams||[]).find(t=>Number(t.id)===Number(opponentId));
  return{opponentId:Number(opponentId),myActuals:espnRosterActuals(mine?.roster?.entries||[],week),oppActuals:espnRosterActuals(opp?.roster?.entries||[],week),myTotal,oppTotal,refreshedAt:new Date().toISOString(),scoreSource:'ESPN live matchup'}
}
function sourceStrength(lineup=[]){if(!lineup.length)return'No trusted lineup';const n=Math.min(...lineup.map(x=>Number(x.source_count||0)));return n>=3?'3-source throughout':n===2?'At least 2-source throughout':n===1?'Includes single-source values':'Incomplete source data'}
function rowStrength(n){n=Number(n||0);return n>=3?'3-source':n===2?'2-source':n===1?'Single Source':'No trusted value'}
function cleanLineup(lineup=[],teamPlayers=[],actualMap={}){const lookup=new Map((teamPlayers||[]).map(p=>[playerKey(p),p]));return lineup.map(x=>{const p=lookup.get(playerKey(x))||x,actual=actualForPlayer(p,actualMap),proj=finite(x.value)?Number(Number(x.value).toFixed(1)):null;return{slot:x.slot,name:x.name,position:x.position,value:proj,actual_points:finite(actual)?Number(Number(actual).toFixed(1)):null,source_count:Number(x.source_count||0),source_strength:finite(actual)?`Actual ${Number(actual).toFixed(1)} · Projected ${proj?.toFixed?.(1)??'—'}`:rowStrength(x.source_count),sources:Array.isArray(x.sources)?x.sources:[],injury_status:x.injury_status||p.injury_status||null}})}
function cleanBench(teamPlayers=[],lineup=[],actualMap={}){
  const starterKeys=new Set((lineup||[]).map(playerKey));
  return (teamPlayers||[]).filter(p=>p?.starter===false||(!starterKeys.has(playerKey(p))&&p?.starter!==true)).map(p=>{const actual=actualForPlayer(p,actualMap),proj=finite(p.weekly_points)?Number(Number(p.weekly_points).toFixed(1)):null;return{slot:'BN',name:p.name,position:p.position,value:proj,actual_points:finite(actual)?Number(Number(actual).toFixed(1)):null,source_count:Number(p.weekly_source_count||0),source_strength:rowStrength(p.weekly_source_count),sources:Array.isArray(p.weekly_sources)?p.weekly_sources:[],injury_status:p.injury_status||null}}).sort((a,b)=>Number(b.value||0)-Number(a.value||0))
}
function starterComparisons(myLine=[],opLine=[]){const order=['QB','RB','WR','TE','FLEX','SUPER_FLEX','DEF','K'],rows=[];for(const slot of order){const mine=myLine.filter(x=>x.slot===slot),opp=opLine.filter(x=>x.slot===slot),n=Math.max(mine.length,opp.length);for(let i=0;i<n;i++){const a=mine[i],b=opp[i],av=Number(a?.value||0),bv=Number(b?.value||0),label=slot+(n>1?' '+(i+1):'')+' · '+(a?.name||'Empty')+' vs '+(b?.name||'Empty');rows.push({group:label,you:Number(av.toFixed(1)),opponent:Number(bv.toFixed(1)),edge:Number((av-bv).toFixed(1)),slot,you_player:a?.name||null,opponent_player:b?.name||null})}}return rows}

export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'POST only'});
  try{
    const {context,analysis}=req.body||{};if(!context||!analysis?.team_details)return res.status(400).json({error:'Context and current ranking analysis are required'});
    const platform=String(context.platform||'').toUpperCase(),live=platform==='SLEEPER'?await sleeperLiveMatchup(context):platform==='ESPN'?await espnLiveMatchup(context):null,opponentId=live?.opponentId||null;
    if(!opponentId)return res.json({available:false,message:'Current opponent could not be identified from the league platform.'});
    const mine=analysis.team_details.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team),opp=analysis.team_details.find(t=>String(t.roster_id)===String(opponentId));
    if(!mine||!opp)return res.json({available:false,message:'Opponent was identified, but its normalized roster was not found in the current analysis.'});
    const myLine=mine.weekly_lineup||[],opLine=opp.weekly_lineup||[];if(!finite(mine.weekly_starters)||!finite(opp.weekly_starters))return res.json({available:false,message:'Matchup analytics withheld because one side lacks a complete trusted weekly starter projection.'});
    const cleanMine=cleanLineup(myLine,mine.players||[],live?.myActuals||{}),cleanOpp=cleanLineup(opLine,opp.players||[],live?.oppActuals||{}),myBench=cleanBench(mine.players||[],myLine,live?.myActuals||{}),oppBench=cleanBench(opp.players||[],opLine,live?.oppActuals||{});
    const position_edges=starterComparisons(myLine,opLine),flags=[...myLine.map(x=>({side:'YOU',...x})),...opLine.map(x=>({side:'OPP',...x}))].filter(x=>x.injury_status&&String(x.injury_status).toUpperCase()!=='ACTIVE').map(x=>({side:x.side,name:x.name,status:x.injury_status,slot:x.slot})),margin=Number((mine.weekly_starters-opp.weekly_starters).toFixed(1));
    return res.json({available:true,opponent:{team:opp.team,roster_id:opp.roster_id},you:{team:mine.team,projection:Number(mine.weekly_starters.toFixed(1)),actual:finite(live?.myTotal)?Number(Number(live.myTotal).toFixed(1)):null,source_strength:sourceStrength(myLine),lineup:cleanMine,bench:myBench},them:{team:opp.team,projection:Number(opp.weekly_starters.toFixed(1)),actual:finite(live?.oppTotal)?Number(Number(live.oppTotal).toFixed(1)):null,source_strength:sourceStrength(opLine),lineup:cleanOpp,bench:oppBench},projected_margin:margin,lean:margin>5?'ADVANTAGE YOU':margin<-5?'ADVANTAGE OPPONENT':'CLOSE MATCHUP',position_edges,injury_flags:flags,score_refreshed_at:live?.refreshedAt||new Date().toISOString(),score_source:live?.scoreSource||context.platform||'League platform',note:'Actual starter and bench fantasy points refresh directly from the league platform whenever the matchup loads. Projected values remain the trusted weekly consensus.'})
  }catch(e){return res.status(500).json({error:e.message})}
}
