import ffaData from '../data/ffanalytics_projections.json';
import { scoreConsensusStats } from './league-scoring.js';
import { getUniversalEspnProjections } from './espn-universal.js';

const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const sum=a=>a.reduce((x,y)=>x+y,0);
const present=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const meanAvailable=(...v)=>{const a=v.filter(present).map(Number);return a.length?avg(a):null};
const pct=(n,d)=>d?Math.round(n/d*100):0;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
function slotCounts(slots=[]){const c={};for(const s of slots)c[s]=(c[s]||0)+1;return c}
function eligible(pos,slot){if(slot===pos)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(pos);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(pos);return false}
function startSlots(slots=[]){return slots.filter(s=>!['BN','IR'].includes(s))}
function optimize(players,slots,field){const used=new Set(),picks=[];const order=[...startSlots(slots)].sort((a,b)=>{const r={QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8};return(r[a]||9)-(r[b]||9)});for(const slot of order){let best=null,bi=-1;players.forEach((p,i)=>{if(used.has(i)||!eligible(p.position,slot)||!present(p[field]))return;const v=Number(p[field]);if(!best||v>Number(best[field])){best=p;bi=i}});if(best){used.add(bi);picks.push({slot,player:best,value:Number(best[field])})}}return picks}
function rosterCapacity(players,slots){return optimize(players.map(p=>({...p,__roster_value:1})),slots,'__roster_value').length}
function requiredPositionScore(players,pos,field,count){const vals=players.filter(p=>p.position===pos&&present(p[field])).map(p=>Number(p[field])).sort((a,b)=>b-a);const n=Math.max(1,count||1);return vals.length<n?null:avg(vals.slice(0,n))}
function rankMap(rows,key){const sorted=[...rows].filter(r=>present(r[key])).sort((a,b)=>b[key]-a[key]),m={};sorted.forEach((r,i)=>m[r.team]=i+1);return m}
function qualityLevel(n){return n>=95?'HIGH':n>=85?'GOOD':n>=70?'PRELIMINARY':'INSUFFICIENT'}
function scoringMode(context){const settings=context.league?.scoring_settings||{};if(present(settings.rec)){const r=Number(settings.rec);if(r>=0.75)return'PPR';if(r>0)return'HALF'}const s=(context.league?.scoring_summary||[]).join(' ').toUpperCase();if(s.includes('HALF'))return'HALF';if(s.includes('PPR'))return'PPR';return'STD'}
function sleeperPoints(row,scoring){const st=row?.stats||row||{};if(scoring==='PPR'&&present(st.pts_ppr))return Number(st.pts_ppr);if(scoring==='HALF'&&present(st.pts_half_ppr))return Number(st.pts_half_ppr);if(present(st.pts_std))return Number(st.pts_std);return null}
async function sleeperGetJson(url){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'FantasyGuru/1.0'}});if(!r.ok)throw new Error('Sleeper API error '+r.status);return r.json()}
async function sleeperFirst(urls){for(const u of urls){try{const d=await sleeperGetJson(u);if(d&&((Array.isArray(d)&&d.length)||(!Array.isArray(d)&&Object.keys(d).length)))return d}catch{}}return {}}
async function sleeperWeekly(season,week){return sleeperFirst(['https://api.sleeper.app/projections/nfl/'+season+'/'+week+'?season_type=regular','https://api.sleeper.app/v1/projections/nfl/regular/'+season+'/'+week])}
async function sleeperSeasonProjections(season){return sleeperFirst(['https://api.sleeper.app/projections/nfl/regular/'+season,'https://api.sleeper.app/v1/projections/nfl/regular/'+season])}
async function sleeperSeasonStats(season){return sleeperFirst(['https://api.sleeper.app/stats/nfl/regular/'+season,'https://api.sleeper.app/v1/stats/nfl/regular/'+season])}
async function sleeperPlayers(){try{return await sleeperGetJson('https://api.sleeper.app/v1/players/nfl')}catch{return {}}}
function sleeperMetaIndexes(players={}){const bySleeper=new Map(),byEspn=new Map(),byGsis=new Map(),byNamePos=new Map();for(const [sid,p] of Object.entries(players||{})){const name=p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' '),position=posNorm(p?.position),rec={sleeper_id:String(sid),espn_id:p?.espn_id!=null?String(p.espn_id):null,gsis_id:p?.gsis_id?String(p.gsis_id):null,name,position};bySleeper.set(String(sid),rec);if(rec.espn_id)byEspn.set(rec.espn_id,rec);if(rec.gsis_id)byGsis.set(rec.gsis_id,rec);if(name)byNamePos.set(norm(name)+'|'+position,rec)}return{bySleeper,byEspn,byGsis,byNamePos}}
function identityFor(p,metaIdx){const pos=posNorm(p.position),name=p.name||'',rawId=String(p.id||''),sid=p.sleeper_id?String(p.sleeper_id):null,eid=p.espn_id?String(p.espn_id):null,gid=p.gsis_id?String(p.gsis_id):null;let hit=null,method=null;if(sid&&metaIdx.bySleeper.has(sid)){hit=metaIdx.bySleeper.get(sid);method='sleeper_id'}else if(gid&&metaIdx.byGsis.has(gid)){hit=metaIdx.byGsis.get(gid);method='gsis_id'}else if(eid&&metaIdx.byEspn.has(eid)){hit=metaIdx.byEspn.get(eid);method='espn_id'}else if(rawId&&metaIdx.bySleeper.has(rawId)){hit=metaIdx.bySleeper.get(rawId);method='sleeper_roster_id'}else if(rawId&&metaIdx.byEspn.has(rawId)){hit=metaIdx.byEspn.get(rawId);method='espn_roster_id'}else{hit=metaIdx.byNamePos.get(norm(name)+'|'+pos)||null;if(hit)method='name_position_fallback'}const sleeperId=hit?.sleeper_id||sid||null,espnId=hit?.espn_id||eid||null,gsisId=hit?.gsis_id||gid||null,canonical=gsisId||sleeperId||(espnId?'espn:'+espnId:null)||(rawId?'raw:'+rawId:null);return{sleeper_id:sleeperId,espn_id:espnId,gsis_id:gsisId,canonical_player_id:canonical,id_match_method:method||'unmapped'}}
function sleeperIndexes(raw={},players={},scoring='PPR'){const byId=new Map(),byName=new Map();const rows=Array.isArray(raw)?raw:Object.entries(raw||{}).map(([id,v])=>({player_id:id,...(v||{})}));for(const row of rows){const id=String(row.player_id||row.player?.player_id||row.player?.id||'');const meta=players?.[id]||row.player||{};const name=meta.full_name||[meta.first_name,meta.last_name].filter(Boolean).join(' ')||row.player_name||row.name||'';const position=posNorm(meta.position||row.position||row.player_position),points=sleeperPoints(row,scoring),rec={id,name,position,points};if(id)byId.set(id,rec);if(name)byName.set(norm(name)+'|'+position,rec)}return{byId,byName}}
function findSleeper(idx,p){const sid=p.sleeper_id?String(p.sleeper_id):'',raw=String(p.id||'');return(sid&&idx.byId.get(sid)&&idx.byId.get(sid).position===posNorm(p.position)?idx.byId.get(sid):null)||(raw&&idx.byId.get(raw)&&idx.byId.get(raw).position===posNorm(p.position)?idx.byId.get(raw):null)||idx.byName.get(norm(p.name)+'|'+posNorm(p.position))||null}
function ffaIndexes(data={}){const byGsis=new Map(),bySleeper=new Map(),byEspn=new Map(),byNamePos=new Map();for(const row of Array.isArray(data?.players)?data.players:[]){const rec={...row,position:posNorm(row.position||row.pos||'')};if(rec.gsis_id)byGsis.set(String(rec.gsis_id),rec);if(rec.sleeper_id)bySleeper.set(String(rec.sleeper_id),rec);if(rec.espn_id)byEspn.set(String(rec.espn_id),rec);if(rec.name)byNamePos.set(norm(rec.name)+'|'+rec.position,rec)}return{byGsis,bySleeper,byEspn,byNamePos}}
function findFfa(idx,p){const pos=posNorm(p.position),gid=p.gsis_id?String(p.gsis_id):'',sid=p.sleeper_id?String(p.sleeper_id):'',eid=p.espn_id?String(p.espn_id):'';const hit=(gid&&idx.byGsis.get(gid))||(sid&&idx.bySleeper.get(sid))||(eid&&idx.byEspn.get(eid))||idx.byNamePos.get(norm(p.name)+'|'+pos)||null;return hit&&posNorm(hit.position)===pos?hit:null}
function universalEspnIndexes(feed={}){const bySleeper=new Map(),byEspn=new Map(),byGsis=new Map(),byNamePos=new Map();for(const row of feed?.players||[]){const rec={...row,position:posNorm(row.position)};if(rec.sleeper_id)bySleeper.set(String(rec.sleeper_id),rec);if(rec.espn_id)byEspn.set(String(rec.espn_id),rec);if(rec.gsis_id)byGsis.set(String(rec.gsis_id),rec);if(rec.name)byNamePos.set(norm(rec.name)+'|'+rec.position,rec)}return{bySleeper,byEspn,byGsis,byNamePos}}
function findUniversalEspn(idx,p){const pos=posNorm(p.position),raw=String(p.id||''),sid=p.sleeper_id?String(p.sleeper_id):'',eid=p.espn_id?String(p.espn_id):'',gid=p.gsis_id?String(p.gsis_id):'';const hit=(sid&&idx.bySleeper.get(sid))||(gid&&idx.byGsis.get(gid))||(eid&&idx.byEspn.get(eid))||(raw&&idx.bySleeper.get(raw))||(raw&&idx.byEspn.get(raw))||idx.byNamePos.get(norm(p.name)+'|'+pos)||null;return hit&&posNorm(hit.position)===pos?hit:null}
function buildLayer(layer,teamRows,context,quality){const pre=layer==='weekly'?'weekly':'ros',blocked=teamRows.some(r=>!r[pre+'_complete']);if(blocked){const incomplete=teamRows.filter(r=>!r[pre+'_complete']).map(r=>r.team+' ('+r[pre+'_slots_filled']+'/'+r.roster_capacity+' fillable starter slots have projections)').slice(0,8);return{blocked:true,my_ranks:null,power_rankings:[],my_explanation:null,data_quality:quality,message:'Power rankings withheld because one or more rostered, fillable starter slots do not have a trusted published '+(layer==='weekly'?'weekly':'rest-of-season')+' value. '+(incomplete.length?'Incomplete teams: '+incomplete.join(', ')+'.':'')}}const ranks={qb:rankMap(teamRows,pre+'_qb'),rb:rankMap(teamRows,pre+'_rb'),wr:rankMap(teamRows,pre+'_wr'),te:rankMap(teamRows,pre+'_te'),starters:rankMap(teamRows,pre+'_starters'),overall:rankMap(teamRows,pre+'_total')};const sorted=[...teamRows].sort((a,b)=>b[pre+'_total']-a[pre+'_total']),my=context.my_team.team,mine=teamRows.find(r=>r.team===my),n=teamRows.length,leagueAvg=avg(teamRows.map(r=>r[pre+'_starters']));const bullets=['Your optimal starters rank #'+ranks.starters[my]+' of '+n+' ('+mine[pre+'_starters'].toFixed(1)+' vs league average '+leagueAvg.toFixed(1)+').',layer==='weekly'?'Weekly values are the straight average of available ESPN and Sleeper published projections.':'ROS values are the straight average of available ESPN, Sleeper and ffanalytics crowd projections. ESPN raw stats are rescored to the selected league even when the league is hosted on Sleeper; ffanalytics is also scored using this league’s linear scoring rules, then converted to remaining-season points by subtracting actual points already scored.'];if(mine.empty_starter_slots)bullets.push('Your roster currently has '+mine.empty_starter_slots+' unfillable starter slot'+(mine.empty_starter_slots===1?'':'s')+'; each is effectively a zero until filled.');return{blocked:false,data_quality:quality,my_ranks:{qb:ranks.qb[my],rb:ranks.rb[my],wr:ranks.wr[my],te:ranks.te[my],starters:ranks.starters[my],overall:ranks.overall[my]},my_explanation:{summary:(layer==='weekly'?'This week':'Rest of season')+', you rank #'+ranks.overall[my]+' of '+n+'.',bullets},power_rankings:sorted.map(r=>({team:r.team,score:Math.round(r[pre+'_total']*10)/10,data_quality:quality.overall,note:(layer==='weekly'?'Optimal weekly starter projection ':'ROS consensus starter projection ')+r[pre+'_starters'].toFixed(1)+(r.empty_starter_slots?'; '+r.empty_starter_slots+' empty/unfillable starter slot'+(r.empty_starter_slots===1?'':'s')+' counted as 0':'')+(r[pre+'_depth']!==null?'; bench avg '+r[pre+'_depth'].toFixed(1):'')}))}}
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'POST only'});
 try{
  const {context}=req.body||{};if(!context?.league_teams?.length)return res.status(400).json({error:'League context missing'});
  const season=String(context.league?.season||'2026'),week=Number(context.current_week||1),scoring=scoringMode(context),slots=context.league?.roster_positions||[],counts=slotCounts(slots);
  const [slWeeklyRaw,slSeasonProjRaw,slSeasonStatsRaw,slPlayers,espnUniversal]=await Promise.all([sleeperWeekly(season,week),sleeperSeasonProjections(season),sleeperSeasonStats(season),sleeperPlayers(),getUniversalEspnProjections(context).catch(()=>({players:[]}))]);
  const metaIdx=sleeperMetaIndexes(slPlayers),slWeeklyIdx=sleeperIndexes(slWeeklyRaw,slPlayers,scoring),slSeasonProjIdx=sleeperIndexes(slSeasonProjRaw,slPlayers,scoring),slSeasonStatsIdx=sleeperIndexes(slSeasonStatsRaw,slPlayers,scoring),ffaIdx=ffaIndexes(ffaData),espnUniversalIdx=universalEspnIndexes(espnUniversal),researched=[],seen=new Set();
  for(const t of context.league_teams){for(const p0 of t.players||[]){
   const p={...p0,position:posNorm(p0.position)},ids=identityFor(p,metaIdx),dedupeKey=ids.canonical_player_id||norm(p.name)+'|'+p.position;if(seen.has(dedupeKey))continue;seen.add(dedupeKey);Object.assign(p,ids);
   const slW=findSleeper(slWeeklyIdx,p),slProj=findSleeper(slSeasonProjIdx,p),slActual=findSleeper(slSeasonStatsIdx,p),ffa=findFfa(ffaIdx,p),ep=findUniversalEspn(espnUniversalIdx,p);
   const espnWeekly=present(p0.espn_weekly_points)?Number(p0.espn_weekly_points):(present(ep?.espn_weekly_points)?Number(ep.espn_weekly_points):null),slWeeklyPts=slW&&present(slW.points)?Number(slW.points):null,espnRos=present(p0.espn_ros_points)?Number(p0.espn_ros_points):(present(ep?.espn_ros_points)?Number(ep.espn_ros_points):null);
   const slProjectedSeason=slProj&&present(slProj.points)?Number(slProj.points):null,slActualSeason=slActual&&present(slActual.points)?Number(slActual.points):null,slRos=present(slProjectedSeason)?Math.max(0,slProjectedSeason-Number(slActualSeason||0)):null;
   const ffaScore=ffa?scoreConsensusStats(context,ffa.consensus_stats||{},p.position):{points:null,scoring_mode:'unavailable',unsupported:[]},ffaProjectedSeason=present(ffaScore.points)?Number(ffaScore.points):null,universalActual=present(ep?.espn_actual_season_points)?Number(ep.espn_actual_season_points):null,platformActual=String(context.platform||'').toUpperCase()==='ESPN'?(present(p0.espn_actual_season_points)?Number(p0.espn_actual_season_points):null):(present(slActualSeason)?Number(slActualSeason):null),actualForFfa=present(universalActual)?universalActual:platformActual,ffaRos=present(ffaProjectedSeason)&&present(actualForFfa)?Math.max(0,ffaProjectedSeason-actualForFfa):null;
   const weekly=meanAvailable(espnWeekly,slWeeklyPts),ros=meanAvailable(espnRos,slRos,ffaRos),weeklySources=[present(espnWeekly)?'ESPN':null,present(slWeeklyPts)?'Sleeper':null].filter(Boolean),rosSources=[present(espnRos)?'ESPN':null,present(slRos)?'Sleeper':null,present(ffaRos)?'ffanalytics crowd':null].filter(Boolean);
   researched.push({id:String(p0.id||''),...ids,name:p0.name,position:p.position,injury_status:p0.injury_status||null,espn_weekly_points:espnWeekly,sleeper_weekly_points:slWeeklyPts,weekly_points:weekly,weekly_source_count:weeklySources.length,weekly_sources:weeklySources,espn_projected_season_points:present(p0.espn_projected_season_points)?Number(p0.espn_projected_season_points):(present(ep?.espn_projected_season_points)?Number(ep.espn_projected_season_points):null),espn_actual_season_points:present(p0.espn_actual_season_points)?Number(p0.espn_actual_season_points):universalActual,espn_ros_points:espnRos,sleeper_projected_season_points:slProjectedSeason,sleeper_actual_season_points:slActualSeason,sleeper_ros_points:slRos,ffanalytics_projected_season_points:ffaProjectedSeason,ffanalytics_ros_points:ffaRos,ffanalytics_scoring_mode:ffaScore.scoring_mode,ffanalytics_unsupported:ffaScore.unsupported||[],ffanalytics_source_count:ffa?.source_count??null,ffanalytics_sources:Array.isArray(ffa?.sources)?ffa.sources:(ffa?.sources?[ffa.sources]:[]),ros_points:ros,ros_source_count:rosSources.length,ros_sources:rosSources});
  }}
  const byCanonical=new Map(),bySleeper=new Map(),byEspn=new Map(),byName=new Map();for(const x of researched){if(x.canonical_player_id)byCanonical.set(x.canonical_player_id,x);if(x.sleeper_id)bySleeper.set(String(x.sleeper_id),x);if(x.espn_id)byEspn.set(String(x.espn_id),x);byName.set(norm(x.name)+'|'+x.position,x)}
  const getVal=p=>{const ids=identityFor({...p,position:posNorm(p.position)},metaIdx);return(ids.canonical_player_id&&byCanonical.get(ids.canonical_player_id))||(ids.sleeper_id&&bySleeper.get(String(ids.sleeper_id)))||(ids.espn_id&&byEspn.get(String(ids.espn_id)))||byName.get(norm(p.name)+'|'+posNorm(p.position))||null};
  const total=researched.length,identityMapped=researched.filter(p=>p.sleeper_id||p.gsis_id).length,nameFallbacks=researched.filter(p=>p.id_match_method==='name_position_fallback').length,espnWeeklyCoverage=pct(researched.filter(p=>present(p.espn_weekly_points)).length,total),sleeperWeeklyCoverage=pct(researched.filter(p=>present(p.sleeper_weekly_points)).length,total),weeklyAny=pct(researched.filter(p=>present(p.weekly_points)).length,total),weeklyTwo=pct(researched.filter(p=>p.weekly_source_count>=2).length,total),espnRosCoverage=pct(researched.filter(p=>present(p.espn_ros_points)).length,total),sleeperRosCoverage=pct(researched.filter(p=>present(p.sleeper_ros_points)).length,total),ffaRosCoverage=pct(researched.filter(p=>present(p.ffanalytics_ros_points)).length,total),rosAny=pct(researched.filter(p=>present(p.ros_points)).length,total),rosTwo=pct(researched.filter(p=>p.ros_source_count>=2).length,total),rosThree=pct(researched.filter(p=>p.ros_source_count>=3).length,total);
  const teamRows=context.league_teams.map(t=>{const ps=(t.players||[]).map(p=>({...p,position:posNorm(p.position),...(getVal(p)||{weekly_points:null,ros_points:null})}));const wOpt=optimize(ps,slots,'weekly_points'),rOpt=optimize(ps,slots,'ros_points'),required=startSlots(slots).length,capacity=rosterCapacity(ps,slots),wComplete=wOpt.length===capacity,rComplete=rOpt.length===capacity,emptySlots=Math.max(0,required-capacity);const wBench=ps.filter(p=>present(p.weekly_points)&&!wOpt.some(x=>x.player.canonical_player_id===p.canonical_player_id)).map(p=>Number(p.weekly_points)).sort((a,b)=>b-a).slice(0,4),rBench=ps.filter(p=>present(p.ros_points)&&!rOpt.some(x=>x.player.canonical_player_id===p.canonical_player_id)).map(p=>Number(p.ros_points)).sort((a,b)=>b-a).slice(0,4);const qbc=Math.max(1,(counts.QB||0)+(counts.SUPER_FLEX||0)),weeklyStarterSum=wComplete?sum(wOpt.map(x=>x.value)):null,rosStarterSum=rComplete?sum(rOpt.map(x=>x.value)):null;return{team:t.team,weekly_complete:wComplete,ros_complete:rComplete,weekly_slots_filled:wOpt.length,ros_slots_filled:rOpt.length,required_slots:required,roster_capacity:capacity,empty_starter_slots:emptySlots,weekly_qb:requiredPositionScore(ps,'QB','weekly_points',qbc),weekly_rb:requiredPositionScore(ps,'RB','weekly_points',counts.RB||1),weekly_wr:requiredPositionScore(ps,'WR','weekly_points',counts.WR||1),weekly_te:requiredPositionScore(ps,'TE','weekly_points',counts.TE||1),ros_qb:requiredPositionScore(ps,'QB','ros_points',qbc),ros_rb:requiredPositionScore(ps,'RB','ros_points',counts.RB||1),ros_wr:requiredPositionScore(ps,'WR','ros_points',counts.WR||1),ros_te:requiredPositionScore(ps,'TE','ros_points',counts.TE||1),weekly_starters:weeklyStarterSum,ros_starters:rosStarterSum,weekly_depth:wBench.length?avg(wBench):null,ros_depth:rBench.length?avg(rBench):null,weekly_total:weeklyStarterSum,ros_total:rosStarterSum}});
  const weeklyStarterCoverage=pct(teamRows.reduce((n,r)=>n+r.weekly_slots_filled,0),teamRows.reduce((n,r)=>n+r.roster_capacity,0)),rosStarterCoverage=pct(teamRows.reduce((n,r)=>n+r.ros_slots_filled,0),teamRows.reduce((n,r)=>n+r.roster_capacity,0));
  const weeklyQuality={overall:weeklyAny,level:qualityLevel(weeklyAny),espn:espnWeeklyCoverage,sleeper:sleeperWeeklyCoverage,two_source_consensus:weeklyTwo,starter_coverage:weeklyStarterCoverage},rosQuality={overall:rosAny,level:qualityLevel(rosAny),espn:espnRosCoverage,sleeper:sleeperRosCoverage,ffanalytics:ffaRosCoverage,two_source_consensus:rosTwo,three_source_consensus:rosThree,starter_coverage:rosStarterCoverage};
  const weekly=buildLayer('weekly',teamRows,context,weeklyQuality),ros=buildLayer('ros',teamRows,context,rosQuality),myIds=new Set((context.my_team?.players||[]).map(p=>identityFor({...p,position:posNorm(p.position)},metaIdx).canonical_player_id).filter(Boolean)),myNames=new Set((context.my_team?.players||[]).map(p=>p.name));
  const player_audit=researched.filter(p=>(p.canonical_player_id&&myIds.has(p.canonical_player_id))||myNames.has(p.name)).map(p=>({name:p.name,position:p.position,canonical_player_id:p.canonical_player_id,sleeper_id:p.sleeper_id,espn_id:p.espn_id,gsis_id:p.gsis_id,id_match_method:p.id_match_method,weekly_points:p.weekly_points,espn_weekly_points:p.espn_weekly_points,sleeper_weekly_points:p.sleeper_weekly_points,weekly_source_count:p.weekly_source_count,weekly_sources:p.weekly_sources,platform_status:p.injury_status,espn_projected_season_points:p.espn_projected_season_points,espn_actual_season_points:p.espn_actual_season_points,espn_ros_points:p.espn_ros_points,sleeper_projected_season_points:p.sleeper_projected_season_points,sleeper_actual_season_points:p.sleeper_actual_season_points,sleeper_ros_points:p.sleeper_ros_points,ffanalytics_projected_season_points:p.ffanalytics_projected_season_points,ffanalytics_ros_points:p.ffanalytics_ros_points,ffanalytics_scoring_mode:p.ffanalytics_scoring_mode,ffanalytics_source_count:p.ffanalytics_source_count,ffanalytics_sources:p.ffanalytics_sources,ros_points:p.ros_points,ros_ppg:p.ros_points,ros_source_count:p.ros_source_count,ros_sources:p.ros_sources}));
  return res.json({weekly,ros,data_quality:{weekly:weeklyQuality,ros:rosQuality},id_mapping:{source:'Sleeper players dictionary',mapped_players:identityMapped,total_players:total,coverage_pct:pct(identityMapped,total),name_position_fallbacks:nameFallbacks},espn_universal:{ready:Array.isArray(espnUniversal?.players)&&espnUniversal.players.length>0,player_count:espnUniversal?.player_count||0,source:espnUniversal?.source||null},ffanalytics:{ready:Array.isArray(ffaData?.players)&&ffaData.players.length>0,generated_at:ffaData?.generated_at||null,player_count:Array.isArray(ffaData?.players)?ffaData.players.length:0,ros_coverage_pct:ffaRosCoverage},player_audit,source_policy:{version:'3.6-universal',valuation_sources:['ESPN published weekly projections rescored to selected league when needed','Sleeper published weekly projections','ESPN published season projections rescored to selected league for ROS','Sleeper published season projections for ROS','ffanalytics equal-weight crowd season-stat consensus scored to league rules for ROS'],context_source:context.platform||'Platform',rule:'Fantasy Guru never invents a projection. League platform determines roster/settings only; projection providers are independent. Player joins prefer GSIS/Sleeper/ESPN IDs from the Sleeper dictionary; normalized name+position is fallback only. Weekly = mean of available ESPN/Sleeper weekly projections. ROS = mean of available ESPN, Sleeper and ffanalytics crowd remaining-season values. ESPN and ffanalytics raw stats are rescored to the selected league when necessary. A genuinely empty or unfillable roster slot is counted as 0 instead of blocking the entire league.'},method:'Free-source SOP v3.6: platform-independent provider layer, canonical identity mapping, ESPN + Sleeper direct data, ffanalytics crowd consensus for ROS, no FantasyPros and no OpenAI projection research; deterministic ranking math.'});
 }catch(e){res.status(500).json({error:e.message})}
}
