const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
const slotsOnly=s=>(s||[]).filter(x=>!['BN','IR'].includes(x));
function eligible(pos,slot){if(pos===slot)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(pos);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(pos);return false}
function optimize(players,slots,field){const used=new Set(),out=[],order=[...slotsOnly(slots)].sort((a,b)=>({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[a]||9)-({QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8}[b]||9));for(const slot of order){let best=null,bi=-1;players.forEach((p,i)=>{if(used.has(i)||!eligible(posNorm(p.position),slot)||!finite(p[field]))return;if(!best||Number(p[field])>Number(best[field])){best=p;bi=i}});if(best){used.add(bi);out.push({slot,player:best,value:Number(best[field])})}}return out}
const total=a=>a.reduce((n,x)=>n+Number(x.value||0),0);
const id=p=>String(p.canonical_player_id||p.gsis_id||p.sleeper_id||p.espn_id||p.id||p.name);
const sum=(a,f)=>a.reduce((n,p)=>n+(finite(p[f])?Number(p[f]):0),0);
function impact(roster,slots){return{weekly:total(optimize(roster,slots,'weekly_points')),ros:total(optimize(roster,slots,'ros_points'))}}
function packageScore(give,get){const gv=sum(give,'ros_points'),rv=sum(get,'ros_points');return gv&&rv?Math.min(gv,rv)/Math.max(gv,rv):0}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const{context,analysis}=req.body||{};if(!context||!analysis?.team_details)return res.status(400).json({error:'Current normalized league analysis is required'});const slots=context.league?.roster_positions||[],teams=analysis.team_details||[],mine=teams.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return res.status(400).json({error:'Your roster was not found'});const baseMine=impact(mine.players||[],slots),ideas=[];for(const opp of teams){if(opp===mine)continue;const baseOpp=impact(opp.players||[],slots),myPool=(mine.players||[]).filter(p=>finite(p.ros_points)).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,14),theirPool=(opp.players||[]).filter(p=>finite(p.ros_points)).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,14);const test=(give,get)=>{if(!give.length||!get.length||packageScore(give,get)<0.72)return;const mineAfter=(mine.players||[]).filter(p=>!give.some(g=>id(g)===id(p))).concat(get),oppAfter=(opp.players||[]).filter(p=>!get.some(g=>id(g)===id(p))).concat(give),mi=impact(mineAfter,slots),oi=impact(oppAfter,slots),myWG=mi.weekly-baseMine.weekly,myRG=mi.ros-baseMine.ros,opWG=oi.weekly-baseOpp.weekly,opRG=oi.ros-baseOpp.ros;if(myRG>0&&opRG>0&&(myWG>=-2||myRG>=5)&&(opWG>=-2||opRG>=5))ideas.push({partner:opp.team,you_send:give.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points})),you_receive:get.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points})),your_weekly_gain:+myWG.toFixed(1),your_ros_gain:+myRG.toFixed(1),their_weekly_gain:+opWG.toFixed(1),their_ros_gain:+opRG.toFixed(1),balance:+packageScore(give,get).toFixed(2),score:+(myRG+opRG+Math.max(0,myWG)+Math.max(0,opWG)).toFixed(1)})};for(const a of myPool)for(const b of theirPool)test([a],[b]);for(let i=0;i<myPool.length;i++)for(let j=i+1;j<Math.min(myPool.length,i+6);j++)for(const b of theirPool)test([myPool[i],myPool[j]],[b]);for(const a of myPool)for(let i=0;i<theirPool.length;i++)for(let j=i+1;j<Math.min(theirPool.length,i+6);j++)test([a],[theirPool[i],theirPool[j]])}ideas.sort((a,b)=>b.score-a.score);const uniq=[],seen=new Set();for(const x of ideas){const k=x.partner+'|'+x.you_send.map(p=>p.name).sort().join('+')+'|'+x.you_receive.map(p=>p.name).sort().join('+');if(!seen.has(k)){seen.add(k);uniq.push(x)}if(uniq.length>=10)break}return res.json({available:true,recommendations:uniq,no_trade:uniq.length===0,note:uniq.length?'These are deterministic trade candidates where both optimized rosters improve ROS. They are starting points for negotiation, not guarantees of acceptance.':'HOLD — no mutually beneficial 1-for-1, 2-for-1, or 1-for-2 trade was found in the evaluated player pool.'})}catch(e){return res.status(500).json({error:e.message})}}