const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const present=finite;
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
function startSlots(slots=[]){return slots.filter(s=>!['BN','IR'].includes(s))}
function eligible(pos,slot){if(slot===pos)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(pos);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(pos);return false}
function optimize(players,slots,field){const used=new Set(),picks=[],order=[...startSlots(slots)].sort((a,b)=>{const r={QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8};return(r[a]||9)-(r[b]||9)});for(const slot of order){let best=null,bi=-1;players.forEach((p,i)=>{if(used.has(i)||!eligible(posNorm(p.position),slot)||!present(p[field]))return;const v=Number(p[field]);if(!best||v>Number(best[field])){best=p;bi=i}});if(best){used.add(bi);picks.push({slot,player:best,value:Number(best[field])})}}return picks}
const total=a=>a.reduce((n,x)=>n+Number(x.value||0),0);
function identity(p){return String(p.canonical_player_id||p.gsis_id||p.sleeper_id||p.espn_id||p.id||p.name)}
function strength(n){return n>=3?'3-source':n===2?'2-source':n===1?'Single Source':'No trusted value'}
function tradeImpact(roster,slots){return{weekly:total(optimize(roster,slots,'weekly_points')),ros:total(optimize(roster,slots,'ros_points'))}}
function tradeSum(a,f){return a.reduce((n,p)=>n+(present(p[f])?Number(p[f]):0),0)}
function directSlotCount(slots,pos){return (slots||[]).filter(s=>s===pos).length}
function desiredDepthCount(slots,pos){if(pos==='RB'||pos==='WR')return Math.max(4,directSlotCount(slots,pos)+2);if(pos==='QB')return Math.max(2,directSlotCount(slots,'QB')+directSlotCount(slots,'SUPER_FLEX')+1);if(pos==='TE')return Math.max(2,directSlotCount(slots,'TE')+1);return 1}
function positionDepthValue(roster,slots,pos){const n=desiredDepthCount(slots,pos);return roster.filter(p=>posNorm(p.position)===pos&&present(p.ros_points)).map(p=>Number(p.ros_points)).sort((a,b)=>b-a).slice(0,n).reduce((a,b)=>a+b,0)}
function rankNeed(rank,teamCount){if(!finite(rank)||teamCount<=1)return 0.5;return Math.max(0,Math.min(1,(Number(rank)-1)/(teamCount-1)))}
function needProfile(context,analysis,mine){const teamCount=(analysis.team_details||[]).length||context.league_teams?.length||10,slots=context.league?.roster_positions||[],wr=analysis.weekly?.my_ranks||{},rr=analysis.ros?.my_ranks||{},players=mine?.players||[];return ['QB','RB','WR','TE'].map(pos=>{const k=pos.toLowerCase(),weeklyRank=wr[k]??null,rosRank=rr[k]??null,rankScore=rankNeed(weeklyRank,teamCount)*0.35+rankNeed(rosRank,teamCount)*0.65,have=players.filter(p=>posNorm(p.position)===pos&&present(p.ros_points)).length,desired=desiredDepthCount(slots,pos),depthShortage=Math.max(0,desired-have)/Math.max(1,desired),needScore=Math.min(1,rankScore*0.8+depthShortage*0.2);return{position:pos,weekly_rank:weeklyRank,ros_rank:rosRank,have,desired,need_score:+needScore.toFixed(3)}}).sort((a,b)=>b.need_score-a.need_score)}
function needForPosition(profile,pos){return profile.find(x=>x.position===pos)?.need_score||0}
function replacementBaselines(analysis){const out={};for(const pos of ['QB','RB','WR','TE']){const vals=(analysis.waiver_pool||[]).filter(p=>posNorm(p.position)===pos&&present(p.weekly_points)).map(p=>Number(p.weekly_points)).sort((a,b)=>b-a).slice(0,3);out[pos]=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}return out}
function playerVorp(p,baselines){const pos=posNorm(p.position);return present(p.weekly_points)?Number(p.weekly_points)-(baselines[pos]||0):0}
function packageVorp(players,baselines){return players.reduce((s,p)=>s+playerVorp(p,baselines),0)}
function fairness(give,get){const gv=tradeSum(give,'ros_points'),rv=tradeSum(get,'ros_points');if(!gv||!rv)return{ratio:0,diff_pct:100,give_value:gv,get_value:rv,net_ros:rv-gv};const ratio=Math.min(gv,rv)/Math.max(gv,rv);return{ratio,diff_pct:Math.abs(gv-rv)/Math.max(gv,rv)*100,give_value:gv,get_value:rv,net_ros:rv-gv}}
function scheduleMetric(players){const vals=[];for(const p of players){const v=present(p.playoff_schedule_score)?Number(p.playoff_schedule_score):present(p.schedule_score)?Number(p.schedule_score):null;if(v!==null)vals.push(v)}return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function findTrades(context,analysis){
 const slots=context.league?.roster_positions||[],teams=analysis.team_details||[],mine=teams.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return{recommendations:[],needs:[]};
 const profile=needProfile(context,analysis,mine),baselines=replacementBaselines(analysis),baseMine=tradeImpact(mine.players||[],slots),baseDepth={};for(const n of profile)baseDepth[n.position]=positionDepthValue(mine.players||[],slots,n.position);const ideas=[];
 for(const opp of teams){if(opp===mine)continue;const baseOpp=tradeImpact(opp.players||[],slots),myPool=(mine.players||[]).filter(p=>present(p.ros_points)).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,16),theirPool=(opp.players||[]).filter(p=>present(p.ros_points)).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,20);
  const test=(give,get)=>{if(!give.length||!get.length)return;const fair=fairness(give,get);if(fair.ratio<0.80||fair.net_ros<0)return;const mineAfter=(mine.players||[]).filter(p=>!give.some(g=>identity(g)===identity(p))).concat(get),oppAfter=(opp.players||[]).filter(p=>!get.some(g=>identity(g)===identity(p))).concat(give),mi=tradeImpact(mineAfter,slots),oi=tradeImpact(oppAfter,slots),myWG=mi.weekly-baseMine.weekly,myRG=mi.ros-baseMine.ros,opWG=oi.weekly-baseOpp.weekly,opRG=oi.ros-baseOpp.ros;
   if(opRG<=0)return;
   let bestNeedPos=null,needFit=0,bestNeedGain=0;for(const n of profile){const depthGain=positionDepthValue(mineAfter,slots,n.position)-(baseDepth[n.position]||0),fit=n.need_score*Math.max(0,depthGain);needFit+=fit;if(fit>bestNeedGain){bestNeedGain=fit;bestNeedPos=n.position}}
   const incomingNeed=get.reduce((s,p)=>s+needForPosition(profile,posNorm(p.position)),0)/get.length,outgoingNeed=give.reduce((s,p)=>s+needForPosition(profile,posNorm(p.position)),0)/give.length,roleFit=incomingNeed-outgoingNeed;
   const vorpDelta=packageVorp(get,baselines)-packageVorp(give,baselines),giveSchedule=scheduleMetric(give),getSchedule=scheduleMetric(get),scheduleDelta=giveSchedule!==null&&getSchedule!==null?getSchedule-giveSchedule:null;
   const standardWin=fair.net_ros>=0&&myRG>0;
   const consolidationWin=fair.net_ros>=0&&give.length>get.length&&myWG>3&&myRG>=0;
   const playoffWin=fair.net_ros>=0&&context?.playoff_locked===true&&scheduleDelta!==null&&scheduleDelta>=1.5&&myWG>=-1&&myRG>=0;
   if(!(standardWin||consolidationWin||playoffWin))return;
   if(myWG<-2)return;
   const override=consolidationWin?'CONSOLIDATION':playoffWin?'PLAYOFF_SCHEDULE':null;
   const championshipScore=myRG*1.7+Math.max(-2,myWG)*0.5+Math.max(0,vorpDelta)*1.2+needFit*0.35+Math.max(0,roleFit)*10+opRG*0.15+(scheduleDelta===null?0:scheduleDelta*2)+(fair.ratio*4)+(fair.net_ros*0.25)+(override==='CONSOLIDATION'?6:override==='PLAYOFF_SCHEDULE'?5:0);
   ideas.push({partner:opp.team,you_send:give.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points,vorp:+playerVorp(p,baselines).toFixed(1)})),you_receive:get.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points,vorp:+playerVorp(p,baselines).toFixed(1)})),fills_need:bestNeedPos,role_fit:+roleFit.toFixed(2),need_gain:+needFit.toFixed(1),your_weekly_gain:+myWG.toFixed(1),your_ros_gain:+myRG.toFixed(1),their_weekly_gain:+opWG.toFixed(1),their_ros_gain:+opRG.toFixed(1),raw_ros_sent:+fair.give_value.toFixed(1),raw_ros_received:+fair.get_value.toFixed(1),raw_ros_delta:+fair.net_ros.toFixed(1),fairness_ratio:+fair.ratio.toFixed(2),value_gap_pct:+fair.diff_pct.toFixed(1),vorp_gain:+vorpDelta.toFixed(1),schedule_gain:scheduleDelta===null?null:+scheduleDelta.toFixed(2),schedule_data_available:scheduleDelta!==null,override,score:+championshipScore.toFixed(1)})};
  for(const a of myPool)for(const b of theirPool)test([a],[b]);
  for(let i=0;i<myPool.length;i++)for(let j=i+1;j<Math.min(myPool.length,i+7);j++)for(const b of theirPool)test([myPool[i],myPool[j]],[b]);
  for(const a of myPool)for(let i=0;i<theirPool.length;i++)for(let j=i+1;j<Math.min(theirPool.length,i+7);j++)test([a],[theirPool[i],theirPool[j]])
 }
 ideas.sort((a,b)=>b.score-a.score);const uniq=[],seenPackages=new Set(),targetCounts=new Map();for(const x of ideas){const packageKey=x.partner+'|'+x.you_send.map(p=>p.name).sort().join('+')+'|'+x.you_receive.map(p=>p.name).sort().join('+');const targetKey=x.you_receive.map(p=>p.name).sort().join('+');if(seenPackages.has(packageKey))continue;const targetCount=targetCounts.get(targetKey)||0;if(targetCount>=2)continue;seenPackages.add(packageKey);targetCounts.set(targetKey,targetCount+1);uniq.push(x);if(uniq.length>=10)break}return{recommendations:uniq,needs:profile,replacement_baselines:baselines}
}

export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const {context,analysis,mode}=req.body||{};if(mode==='trades'){if(!context||!analysis?.team_details)return res.status(400).json({error:'Current normalized league analysis is required'});const out=findTrades(context,analysis),recommendations=out.recommendations,topNeeds=out.needs.slice(0,3);return res.json({available:true,needs:out.needs,replacement_baselines:out.replacement_baselines,recommendations,no_trade:recommendations.length===0,note:recommendations.length?'Trade Finder treats fairness as plausibility, not 50/50 equality: the other manager must receive at least 80% of the raw ROS value they send, while your side may never receive less raw ROS value than it gives up. Recommendations must also improve your championship roster through lineup impact, VORP/need, consolidation, or verified playoff schedule.':'HOLD — no realistic trade improved your roster without giving up value.',need_summary:topNeeds})}if(!context||!analysis?.team_details||!Array.isArray(analysis?.waiver_pool))return res.status(400).json({error:'Current ranking analysis with waiver pool is required'});const mine=analysis.team_details.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return res.status(400).json({error:'Your normalized roster was not found'});const slots=context.league?.roster_positions||[],basePlayers=mine.players||[],baseW=total(optimize(basePlayers,slots,'weekly_points')),baseR=total(optimize(basePlayers,slots,'ros_points')),results=[];
const ownedIds=new Set();for(const team of context.league_teams||[])for(const p of team.players||[]){for(const v of [p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id])if(v!==null&&v!==undefined&&String(v)!=='')ownedIds.add(String(v));}
const isOwned=p=>[p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id].some(v=>v!==null&&v!==undefined&&String(v)!==''&&ownedIds.has(String(v)));
const rawCandidates=(analysis.waiver_pool||[]).slice(0,100),candidates=rawCandidates.filter(p=>!isOwned(p));
for(const add of candidates){let best=null;for(const drop of basePlayers){if(identity(drop)===identity(add))continue;const roster=basePlayers.filter(p=>identity(p)!==identity(drop)).concat([{...add,position:posNorm(add.position)}]),w=total(optimize(roster,slots,'weekly_points')),r=total(optimize(roster,slots,'ros_points')),weeklyGain=Number((w-baseW).toFixed(1)),rosGain=Number((r-baseR).toFixed(1)),score=rosGain+weeklyGain*0.35;if(!best||score>best.score)best={drop,weeklyGain,rosGain,score}}if(best&&(best.rosGain>0||best.weeklyGain>0)){results.push({add:{name:add.name,position:add.position,team:add.team,weekly_points:add.weekly_points,ros_points:add.ros_points,weekly_sources:add.weekly_sources,ros_sources:add.ros_sources,weekly_strength:strength(add.weekly_source_count),ros_strength:strength(add.ros_source_count),injury_status:add.injury_status||null},drop:{name:best.drop.name,position:best.drop.position,weekly_points:best.drop.weekly_points,ros_points:best.drop.ros_points},weekly_starter_gain:best.weeklyGain,ros_starter_gain:best.rosGain,upgrade_score:Number(best.score.toFixed(2))})}}
results.sort((a,b)=>b.upgrade_score-a.upgrade_score);const actionable=results.filter(x=>x.ros_starter_gain>=1||x.weekly_starter_gain>=2).slice(0,12);const watch=results.filter(x=>!actionable.includes(x)&&(x.ros_starter_gain>0||x.weekly_starter_gain>0)).slice(0,5);const verdict=actionable.length?'ADD':watch.length?'WATCH':'HOLD';return res.json({available:true,verdict,baseline:{weekly_starters:Number(baseW.toFixed(1)),ros_starters:Number(baseR.toFixed(1))},recommendations:actionable,watchlist:watch,no_move:actionable.length===0,availability_audit:{raw_pool:rawCandidates.length,verified_unowned:candidates.length,rostered_excluded:rawCandidates.length-candidates.length},note:actionable.length?'Only verified unowned players that materially improve the optimized lineup are shown. Exact add/drop pairs are simulated deterministically.':watch.length?'No clear add yet. These verified free agents create only a marginal lineup improvement, so they are WATCH candidates rather than forced moves.':'HOLD — no verified unowned player in the evaluated waiver pool improves your optimized lineup.'})}catch(e){return res.status(500).json({error:e.message})}}
