const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const present=finite;
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
function startSlots(slots=[]){return slots.filter(s=>!['BN','IR'].includes(s))}
function eligible(pos,slot){if(slot===pos)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(pos);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(pos);return false}
function optimize(players,slots,field){const used=new Set(),picks=[],order=[...startSlots(slots)].sort((a,b)=>{const r={QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8};return(r[a]||9)-(r[b]||9)});for(const slot of order){let best=null,bi=-1;players.forEach((p,i)=>{if(used.has(i)||!eligible(posNorm(p.position),slot)||!present(p[field]))return;const v=Number(p[field]);if(!best||v>Number(best[field])){best=p;bi=i}});if(best){used.add(bi);picks.push({slot,player:best,value:Number(best[field])})}}return picks}
const total=a=>a.reduce((n,x)=>n+Number(x.value||0),0);
function identity(p){return String(p.canonical_player_id||p.gsis_id||p.sleeper_id||p.espn_id||p.id||p.name)}
function strength(n){return n>=3?'3-source':n===2?'2-source':n===1?'Single Source':'No trusted value'}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const {context,analysis}=req.body||{};if(!context||!analysis?.team_details||!Array.isArray(analysis?.waiver_pool))return res.status(400).json({error:'Current ranking analysis with waiver pool is required'});const mine=analysis.team_details.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return res.status(400).json({error:'Your normalized roster was not found'});const slots=context.league?.roster_positions||[],basePlayers=mine.players||[],baseW=total(optimize(basePlayers,slots,'weekly_points')),baseR=total(optimize(basePlayers,slots,'ros_points')),results=[];
const ownedIds=new Set();for(const team of context.league_teams||[])for(const p of team.players||[]){for(const v of [p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id])if(v!==null&&v!==undefined&&String(v)!=='')ownedIds.add(String(v));}
const isOwned=p=>[p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id].some(v=>v!==null&&v!==undefined&&String(v)!==''&&ownedIds.has(String(v)));
const rawCandidates=(analysis.waiver_pool||[]).slice(0,100),candidates=rawCandidates.filter(p=>!isOwned(p));
for(const add of candidates){let best=null;for(const drop of basePlayers){if(identity(drop)===identity(add))continue;const roster=basePlayers.filter(p=>identity(p)!==identity(drop)).concat([{...add,position:posNorm(add.position)}]),w=total(optimize(roster,slots,'weekly_points')),r=total(optimize(roster,slots,'ros_points')),weeklyGain=Number((w-baseW).toFixed(1)),rosGain=Number((r-baseR).toFixed(1)),score=rosGain+weeklyGain*0.35;if(!best||score>best.score)best={drop,weeklyGain,rosGain,score}}if(best&&(best.rosGain>0||best.weeklyGain>0)){results.push({add:{name:add.name,position:add.position,team:add.team,weekly_points:add.weekly_points,ros_points:add.ros_points,weekly_sources:add.weekly_sources,ros_sources:add.ros_sources,weekly_strength:strength(add.weekly_source_count),ros_strength:strength(add.ros_source_count),injury_status:add.injury_status||null},drop:{name:best.drop.name,position:best.drop.position,weekly_points:best.drop.weekly_points,ros_points:best.drop.ros_points},weekly_starter_gain:best.weeklyGain,ros_starter_gain:best.rosGain,upgrade_score:Number(best.score.toFixed(2))})}}
results.sort((a,b)=>b.upgrade_score-a.upgrade_score);const actionable=results.filter(x=>x.ros_starter_gain>=1||x.weekly_starter_gain>=2).slice(0,12);return res.json({available:true,baseline:{weekly_starters:Number(baseW.toFixed(1)),ros_starters:Number(baseR.toFixed(1))},recommendations:actionable,no_move:actionable.length===0,availability_audit:{raw_pool:rawCandidates.length,verified_unowned:candidates.length,rostered_excluded:rawCandidates.length-candidates.length},note:actionable.length?'Only moves for players verified unowned in the current league context are shown. Exact add/drop pairs are simulated deterministically.':'No verified unowned player in the evaluated waiver pool clearly improves your optimized lineup right now.'})}catch(e){return res.status(500).json({error:e.message})}}
