const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const present=finite;
const posNorm=p=>String(p||'').toUpperCase()==='DST'?'DEF':String(p||'').toUpperCase();
function startSlots(slots=[]){return slots.filter(s=>!['BN','IR'].includes(s))}
function eligible(pos,slot){if(slot===pos)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(pos);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(pos);return false}
function optimize(players,slots,field){const used=new Set(),picks=[],order=[...startSlots(slots)].sort((a,b)=>{const r={QB:1,SUPER_FLEX:2,TE:3,RB:4,WR:5,FLEX:6,DEF:7,K:8};return(r[a]||9)-(r[b]||9)});for(const slot of order){let best=null,bi=-1;players.forEach((p,i)=>{if(used.has(i)||!eligible(posNorm(p.position),slot)||!present(p[field]))return;const v=Number(p[field]);if(!best||v>Number(best[field])){best=p;bi=i}});if(best){used.add(bi);picks.push({slot,player:best,value:Number(best[field])})}}return picks}
const total=a=>a.reduce((n,x)=>n+Number(x.value||0),0);
function identity(p){return String(p.canonical_player_id||p.gsis_id||p.sleeper_id||p.espn_id||p.id||p.name)}
function strength(n){return n>=3?'3-source':n===2?'2-source':n===1?'Single Source':'No trusted value'}
function tradeImpact(roster,slots){return{weekly:total(optimize(roster,slots,'weekly_points')),ros:total(optimize(roster,slots,'ros_points'))}}
function tradeSum(a,f){return a.reduce((n,p)=>n+(present(p[f])?Number(p[f]):0),0)}
function packageScore(give,get){const gv=tradeSum(give,'ros_points'),rv=tradeSum(get,'ros_points');return gv&&rv?Math.min(gv,rv)/Math.max(gv,rv):0}
function directSlotCount(slots,pos){return (slots||[]).filter(s=>s===pos).length}
function desiredDepthCount(slots,pos){if(pos==='RB'||pos==='WR')return Math.max(4,directSlotCount(slots,pos)+2);if(pos==='QB')return Math.max(2,directSlotCount(slots,'QB')+directSlotCount(slots,'SUPER_FLEX')+1);if(pos==='TE')return Math.max(2,directSlotCount(slots,'TE')+1);return 1}
function positionDepthValue(roster,slots,pos){const n=desiredDepthCount(slots,pos);return roster.filter(p=>posNorm(p.position)===pos&&present(p.ros_points)).map(p=>Number(p.ros_points)).sort((a,b)=>b-a).slice(0,n).reduce((a,b)=>a+b,0)}
function inferredNeeds(mine,slots){const ps=mine?.players||[],needs=[];for(const pos of ['RB','WR','QB','TE']){const have=ps.filter(p=>posNorm(p.position)===pos&&present(p.ros_points)).length,desired=desiredDepthCount(slots,pos);if(have<desired)needs.push(pos)}return needs}
function preferredPositions(context,mine,slots){if(Array.isArray(context?.trade_needs)&&context.trade_needs.length)return context.trade_needs.map(posNorm);if(String(context?.league?.id||'')==='1389377608638042112')return ['RB'];return inferredNeeds(mine,slots)}
function findTrades(context,analysis){
 const slots=context.league?.roster_positions||[],teams=analysis.team_details||[],mine=teams.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return{recommendations:[],needs:[]};
 const needs=preferredPositions(context,mine,slots),baseMine=tradeImpact(mine.players||[],slots),baseNeed={};needs.forEach(p=>baseNeed[p]=positionDepthValue(mine.players||[],slots,p));const ideas=[];
 for(const opp of teams){if(opp===mine)continue;const baseOpp=tradeImpact(opp.players||[],slots),myPool=(mine.players||[]).filter(p=>present(p.ros_points)).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,14),theirPool=(opp.players||[]).filter(p=>present(p.ros_points)&&(!needs.length||needs.includes(posNorm(p.position)))).sort((a,b)=>Number(b.ros_points)-Number(a.ros_points)).slice(0,18);
  const test=(give,get)=>{if(!give.length||!get.length||packageScore(give,get)<0.72)return;if(needs.length&&!get.some(p=>needs.includes(posNorm(p.position))))return;const mineAfter=(mine.players||[]).filter(p=>!give.some(g=>identity(g)===identity(p))).concat(get),oppAfter=(opp.players||[]).filter(p=>!get.some(g=>identity(g)===identity(p))).concat(give),mi=tradeImpact(mineAfter,slots),oi=tradeImpact(oppAfter,slots),myWG=mi.weekly-baseMine.weekly,myRG=mi.ros-baseMine.ros,opWG=oi.weekly-baseOpp.weekly,opRG=oi.ros-baseOpp.ros;let bestNeedPos=null,needGain=0;for(const pos of needs){const g=positionDepthValue(mineAfter,slots,pos)-(baseNeed[pos]||0);if(g>needGain){needGain=g;bestNeedPos=pos}}const helpsUs=myRG>0||(needGain>=5&&myRG>=-2),helpsThem=opRG>0&&(opWG>=-2||opRG>=5);if(!helpsUs||!helpsThem)return;ideas.push({partner:opp.team,you_send:give.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points})),you_receive:get.map(p=>({name:p.name,position:p.position,weekly_points:p.weekly_points,ros_points:p.ros_points})),fills_need:bestNeedPos?bestNeedPos+' depth':null,need_gain:+needGain.toFixed(1),your_weekly_gain:+myWG.toFixed(1),your_ros_gain:+myRG.toFixed(1),their_weekly_gain:+opWG.toFixed(1),their_ros_gain:+opRG.toFixed(1),balance:+packageScore(give,get).toFixed(2),score:+(myRG+opRG+Math.max(0,myWG)+Math.max(0,opWG)+needGain*0.35).toFixed(1)})};
  for(const a of myPool)for(const b of theirPool)test([a],[b]);
  for(let i=0;i<myPool.length;i++)for(let j=i+1;j<Math.min(myPool.length,i+6);j++)for(const b of theirPool)test([myPool[i],myPool[j]],[b]);
  for(const a of myPool)for(let i=0;i<theirPool.length;i++)for(let j=i+1;j<Math.min(theirPool.length,i+6);j++)test([a],[theirPool[i],theirPool[j]])
 }
 ideas.sort((a,b)=>b.score-a.score);const uniq=[],seenPackages=new Set(),targetCounts=new Map();for(const x of ideas){const packageKey=x.partner+'|'+x.you_send.map(p=>p.name).sort().join('+')+'|'+x.you_receive.map(p=>p.name).sort().join('+');const targetKey=x.you_receive.map(p=>p.name).sort().join('+');if(seenPackages.has(packageKey))continue;const targetCount=targetCounts.get(targetKey)||0;if(targetCount>=2)continue;seenPackages.add(packageKey);targetCounts.set(targetKey,targetCount+1);uniq.push(x);if(uniq.length>=10)break}return{recommendations:uniq,needs}
}

export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const {context,analysis,mode}=req.body||{};if(mode==='trades'){if(!context||!analysis?.team_details)return res.status(400).json({error:'Current normalized league analysis is required'});const out=findTrades(context,analysis),recommendations=out.recommendations;return res.json({available:true,needs:out.needs,recommendations,no_trade:recommendations.length===0,note:recommendations.length?'Trade Finder is targeting '+(out.needs.length?out.needs.join('/')+' depth':'your weakest roster roles')+' and only showing deals that help the other roster too.':'HOLD — no mutually beneficial trade that fills the identified roster need was found in the evaluated player pool.'})}if(!context||!analysis?.team_details||!Array.isArray(analysis?.waiver_pool))return res.status(400).json({error:'Current ranking analysis with waiver pool is required'});const mine=analysis.team_details.find(t=>String(t.roster_id)===String(context.my_team?.roster_id)||t.team===context.my_team?.team);if(!mine)return res.status(400).json({error:'Your normalized roster was not found'});const slots=context.league?.roster_positions||[],basePlayers=mine.players||[],baseW=total(optimize(basePlayers,slots,'weekly_points')),baseR=total(optimize(basePlayers,slots,'ros_points')),results=[];
const ownedIds=new Set();for(const team of context.league_teams||[])for(const p of team.players||[]){for(const v of [p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id])if(v!==null&&v!==undefined&&String(v)!=='')ownedIds.add(String(v));}
const isOwned=p=>[p.canonical_player_id,p.gsis_id,p.sleeper_id,p.espn_id,p.id].some(v=>v!==null&&v!==undefined&&String(v)!==''&&ownedIds.has(String(v)));
const rawCandidates=(analysis.waiver_pool||[]).slice(0,100),candidates=rawCandidates.filter(p=>!isOwned(p));
for(const add of candidates){let best=null;for(const drop of basePlayers){if(identity(drop)===identity(add))continue;const roster=basePlayers.filter(p=>identity(p)!==identity(drop)).concat([{...add,position:posNorm(add.position)}]),w=total(optimize(roster,slots,'weekly_points')),r=total(optimize(roster,slots,'ros_points')),weeklyGain=Number((w-baseW).toFixed(1)),rosGain=Number((r-baseR).toFixed(1)),score=rosGain+weeklyGain*0.35;if(!best||score>best.score)best={drop,weeklyGain,rosGain,score}}if(best&&(best.rosGain>0||best.weeklyGain>0)){results.push({add:{name:add.name,position:add.position,team:add.team,weekly_points:add.weekly_points,ros_points:add.ros_points,weekly_sources:add.weekly_sources,ros_sources:add.ros_sources,weekly_strength:strength(add.weekly_source_count),ros_strength:strength(add.ros_source_count),injury_status:add.injury_status||null},drop:{name:best.drop.name,position:best.drop.position,weekly_points:best.drop.weekly_points,ros_points:best.drop.ros_points},weekly_starter_gain:best.weeklyGain,ros_starter_gain:best.rosGain,upgrade_score:Number(best.score.toFixed(2))})}}
results.sort((a,b)=>b.upgrade_score-a.upgrade_score);const actionable=results.filter(x=>x.ros_starter_gain>=1||x.weekly_starter_gain>=2).slice(0,12);const watch=results.filter(x=>!actionable.includes(x)&&(x.ros_starter_gain>0||x.weekly_starter_gain>0)).slice(0,5);const verdict=actionable.length?'ADD':watch.length?'WATCH':'HOLD';return res.json({available:true,verdict,baseline:{weekly_starters:Number(baseW.toFixed(1)),ros_starters:Number(baseR.toFixed(1))},recommendations:actionable,watchlist:watch,no_move:actionable.length===0,availability_audit:{raw_pool:rawCandidates.length,verified_unowned:candidates.length,rostered_excluded:rawCandidates.length-candidates.length},note:actionable.length?'Only verified unowned players that materially improve the optimized lineup are shown. Exact add/drop pairs are simulated deterministically.':watch.length?'No clear add yet. These verified free agents create only a marginal lineup improvement, so they are WATCH candidates rather than forced moves.':'HOLD — no verified unowned player in the evaluated waiver pool improves your optimized lineup.'})}catch(e){return res.status(500).json({error:e.message})}}
